### ISSUE TITLE
Request to tie table_open_cache increase messages to open_files_limit 

### ISSUE THREAD

**Issue by davidfavor** [major/MySQLTuner-perl#101]
Took me a while to figure out table_open_cache + innodb_open_files (+ something else which evades me) are capped by open_files_limit.

So great additional info would be to mention in table_open_cache if open_files_limit must also be increased to allow table_open_cache to have any effect.

Not pressing. Just good info to speed up the tuning process.

Thanks.

**Comment by jmrenouard** [comment]
General recommandations added:
push(@generalrec,"Beware that open_files_limit (".$myvar{'open_files_limit'}.") variable ");
push(@generalrec,"should be greater that $table_cache_var ( ".$myvar{$table_cache_var}.")");

**Comment by jmrenouard** [comment]
IIs it ok for You ?

JM

**Comment by jmrenouard** [comment]
Thanks for reporting this issue :)
