### ISSUE TITLE
warning for user@host has user name as password but user has no login and is locked.

### ISSUE THREAD

**Issue by MassimoDIFA** [major/MySQLTuner-perl#102]
Hi have an user with no login and locked but I get this warning:

-------- Security Recommendations ----------
[!!] User 'vertigo@localhost' has user name as password.

-------- Recommendations --------
General recommendations:
Set up a Secure Password for user@host ( SET PASSWORD FOR 'user'@'SpecificDNSorIp' = PASSWORD('secure_password'); )

**Comment by jmrenouard** [comment]
Hi,

How do you exactely lock your account ?
do you use expires field in mysql.user table ?

If you user has no password, the message should be 
User 'vertigo@localhost' has no password set.

In your case, user and password is are the same.
and match the following SQL request according mysqltuner code:

SELECT CONCAT(user, '\@', host) FROM mysql.user WHERE CAST(password as Binary) = PASSWORD(user) OR CAST(password as Binary) = PASSWORD(UPPER(user)) OR CAST(password as Binary) = PASSWORD(UPPER(LEFT(User, 1)) + SUBSTRING(User, 2, LENGTH(User)))

It is strange could you give me more feedback ?

Thanks by advance,
JM

**Comment by grooverdan** [comment]
looks like mysq-5.7 - https://dev.mysql.com/doc/refman/5.7/en/account-locking.html  / https://dev.mysql.com/doc/refman/5.7/en/show-create-user.html

**Comment by MassimoDIFA** [comment]
Hi @jmrenouard, sorry for delay.
lock or unlocks user doesn't make difference for passwords.
I don't use expires field in mysql.user table.

I have changed passwd for that user but I still get the Warming.

Thanks, bye.

**Comment by jmrenouard** [comment]
If we are looking for bad passwords or missing password, it doesn't make sense to avoid password for locked account ?

I closed this issue, feel free to reopen this issue if needed.
