### ISSUE TITLE
innodb_buffer_pool_instances should be bound by 64

### ISSUE THREAD

**Issue by phunehehe** [major/MySQLTuner-perl#103]
As the documentation stated, the maximum value for this param is 64 https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_buffer_pool_instances

**Comment by jmrenouard** [comment]
Hello,

Line 1426 of current git version:
A warning is displayed if innodb_buffer_pool_instances > 64.

	# InnoDB Buffer Pull Instances (MySQL 5.6.6+)
	if (defined($myvar{'innodb_buffer_pool_instances'})) {
		# Bad Value if > 64
		if ($myvar{'innodb_buffer_pool_instances'} > 64) {
			badprint "InnoDB buffer pool instances: ".$myvar{'innodb_buffer_pool_instances'}."\n";
			push(@adjvars,"innodb_buffer_pool_instances (<= 64)");
		} 


I don't know if this is the real sense of you thoughts, if not don't hesitate to push us more feedback !

Best regards,
JM

**Comment by phunehehe** [comment]
Ah, I didn't see that, but I did see that the script suggests I use a `innodb_buffer_pool_instances` of 100, supposedly because I'm using 100GB of `innodb_buffer_pool_size`.

**Comment by jmrenouard** [comment]
Ok I see :)

**Comment by jmrenouard** [comment]
Can you give me your feedback about the last version ?

**Comment by phunehehe** [comment]
Looking great, thanks!
