### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by TabSystems** [major/MySQLTuner-perl#107]
http://mysqltuner.com/ claims:

You can download the entire repository by using 'git clone' followed by the cloning URL above. The simplest and shortest method is:

wget mysqltuner.pl
wget https://raw.githubusercontent.com/major/MySQLTuner-perl/master/basic_passwords.txt -O basic_passwords.txt
perl mysqltuner.pl

this seems wrong 
- wget mysqltuner.pl without -O gets file as index.html not as .pl
- why would I need the basic pwd list? I think it is to test for weak pwds but could be mentioned.

**Comment by kn007** [comment]
Using 
```
wget http://mysqltuner.pl/ -O mysqltuner.pl
```
basic_passwords.txt is not required.

**Comment by kn007** [comment]
You can see
https://github.com/major/MySQLTuner-perl#downloadinstallation

**Comment by jmrenouard** [comment]
Update done !
