### ISSUE TITLE
Experiencing Several Errors

### ISSUE THREAD

**Issue by dave0783** [major/MySQLTuner-perl#108]
I cloned the repo, and am trying to run this but and experiencing alot of errors.  Here is an example of some

```
Use of uninitialized value in addition (+) at ./mysqltuner.pl line 670, <> line
	2 (#1)
Use of uninitialized value in multiplication (*) at ./mysqltuner.pl line 672,
	<> line 2 (#1)
Use of uninitialized value in numeric gt (>) at ./mysqltuner.pl line 676, <>
	line 2 (#1)
Use of uninitialized value $mycalc{"max_tmp_table_size"} in addition (+) at
	./mysqltuner.pl line 677, <> line 2 (#1)
Use of uninitialized value in addition (+) at ./mysqltuner.pl line 677, <> line
	2 (#1)
Use of uninitialized value in division (/) at ./mysqltuner.pl line 692, <> line
	2 (#1)

Illegal division by zero at ./mysqltuner.pl line 692, <> line 2 (#3)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.

Uncaught exception from user code:
	Illegal division by zero at ./mysqltuner.pl line 692, <> line 2.
	main::calculations() called at ./mysqltuner.pl line 1083
```

I am using:
* Perl v5.18.2
* Mysql 5.6.24
* OSX 10.10.4

**Comment by jmrenouard** [comment]
Hi,

Thanks for your feedback !

However, line indicated in your script doesn't match with the current github version.

For example, line 692 :    if (@mysqlstatlist) {
And your script indicate an illegal value in division
Use of uninitialized value in division (/) at ./mysqltuner.pl line 692, <> line
    2 (#1)

This line is not a math operation code line.

Can you give us the result of following command:
 mysqltuner.pl --debug

**Comment by dave0783** [comment]
My apologies, I was on the 1.4.0 branch. I switched back to master and am still getting similar errors.  here is an example

```
Use of uninitialized value $mysqlvermajor in numeric gt (>) at ./mysqltuner.pl
	line 875 (#2)
Use of uninitialized value $mysqlvermajor in numeric eq (==) at ./mysqltuner.pl
	line 875 (#2)
Use of uninitialized value in addition (+) at ./mysqltuner.pl line 1175 (#2)
Use of uninitialized value in multiplication (*) at ./mysqltuner.pl line 1182 (#2)
Use of uninitialized value in numeric gt (>) at ./mysqltuner.pl line 1188 (#2)
Use of uninitialized value $mycalc{"max_tmp_table_size"} in addition (+) at
	./mysqltuner.pl line 1192 (#2)
Use of uninitialized value in addition (+) at ./mysqltuner.pl line 1192 (#2)
Use of uninitialized value in division (/) at ./mysqltuner.pl line 1243 (#2)

Illegal division by zero at ./mysqltuner.pl line 1243 (#3)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.

Uncaught exception from user code:
	Illegal division by zero at ./mysqltuner.pl line 1243.
	main::calculations() called at ./mysqltuner.pl line 2658
```

**Comment by dave0783** [comment]
Also running ./mysqltuner.pl is dumping many more lines than I am used to.  I have run this in the past, had no issue and didn't see as much output; its almost as if its stuck in debug mode somehow.

**Comment by dave0783** [comment]
I figured it out. I had the followign in my .my.cnf
```
[mysql]
user=root
auto-vertical-output=true
```

Commenting out `auto-vertical-output=true` fixed the problem.

**Comment by jmrenouard** [comment]
I can find an option to avoid this parameter :(

We can also display a error message at startup for indicating that this option is incompatible with mysqltuner.

Want do you think about that ?

**Comment by jmrenouard** [comment]
I have added --auto-vertical-output=false in the commande line for mysql client.

This should solved your problem.

**Comment by dave0783** [comment]
Cool, thanks for your help!
