### ISSUE TITLE
add noask for cronjobs etc so mysqltuner would not ask for anything

### ISSUE THREAD

**Issue by gemal** [major/MySQLTuner-perl#110]
would be nice to have the ability to call mysqltuner with "--noask" and it would NOT ask for any login information if the provided login info was wrong
The would prevent a cronjob hanging forever

```
[root@vm0268 util]# perl mysqltuner.pl --user mysqltuner
Please enter your MySQL administrative login:
```

so I would get:
```
[root@vm0268 util]# perl mysqltuner.pl --user mysqltuner --noask
Attempted to use login credentials, but they were invalid
[root@vm0268 util]#
```

**Comment by jmrenouard** [comment]
Can you please give me your feedback  ??

**Comment by gemal** [comment]
perfect
