### ISSUE TITLE
MariaDB 10.0

### ISSUE THREAD

**Issue by tokar86a** [major/MySQLTuner-perl#111]
Hi

should not MariaDB 10.0 be supported? when i run the script i get this: Currently running unsupported MySQL version 10.0.21-MariaDB

What is it?

**Comment by jmrenouard** [comment]
Thanks for your feedback.

**Comment by jmrenouard** [comment]
Can you please give me your feedback  ??

**Comment by tokar86a** [comment]
What sort of feedback?

**Comment by jmrenouard** [comment]
I have push a fix for MariaDB version check.

Now version better 10 and 11 are normally support and warning message no longer displayed.

**Comment by jmrenouard** [comment]
MariaDB is supported version :)

**Comment by jmrenouard** [comment]
Is it right for you ?
Do you still have the message ?

**Comment by tokar86a** [comment]
Yes everything is working now. I dont get the message.
