### ISSUE TITLE
"Access denied; you need at least xxx" at top of output

### ISSUE THREAD

**Issue by gemal** [major/MySQLTuner-perl#112]
is it OK that the script reports errors like this when it needs more permissions?
Just wondering

```
[root@vm0268 util]# perl mysqltuner.pl --user mysqltuner
 >>  MySQLTuner 1.5.1 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
ERROR 1227 (42000) at line 1: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation
ERROR 1227 (42000) at line 1: Access denied; you need (at least one of) the REPLICATION SLAVE privilege(s) for this operation
```

**Comment by jmrenouard** [comment]
Thanks for your feedback.

Yes because it's one of the best way to alert on missing permissions (privileges) for mysql user used by mysqltuner.

I am ok that a better error/warning message can be displayed in this case.

Do you have a idea of a message for this case ?

Thanks for your reply.

**Comment by mahemoff** [comment]
Not sure if it's within the same issue scope, but I'd like to suggest these permission related errors be shown only once per script run. Presently, I see the same error repeated dozens of times if not running it as root.

**Comment by jmrenouard** [comment]
User should be create locally as is:
GRANT ALL PRIVILEGES ON *.* TO 'mysqltuner'@localhost IDENTIFIED BY 'xxxxx';

**Comment by mahemoff** [comment]
Okay thanks.
