### ISSUE TITLE
minor text fixes

### ISSUE THREAD

**Issue by gemal** [major/MySQLTuner-perl#113]
"There is not basic password file list !" => "There is no basic password file list!"
"InnoDB  buffer pool / data size:" => "InnoDB buffer pool / data size:

**Comment by gemal** [comment]
I have patches for this. Not sure how I make a pull requets

**Comment by kn007** [comment]
To JM, another one:
https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L1923
```
"should be greater that $table_cache_var ( "
```
->
```
"should be greater that $table_cache_var ("
```
