### ISSUE TITLE
unknown variable

### ISSUE THREAD

**Issue by klara31** [major/MySQLTuner-perl#117]
running on commit f10df53c9bc9a6af54217cb42e643e271f0dc7f8, I am getting multiple lines of this error:
````/usr/bin/mysql: unknown variable 'defaults-file=/etc/mysql/debian.cnf'````

**Comment by jmrenouard** [comment]
Can you give me your mysql version please ?

**Comment by Monter** [comment]
I have the same result. Mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by Shaddow-es** [comment]
Same error using Debian 8.1

MySQL Server version: 5.5.44-0+deb8u1 (Debian)
Linux .host 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux

**Comment by klara31** [comment]
I am running Percona Server, version 5.6.25-73.1-1.vivid on an Ubuntu server 15.04 with kernel 3.19.0-26-generic

**Comment by CaracalSef** [comment]
Same problem.
Linux rullz.us 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux

Distributor ID: Debian
Description:    Debian GNU/Linux 8.1 (jessie)
Release:        8.1
Codename:       jessie

mysqld  Ver 5.5.44-0+deb8u1 for debian-linux-gnu on x86_64 ((Debian))

mysqltuner.pl - Version 1.5.1

**Comment by jmrenouard** [comment]
I have rollback modifications about (auto-vertical-output option).

Can you tell me if this is fixing this issue ?

**Comment by klara31** [comment]
It is working again without the messages.

**Comment by jmrenouard** [comment]
Perfect, it is a side effect for issue fix
 unknown variable 'auto-vertical-output=false' #118 

All apologizes :)

**Comment by Shaddow-es** [comment]
@jmrenouard thank you!

**Comment by jmrenouard** [comment]
Is there anybody experimenting or reproducing this issue ?

**Comment by Monter** [comment]
Version 1.5.2 works correctly. Thanks.

**Comment by jmrenouard** [comment]
I close this issue is it ok ?
If something similar appears reopen the issue ...

Best regards.
