### ISSUE TITLE
unknown variable 'auto-vertical-output=false'

### ISSUE THREAD

**Issue by maartenq** [major/MySQLTuner-perl#118]
After commit 3f78587   mysqltuner.pl exits with 2 On mysql-server-5.1.73-5.el6_6.x86_64 (RHEL 6.7) 
with error:
/usr/bin/mysql: unknown variable 'auto-vertical-output=false'

commit   3f78587 works fine

**Comment by jmrenouard** [comment]
Can you test the lest version ?

If mysql < 5.5 then we don't use this option.

Thanks for your feedback.

**Comment by maartenq** [comment]
Yes daf7794 works for me.
Thx
