### ISSUE TITLE
Ignore lost+found

### ISSUE THREAD

**Issue by fryguy451** [major/MySQLTuner-perl#121]
Can the lost+found directory be ignored?

ERROR 1018 (HY000) at line 1: Can't read dir of './lost+found/' (errno: 13)
Argument "NULL" isn't numeric in numeric gt (>) at ./mysqltuner.pl line 1630 (#1)
    (W numeric) The indicated string was fed as an argument to an operator
    that expected a numeric value instead.  If you're fortunate the message
    will identify which operator was so unfortunate.
    
Argument "NULL" isn't numeric in addition (+) at ./mysqltuner.pl line 1623 (#1)

**Comment by jmrenouard** [comment]
Can you tell me if it solved this issue ?

**Comment by fryguy451** [comment]
It doesn't complain about lost+found but it still shows the following message. I'm not sure if it's related or completely separate.

Argument "NULL" isn't numeric in numeric gt (>) at ./mysqltuner.pl line 1631 (#1)
    (W numeric) The indicated string was fed as an argument to an operator
    that expected a numeric value instead.  If you're fortunate the message
    will identify which operator was so unfortunate.
    
Argument "NULL" isn't numeric in addition (+) at ./mysqltuner.pl line 1624 (#1)

**Comment by fryguy451** [comment]
]# ls -la /var/lib/mysql
total 1084516
drwxr-xr-x  5 mysql mysql      4096 Jun  1 16:26 .
drwxr-xr-x 30 root  root       4096 Mar 17  2014 ..
-rw-rw----  1 mysql mysql  35651584 Sep  2 07:30 ibdata1
-rw-rw----  1 mysql mysql 536870912 Sep  2 07:30 ib_logfile0
-rw-rw----  1 mysql mysql 536870912 Sep  2 07:29 ib_logfile1
drwx------  2 root  root      16384 Nov 11  2014 lost+found
drwx------  2 mysql mysql      4096 Aug 19  2013 mysql
srwxrwxrwx  1 mysql mysql         0 Jun  1 16:26 mysql.sock
drwx------  2 mysql mysql     20480 Aug 31 05:42 WebHelpDesk

**Comment by jmrenouard** [comment]
I have fix some default value unset.
Can you tell me if it solved this issue ?

**Comment by fryguy451** [comment]
Resolved the unset values, but lost+found shows in a different location now.

-------- Storage Engine Statistics -------------------------------------------
[--] Status: -Archive -BDB -Federated +InnoDB -ISAM -Aria -NDBCluster 
[--] Data in NULL tables: 0B (Tables: 5)
[--] Data in InnoDB tables: 8G (Tables: 208)
[OK] Total fragmented tables: 0
ERROR 1018 (HY000) at line 1: Can't read dir of './lost+found/' (errno: 13)

**Comment by jmrenouard** [comment]
Can you tell me if it solved this issue ?

**Comment by fryguy451** [comment]
That seems to have solved the issue. Thanks.

**Comment by jmrenouard** [comment]
Nice, I closed this issue.
