### ISSUE TITLE
Better template for MySQLTuner

### ISSUE THREAD

**Issue by jmrenouard** [major/MySQLTuner-perl#122]
We have introduce since 1.6.X versions a template system based on Text::Template.

Test::Template is embedded in mysqltuner for the moment in 1.46 version.

MysqlTuner is filling a big structure called result.

the actual rendering template is displaying this structure in a basic html page formatted by Data::Dumper package.

We need help because we think that a better rendering html report is possible.

Some of the main ideas is using bootstrap js, jsgraph or morrisjs to include graph around metrics mysqltuner is actually collecting.

so, in order to perform this feature, you can in order do:
1° perl mysqltuner.pl --silent -dbstat --idxstat --reportfile /tmp/result_mysqltuner.txt 
This command will help you to get information about %result structure.

2° Create a new model based on 
https://github.com/major/MySQLTuner-perl/blob/master/template_example.tpl

3° test your rendering result with 
perl mysqltuner.pl --silent -dbstat --idxstat --reportfile /tmp/result_mysqltuner.txt --template=/tmp/mymodel.tmpl 

Thanks by advance for your help :)

**Comment by jmrenouard** [comment]
In order to understand way to realize a template, you can have alook at 
http://search.cpan.org/~mjd/Text-Template-1.46/lib/Text/Template.pm

**Comment by jmrenouard** [comment]
Now and then, we already get a json output mode for mysqltuner.

Is there anybody want to provide us a beautiful HTML/JS/bootstrap template to wrap around this new feature ?

Imagine providing a all-in-one html page with a beautiful rendering view ! Would it be nice ?

I think it can be too !

**Comment by DutchProgrammer** [comment]
I will check this.

I also updated the json option in my fork
Maybe it's an idea to create an directadmin plugin as well so people can check directly in directadmin.

**Comment by JTheLord** [comment]
Setup did as specified. 
I get errors when I run?
Attempted to use login credentials from DirectAdmin, but they failed.
How can I solve this problem.

**Comment by jmrenouard** [comment]
I start coding some staff in runAudit.sh and txt2Html.pl.
