### ISSUE TITLE
History metrics collect and rendering

### ISSUE THREAD

**Issue by jmrenouard** [major/MySQLTuner-perl#123]
MySQLTuner is not able to collect metrics and giving a time based evolution of metrics collected.

The idea is to store and render historical information about metrics.

1° detect parameters that have changed since the last time.
2° Giving information about when and hos many times parameters has been changed.
3° Using rendering and template feature, to display this kind of information.

Thanks for your help :)

**Comment by skynet** [comment]
Might as well just write a https://github.com/influxdb/telegraf plugin.

**Comment by jmrenouard** [comment]
Why not !
Do you have some awaited format for telegraf ?

We can use rendering template to generate output suitable for telegraf.

Thanks for your feedback.

**Comment by skynet** [comment]
To test we can use the https://github.com/influxdb/telegraf/tree/master/plugins/exec plugin which simply ingests json. Can you provide txt or json output with tuner metrics?

**Comment by jmrenouard** [comment]
Yes I thnik I can do it :)
Is there any specific output awaited ?

**Comment by skynet** [comment]
json

**Comment by denji** [comment]
###### Advanced Analytics/Monitoring/Aggregator
* https://github.com/mysql/mysql-sys
* https://github.com/datacharmer/mysql-sandbox
* https://github.com/square/inspect
* https://github.com/sjmudd/ps-top
* https://github.com/vadimtk/metrics-collector
* https://github.com/jayjanssen/myq-tools#myq-tools-
* https://github.com/jamesrwhite/tsadmin#tsadmin – Get a realtime overview of your MySQL servers
* https://github.com/open-falcon/mymon – MySQL Monitor Script

---

* https://github.com/morgo/mysql-compatibility-config
* https://github.com/outbrain/orchestrator#orchestrator-manual
* https://github.com/datacharmer/mysql-replication-samples#mysql-replication-samples
* https://github.com/pinterest/mysql_utils#pinterest-mysql-management-tools
* https://github.com/junhe/mysql-io-pattern

**Comment by jmrenouard** [comment]
Json output is now available.

**Comment by skynet** [comment]
Excellent, thank you!

**Comment by jmrenouard** [comment]
Hi @skynet,

Do you have some feedback with JSON output ?

Thanks by advance,

**Comment by skynet** [comment]
Not yet, but soon, thanks!

**Comment by jmrenouard** [comment]
Grafana graphs are available from:
https://grafana.net/plugins/percona-percona-app
https://github.com/percona/grafana-dashboards

Statd for MySQL:
https://github.com/db-art/mysql-statsd

Great projects !
