### ISSUE TITLE
Aria not using indexes

### ISSUE THREAD

**Issue by ZeNerzhul** [major/MySQLTuner-perl#130]
Hello,

In 1.6.0 version at the line 1912 you have an issue.

replace $mycalc{'total_aria_indexe'} = select_one
with $mycalc{'total_aria_indexes'} = select_one

;-)

**Comment by jmrenouard** [comment]
Thanks for your feedback :)

**Comment by ZeNerzhul** [comment]
Non mais "You welcome" monsieur Renouard
