### ISSUE TITLE
Extra requirement Text::Template on latest git master

### ISSUE THREAD

**Issue by Vash63** [major/MySQLTuner-perl#133]
Hi all, the removal of the Text::Template module in the following commit adds extra steps before this can be run on a stock CentOS server, including cPanel builds.
9d22307754887f0278a2601ed07afcba2a156ae3

This is more of a feature request than a bug but when working on many servers it's more convenient if the default perl packages in common distributions are able to run it without additional installs. At very least a cleaner error indicating that you must install Text::Template would be nicer as well as a note on the readme of its new requirement.

**Comment by biga2000** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

biga2000@naver.com 님께 보내신 메일 <[MySQLTuner-perl] Extra requirement Text::Template on latest git master (#133)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by JDavidRogers** [comment]
```
BEGIN failed--compilation aborted at /home/user/cron/MySQLTuner-perl/mysqltuner.pl line 2816 (#1)
    (F) You said to do (or require, or use) a file that couldn't be
    found. Perl looks for the file in all the locations mentioned in @INC,
    unless the file name included the full path to the file.  Perhaps you
    need to set the PERL5LIB or PERL5OPT environment variable to say where
    the extra library is, or maybe the script needs to add the library name
    to @INC.  Or maybe you just misspelled the name of the file.  See
    perlfunc/require and lib.

Uncaught exception from user code:
        Can't locate Text/Template.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/user/cron/MySQLTuner-perl/mysqltuner.pl line 2816.
BEGIN failed--compilation aborted at /home/user/cron/MySQLTuner-perl/mysqltuner.pl line 2816.
 at /home/user/cron/MySQLTuner-perl/mysqltuner.pl line 2816
```

**Comment by biga2000** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

biga2000@naver.com 님께 보내신 메일 <Re: [MySQLTuner-perl] Extra requirement Text::Template on latest git master (#133)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by ckoerner** [comment]
:+1:

**Comment by jmrenouard** [comment]
Ok,
I think you are right :)

I propose using Perl  APP::Fatten to generate an all in one script with embedded module.

Is it ok ?

**Comment by Vash63** [comment]
It was embedded before, definitely more convenient that way. I don't spend a lot of time in Perl but for my use case I work with a lot of different servers and not having to install dependencies is a big plus.

**Comment by cloos** [comment]
@jmrenouard actually your "conditional loading" of Text::Template doesn't work because you use "use Text::Template" which checks for Text::Template on compile time.
If you want to conditionally load a module you have to use require instead of use.

Same applies to you conditionally loading of Data::Dumper. I think this isn't necessary at all, because Data::Dumper is in core Perl since 5.005. So you can add 'use Data::Dumper' to the top and remove all other occurrences of this, and set a required minimum Perl version of 5.005.

**Comment by JDavidRogers** [comment]
@Vash63 I also would prefer a stand alone solution without needing the installation of dependencies.

**Comment by Juberstine** [comment]
I would also agree with @Vash63 and @JDavidRogers. For someone who might use this on 10+ unique servers a day and servers who do not explicitly belong to me, not having to installed added dependencies is a huge plus. If this can't be addressed, I will have no choice but to only use the versions before the change.
