### ISSUE TITLE
RFE: Support for counting thread pool in per-thread memory

### ISSUE THREAD

**Issue by Am1GO** [major/MySQLTuner-perl#138]
https://mariadb.com/kb/en/mariadb/thread-pool-in-mariadb/

**Comment by jmrenouard** [comment]
Ok, nic, I will look at it.

**Comment by jmrenouard** [comment]
Hello,

Do you have a special formula to calculate useful indicators with limit values ?

Thanks for you feedback....

**Comment by Am1GO** [comment]
Yes, I'll double-check and notify you.

**Comment by jmrenouard** [comment]
https://dev.mysql.com/doc/refman/5.6/en/thread-pool-tuning.html

According to offical oracle doc
https://dev.mysql.com/doc/refman/5.6/en/thread-pool-tuning.html

If innodb main storage: thread_pool_size between 16 to 36
If myisam main storage: thread_pool_size between 4 to 8

Rule coded:
If innodb usage => thread_pool_size between 16 to 36
If myisam usage => thread_pool_size between 4 to 8

**Comment by jmrenouard** [comment]
Can anyone can give me this feedback on this new indicator ?

**Comment by cloos** [comment]
MariaDB actually sets "number of processors" as default [1] and says
that the default should be ok for most cases [2].

[1] https://mariadb.com/kb/en/mariadb/thread-pool-in-mariadb
/#optimizing-server-variables-on-unix
[2]
https://mariadb.com/kb/en/mariadb/thread-pool-in-mariadb/#threadpool-server-variables

Am 22.03.2016 um 15:19 schrieb Jean-Marie Renouard:

**Comment by denji** [comment]
https://www.percona.com/doc/percona-server/5.6/performance/threadpool.html#version-specific-information

- Percona 5.6.15-63.0 Implemented new [thread_pool_high_prio_mode](https://www.percona.com/doc/percona-server/5.6/performance/threadpool.html#thread_pool_high_prio_mode) variable.
- Percona 5.6.15-63.0 Implemented [Low priority queue throttling](https://www.percona.com/doc/percona-server/5.6/performance/threadpool.html#low-priority-queue-throttling).

**Comment by jmrenouard** [comment]
Thanks @cloos @denji

**Comment by jmrenouard** [comment]
So want do you think we must do with this indicators to enhance MT ?

**Comment by jmrenouard** [comment]
I closed this issue after my last commit !
For MariaDB and Percona message telling default value are good enough.

**Comment by jmrenouard** [comment]
Thanks @cloos @denji
