### ISSUE TITLE
Please conider to put password to the temporary config file to avoid warnings

### ISSUE THREAD

**Issue by vrtareg** [major/MySQLTuner-perl#143]
Hi

In latest MySQL versions there is a warning shown if password is passed to the command line.

> Warning: Using a password on the command line interface can be insecure.

The workaround of this or suppress this warning which is not nice or use some temporary MySQL config file which can be passed to mysql executables via _"--defaults-extra-file"_ option.

Content of file can be
```
[client]
username = <username>
password = <pasword>
```

Regards,
Areg

**Comment by jmrenouard** [comment]
README.md, in the FAQ chapter, all this details have been described :)

So, I closed this issue because it is an already documented aspect.

**Comment by vrtareg** [comment]
Thanks a lot. 

Sorry for false alarm. 
Should be reading that file first. 

Regards, 
Areg

**Comment by jmrenouard** [comment]
Hi

Thanks for asking questions.

If you want you can help us improving faq section so that mt users can find
easily this information.

Jm
