### ISSUE TITLE
Add metric for MariaDB Clustering (Galera Clustering)

### ISSUE THREAD

**Issue by DEV-Kapler** [major/MySQLTuner-perl#150]
There are serveral metrics, which are interessting in for a working or good performing cluster in
SHOW STATUS LIKE 'wsrep_%';

Also it is good to check from time to time to avoid a split brain condition. A offset may not appear a second time.
SHOW VARIABLES LIKE '%auto_increment%';

**Comment by jmrenouard** [comment]
Following information can be checked for this issue:
 QUORUM CHECK
 CLUSTER IS READY
 CLUSTER IS CONNECTED
 CLUSTER SPLIT BRAIN
 CLUSTER STATE
 CLUSTER CONF LEVEL
 CLUSTER SIZE LEVEL
 CLUSTER DATA UUID LEVEL
 LOCAL DATA UUID LEVEL
 LAST COMMITED LEVEL

**Comment by jmrenouard** [comment]
•	wsrep_ready cluster is ready
•	wsrep_connected node is connected to other nodes
•	wsrep_cluster_status PRIMARY /NON PRIMARY.
•	PRIMARY : Coherent cluster
•	NO PRIMARY : cluster gets several states
•	wsrep_ local_state_comment: Node state 
SYNCED (uptodate),
 DONOR(sending information to another node)
 Joiner(Try to reach cluster group)
•	SYNCED state able to read/write
•	wsrep_cluster_conf_id configuration level must be identical in all nodes
•	wsrep_last_commited committed level must be identical in all nodes

**Comment by jmrenouard** [comment]
I think all essential indicators are catched now by mt for galera.

I close this issue.
