### ISSUE TITLE
1.6.3 or 1.6.2

### ISSUE THREAD

**Issue by CrazyRedScorp** [major/MySQLTuner-perl#152]
Hello. Thanks for you.

But... In file mysqltuner in line 2
   https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L2
version 1.6.3

but in line 54
   https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L54
1.6.2

**Comment by jmrenouard** [comment]
I fix it in my last commit :)

**Comment by CrazyRedScorp** [comment]
Thanks!
