### ISSUE TITLE
Adding password strength metric for input password

### ISSUE THREAD

**Issue by 0xbsec** [major/MySQLTuner-perl#154]
I was thinking on adding password strength metric for the passed user/pass.
We can use an avariable module from CPAN, and if not installed give a simple estimation for strength.
Please tell me what you think, Thanks.
### Sample cases:
- cmd: perl mysqltuner.pl --user user --pass weakpass
 - output: [!!] Password for user is very weak
- cmd: perl mysqltuner.pl --user user --pass weakpass123456
 - output: [!!] Password for user is weak
- cmd: perl mysqltuner.pl --user user --pass 313weakpass337
 - output: [ok] Password for user is so-so
- cmd: perl mysqltuner.pl --user user --pass='Tr0ub4dor&3'
 - output: [ok] Password for user is strong
- cmd: perl mysqltuner.pl --user user --pass='correct horse battery staple :D'
 - output: [ok] Password for user is very strong

**Comment by jmrenouard** [comment]
Ok nice feature 
Thanks for this subjection

**Comment by jmrenouard** [comment]
Can you give us some further information about available CPAN Modules that can do this jobs ?

Thanks for your feedback.

**Comment by 0xbsec** [comment]
Maybe we can use `Data::Password::Entropy` ([metacpan](https://metacpan.org/pod/Data::Password::Entropy)) , it calculate the entropy of the password/passphrase. Example of values it give:

> 123456 -> 10
> weakpass -> 32
> weakpass123456 -> 53
> 313weakpass337 -> 56
> Tr0ub4dor&3 -> 65
> correct horse battery staple :D -> 130

so we can take 40 bits (or another value) entropy as a base value, so if it's > 40 it's strong, > 2*40 it's very strong an so on.

**Comment by cloos** [comment]
I think this is something that should be done if you try to create/set a wear password within the database, and not by a performance optimization script.

**Comment by 0xbsec** [comment]
@cloos Maybe it can be added under `Security Recommendations` or show like the `Successfully authenticated with no password` warning.

**Comment by jmrenouard** [comment]
Hi,

To be more precise on what's doing mysqltuner:

Security recommandations:
Successfully authenticated with no password is already included.
Bad password are already checked based on bad_password.txt file.

For code details:
Line 608:
               badprint
"Successfully authenticated with no password - SECURITY RISK!";

Line 850: Check for user without password

**Comment by jmrenouard** [comment]
There is already a bad password database .
https://github.com/major/MySQLTuner-perl/blob/master/basic_passwords.txt
All password are tested with basic passwords.
Please feel free to add new password if you like in this file.

**Comment by jmrenouard** [comment]
Your proposals is only useful for password used in command line.
Do you have an other idea about checking all password for all users in database ?

Do you want us to include a other script that can indicate password quality ?

I think you should have a look at security plugin (validate_password and password plugin) already avaivalble for MariaDB and MySQL.

**Comment by 0xbsec** [comment]
> Your proposals is only useful for password used in command line.

Yes, that's right.
>I think you should have a look at security plugin (validate_password and password plugin) already avaivalble for MariaDB and MySQL.

I've check it, sorry didn't know about the password policy rule (@cloos now I got your point).
@jmrenouard you can close the issue now.
