### ISSUE TITLE
Query cache should be disabled

### ISSUE THREAD

**Issue by jmrenouard** [major/MySQLTuner-perl#159]
Advise to disable QC by default.
 query cache is disabled in 5.6+ by default due to mutex contention.
From Morgan Tocker (PM MySQL).

**Comment by morgo** [comment]
LGTM :)  For references: [1](http://www.tocker.ca/2013/09/27/how-do-you-use-the-query-cache.html), [2](http://dba.stackexchange.com/questions/66774/why-query-cache-type-is-disabled-by-default-start-from-mysql-5-6), [3](https://www.flamingspork.com/blog/2014/06/05/performance-impact-of-mysql-query-cache-on-modern-hardware/).

**Comment by morgo** [comment]
See also: http://mysqlserverteam.com/mysql-8-0-retiring-support-for-the-query-cache/
