### ISSUE TITLE
apache running on 80 and 443 [question]

### ISSUE THREAD

**Issue by DutchProgrammer** [major/MySQLTuner-perl#163]
Hello,

In the section 'System Linux Recommendations' i get this message:
[!!] There is Apache like server running on 80 or 443 port.

but 80 is the default http port and 443 the default https port, what do you guys mean with this message ?

It's not recommended to change these ports.

In the source there is only an check if the ports are open
```perl

    if ( is_open_port(80) or is_open_port(443) ) {
	badprint "There is Apache like server running on 80 or 443 port.";
    	push( @generalrec, "Consider dedicating a server for Web server in production !" );
    }  else {
	goodprint "No Web server runing on 80 and 444 port.";
    }
```

**Comment by jmrenouard** [comment]
Hi @DutchProgrammer,

This warning is not for changing port but separate Apache, nginx, Tomcat, django/python services from server hosting your database.

In fact, having HTTP server on the same hosts can lead tuning recommandations direct to a OOM kill situation.

Applying mysqltuner recommandations can be valid only when:

1. There is no other server running on OS except classical service port (22, 25, ..)
2. Performance_schema is off
3. Galera and wsrep protocol are not activated.

So, I had a by default check for 80, 8080, 8443 and 443 port checking to detect presence of web server and web application server and warn for this.

I just push a modification to remove this and let user use bannedports option instead.

Thanks for your feedback.

**Comment by jmrenouard** [comment]
Can you tell me if it is better ?

**Comment by DutchProgrammer** [comment]
Thanks for explaining,
I understand what you mean but it's still a design choice most webservers/websites are good enough to let http server and database on the same server so i would suggest to just make a notice about it.

And maybe only to inform the user to separate the database and http server when the memory left is less then 800.000 kB ( just an idea )

**Comment by jmrenouard** [comment]
Principe coded:
if 15% of total RAM is used (RSS proc info), a warning is raised.

If user process excluded mysqld process is using more than 15% physical memory :
- Bad message: Other user process except mysqld used more than 15% of total physical memory "
- General recommendations: Consider stopping or dedicate server for additionnal process other than mysqld.
