### ISSUE TITLE
system recommandations: better indicators

### ISSUE THREAD

**Issue by jmrenouard** [major/MySQLTuner-perl#165]
Hi,

I have some ideas about system indicators : 

- Virtual or physical server
- Disk usage per mount point
- CPU Usage
- kernel tuning
- tuned daemon activated on Red hat / Centos 7+  
- vm.swapinness < 15
- some kernel limits
- some sysctl parameters

Is there any precision/ howto / you want to see in MysqlTuner ?

**Comment by DutchProgrammer** [comment]
@jmrenouard Nice update, useful info!

**Comment by mrqwer88** [comment]
1.
Virtual or physical server - it cannot detect containers and detect it like physical server.
Looks like it need additional check for exist /proc/user_beancounters and etc.
How example may be used - http://projects.puppetlabs.com/projects/1/wiki/Virtual_Machine_Patterns , imho.

2. Detect os release looks strange.
You mean not /etc/system-release, but /etc/os-release ?
as example - 
```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```
But old versions OS cannot have this os-release file, but usual have info about OS in /etc/issue.

**Comment by mrqwer88** [comment]
And
```
1157     infoprint "Network Cards         : ";
1158     infocmd_tab "ifconfig| grep -A1 mtu";
```
looks like freebsd only.
In linux in output "MTU", not "mtu" and name interface on another line.
And in centos 7 and etc ifconfig not install by default, it supposed to use ip command 	instead of ifconfig.

**Comment by mrqwer88** [comment]
Sorry - rpm based have /etc/system-release, but deb-based not have this file and goes to "Unknown OS release".
I try to fix it in get_os_release - 
https://github.com/major/MySQLTuner-perl/pull/178

**Comment by mrqwer88** [comment]
And fixes to mount point info - 
https://github.com/major/MySQLTuner-perl/commit/ff796b48bf5681f9be213fb69d9b1e4d17546509
In linux it not show disk space on / and show many virtual fs.
Output befor this changes - 
```
[--] Other user process except mysqld used less than 15% of total physical memory 4.33% (221M / 5G)
[--] mount point /sys/fs/cgroup is using 0 % of total space
[--] mount point /dev is using 0 % of total space
[--] mount point /dev/shm is using 0 % of total space
[--] mount point /run is using 3 % of total space
[--] mount point /run/lock is using 0 % of total space
[--] mount point /run/shm is using 0 % of total space
[--] mount point / is using 5 % of max allowed inodes
[--] mount point /sys/fs/cgroup is using 1 % of max allowed inodes
[--] mount point /dev is using 1 % of max allowed inodes
[--] mount point /dev/shm is using 1 % of max allowed inodes
[--] mount point /run is using 1 % of max allowed inodes
[--] mount point /run/lock is using 1 % of max allowed inodes
[--] mount point /run/shm is using 1 % of max allowed inodes

```

After - 
```
[--] Other user process except mysqld used less than 15% of total physical memory 4.50% (230M / 5G)
[--] mount point / is using 11 % of total space
[--] mount point / is using 5 % of max allowed inodes
```

**Comment by mrqwer88** [comment]
And now used third-party utilities like curl. And curl not install on all hosts( and ifconfig too).
And we have output like 
```
Can't exec "curl": No such file or directory at mysqltuner.pl line 1155 (#1)
    (W exec) A system(), exec(), or piped open call could not execute the
    named program for the indicated reason.  Typical reasons include: the
    permissions were wrong on the file, the file wasn't found in
    $ENV{PATH}, the executable in question was compiled for another
    architecture, or the #! line in a script points to an interpreter that
    can't be run for similar reasons.  (Or maybe your system doesn't support
    #! at all.)
    
[--] External IP           : 

```

It looks like need additional checks for have this utilites on server or not, imho.

**Comment by z0rc** [comment]
I'd really like so see IP/Network indicators disabled by default and enabled with additional parameter. Right now it's done in non-portable way, it introduces external dependencies and in general has nothing to do with MySQL server configuration.

**Comment by jmrenouard** [comment]
@z0rc @mrqwer88 @DutchProgrammer 

Thanks for all feedbacks.

I just add an option --sysstat for your personal needs.

Information about system is no more display by default.

**Comment by jmrenouard** [comment]
all main indicators are now available through --sysstat.
So I closed this issue.
I proposed to open new issue for all other issue regarding this part of mysqltuner.
