### ISSUE TITLE
"no password" warning for users which have unix_socket plugin set

### ISSUE THREAD

**Issue by cloos** [major/MySQLTuner-perl#166]
```
select Host, User, Password, authentication_string, plugin from mysql.user where Password = '';
+-----------+------+----------+-----------------------+-------------+
| Host      | User | Password | authentication_string | plugin      |
+-----------+------+----------+-----------------------+-------------+
| localhost | root |          |                       | unix_socket |
| 127.0.0.1 | root |          |                       | unix_socket |
| ::1       | root |          |                       | unix_socket |
+-----------+------+----------+-----------------------+-------------+
```

```
[!!] User 'root@127.0.0.1' has no password set.
[!!] User 'root@::1' has no password set.
[!!] User 'root@localhost' has no password set.
```

**Comment by jmrenouard** [comment]
Ok 

Adding where plugin <> 'unix_socket' should be ok ?

Thanks for your feedback.
@jmrenouard

**Comment by DutchProgrammer** [comment]
How much plugins are there where its possible to login without password ?

For example is there a win_socket ?

Maybe it's beter to add plugin NOT IN ('unix_'socket') so we can easy add more plugin that can login without password ?

for example if win_socket is a plugin it will be:
plugin NOT IN ('unix_'socket', 'win_socket')

**Comment by jmrenouard** [comment]
@DutchProgrammer @cloos 
Is it ok now ?
Br

**Comment by DutchProgrammer** [comment]
@jmrenouard sql looks good tested on my servers (they only dont got sockets connections) and there it's working like it should be.

**Comment by jmrenouard** [comment]
@DutchProgrammer  @cloos Thanks for your feedbacks !
