### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by jazzerman** [major/MySQLTuner-perl#171]
Missing . (dot) on line 964 after scalar(@opened_ports): 
Now: 
badprint "There is too many listening ports: ". scalar(@opened_ports) " opened > ".$opt{'maxportallowed'}. "allowed.";

Should be: 
badprint "There is too many listening ports: ". scalar(@opened_ports). " opened > ".$opt{'maxportallowed'}. "allowed.";

**Comment by jmrenouard** [comment]
Hi, 

Thank for your support :

All seems to be ok now !
https://travis-ci.org/major/MySQLTuner-perl

Best regards,
@jmrenouard
