### ISSUE TITLE
Syntax error Perl v5.20.3

### ISSUE THREAD

**Issue by kosfango** [major/MySQLTuner-perl#172]
Hi All,

I have installed FreeBSD 10.2 Perl v5.20.3.
Unfortunatly, mysqltunel.pl doesn't work:

perl mysqltuner.pl
String found where operator expected at mysqltuner.pl line 964, near ") "
        opened > "" (#1)
    (S syntax) The Perl lexer knows whether to expect a term or an operator.
    If it sees what it knows to be a term when it was expecting to see an
    operator, it gives you this warning.  Usually it indicates that an
    operator or delimiter was omitted, such as a semicolon.

        (Missing operator before " opened > "?) (#2)
    (S syntax) This is an educated guess made in conjunction with the message
    "%s found where operator expected".  Often the missing operator is a comma.

syntax error at mysqltuner.pl line 964, near ") " opened > ""
syntax error at mysqltuner.pl line 979, near "}"
syntax error at mysqltuner.pl line 1097, near "}"
syntax error at mysqltuner.pl line 1153, near "}"
Global symbol "$mysqlvermajor" requires explicit package name at mysqltuner.pl line 1159.
Global symbol "$mysqlverminor" requires explicit package name at mysqltuner.pl line 1159.
Global symbol "$mysqlvermicro" requires explicit package name at mysqltuner.pl line 1159.
Global symbol "$mysqlverminor" requires explicit package name at mysqltuner.pl line 1161.
Global symbol "$mysqlvermicro" requires explicit package name at mysqltuner.pl line 1162.
BEGIN not safe after errors--compilation aborted at mysqltuner.pl line 3195 (#3)
    (F) Probably means you had a syntax error.  Common reasons include:

        A keyword is misspelled.
        A semicolon is missing.
        A comma is missing.
        An opening or closing parenthesis is missing.
        An opening or closing brace is missing.
        A closing quote is missing.

    Often there will be another error message associated with the syntax
    error giving more information.  (Sometimes it helps to turn on -w.)
    The error message itself often tells you where it was in the line when
    it decided to give up.  Sometimes the actual error is several tokens
    before this, because Perl is good at understanding random input.
    Occasionally the line number may be misleading, and once in a blue moon
    the only way to figure out what's triggering the error is to call
    perl -c repeatedly, chopping away half the program each time to see
    if the error went away.  Sort of the cybernetic version of 20 questions.

Uncaught exception from user code:
        syntax error at mysqltuner.pl line 964, near ") " opened > ""
        syntax error at mysqltuner.pl line 979, near "}"
        syntax error at mysqltuner.pl line 1097, near "}"
        syntax error at mysqltuner.pl line 1153, near "}"
        Global symbol "$mysqlvermajor" requires explicit package name at mysqltuner.pl line 1159.
        Global symbol "$mysqlverminor" requires explicit package name at mysqltuner.pl line 1159.
        Global symbol "$mysqlvermicro" requires explicit package name at mysqltuner.pl line 1159.
        Global symbol "$mysqlverminor" requires explicit package name at mysqltuner.pl line 1161.
        Global symbol "$mysqlvermicro" requires explicit package name at mysqltuner.pl line 1162.
        BEGIN not safe after errors--compilation aborted at mysqltuner.pl line 3195.

**Comment by flamber** [comment]
Same bug as #171

**Comment by jmrenouard** [comment]
Hi, 

Thank for your support :

All seems to be ok now !
https://travis-ci.org/major/MySQLTuner-perl

Best regards,
@jmrenouard
