### ISSUE TITLE
BEGIN not safe after errors--compilation aborted 

### ISSUE THREAD

**Issue by Sweepr** [major/MySQLTuner-perl#173]
I've just download the latest mysqltuner but upon running i get this error:

`perl mysqltuner.pl
String found where operator expected at mysqltuner.pl line 964, near ") "
        opened > "" (#1)
    (S syntax) The Perl lexer knows whether to expect a term or an operator.
    If it sees what it knows to be a term when it was expecting to see an
    operator, it gives you this warning.  Usually it indicates that an
    operator or delimiter was omitted, such as a semicolon.

        (Missing operator before " opened > "?)
"my" variable $mysqlverminor masks earlier declaration in same scope at
        mysqltuner.pl line 1161 (#2)
    (W misc) A "my", "our" or "state" variable has been redeclared in the current
    scope or statement, effectively eliminating all access to the previous
    instance.  This is almost always a typographical error.  Note that the
    earlier variable will still exist until the end of the scope or until
    all closure referents to it are destroyed.

"my" variable $mysqlvermicro masks earlier declaration in same scope at
        mysqltuner.pl line 1162 (#2)

syntax error at mysqltuner.pl line 964, near ") " opened > ""
syntax error at mysqltuner.pl line 979, near "}"
syntax error at mysqltuner.pl line 1097, near "}"
syntax error at mysqltuner.pl line 1153, near "}"
BEGIN not safe after errors--compilation aborted at mysqltuner.pl line 3195 (#3)
    (F) Probably means you had a syntax error.  Common reasons include:

        A keyword is misspelled.
        A semicolon is missing.
        A comma is missing.
        An opening or closing parenthesis is missing.
        An opening or closing brace is missing.
        A closing quote is missing.

    Often there will be another error message associated with the syntax
    error giving more information.  (Sometimes it helps to turn on -w.)
    The error message itself often tells you where it was in the line when
    it decided to give up.  Sometimes the actual error is several tokens
    before this, because Perl is good at understanding random input.
    Occasionally the line number may be misleading, and once in a blue moon
    the only way to figure out what's triggering the error is to call
    perl -c repeatedly, chopping away half the program each time to see
    if the error went away.  Sort of the cybernetic version of S<20
    questions>.

BEGIN not safe after errors--compilation aborted at /usr/share/perl5/Carp/Heavy.pm line 11.
Compilation failed in require at /usr/share/perl5/Carp.pm line 33.
`

**Comment by Sweepr** [comment]
perl -version

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

Copyright 1987-2009, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by DutchProgrammer** [comment]
This is fixed in the new release v1.6.9

**Comment by jmrenouard** [comment]
Hi,

Thank for your support :

All seems to be ok now !
https://travis-ci.org/major/MySQLTuner-perl

Best regards,
@jmrenouard
