### ISSUE TITLE
 InnoDB Write Log efficiency negative values

### ISSUE THREAD

**Issue by toomuchio** [major/MySQLTuner-perl#182]
Not exactly sure how, but I'm getting negative values on InnoDB Write Log efficiency
e.g. [!!] InnoDB Write Log efficiency: -99.85% (-43324 hits/ 43389 total)
Perhaps the percentage needs to be abs'd before it's checked.

A good reference for if the write log value is ok is if Innodb_log_waits is 0 which mine is so I think my configuration is correct.

Somebody else seems to have had the issue as well https://dba.stackexchange.com/questions/132361/negative-innodb-write-log-efficiency-in-mysqltuner-pl-results

**Comment by jmrenouard** [comment]
@toomuchio Can you give us your feedback ?

**Comment by toomuchio** [comment]
Resolved

-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[OK] InnoDB buffer pool / data size: 2.0G/2.0G
[OK] InnoDB buffer pool instances: 2
[OK] InnoDB Used buffer: 99.37% (130241 used/ 131072 total)
[OK] InnoDB Read buffer efficiency: 100.00% (1611562377 hits/ 1611574358 total)
[!!] InnoDB Write Log efficiency: 18.84% (966406 hits/ 5128744 total)
[OK] InnoDB log waits: 0.00% (0 waits / 4162338 writes)

**Comment by jmrenouard** [comment]
Perfect,

I close this issue.
