### ISSUE TITLE
script generates uninitialized variables

### ISSUE THREAD

**Issue by vchepkov** [major/MySQLTuner-perl#183]
`>> MySQLTuner 1.6.9 - Major Hayden <major@mhtx.net>`

```
Use of uninitialized value $infoPFSMemory[0] in substitution (s///) at
	/usr/bin/mysqltuner line 2927 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.
    
    To help you figure out what was undefined, perl will try to tell you the
    name of the variable (if any) that was undefined. In some cases it cannot
    do this, so it also tells you what operation you used the undefined value
    in.  Note, however, that perl optimizes your program and the operation
    displayed in the warning may not necessarily appear literally in your
    program.  For example, "that $foo" is usually optimized into "that "
    . $foo, and the warning will refer to the concatenation (.) operator,
    even though there is no . in your program.
    
Use of uninitialized value in addition (+) at /usr/bin/mysqltuner line 1925 (#1)
...

Use of uninitialized value in addition (+) at /usr/bin/mysqltuner line 1932 (#1)
...
Use of uninitialized value $num in numeric ge (>=) at /usr/bin/mysqltuner line
	262 (#1)
Use of uninitialized value $num in numeric ge (>=) at /usr/bin/mysqltuner line
	265 (#1)
Use of uninitialized value $num in numeric ge (>=) at /usr/bin/mysqltuner line
	268 (#1)
Use of uninitialized value $num in concatenation (.) or string at
	/usr/bin/mysqltuner line 272 (#1)
...
Use of uninitialized value $num in numeric ge (>=) at /usr/bin/mysqltuner line
	245 (#1)
Use of uninitialized value $num in numeric ge (>=) at /usr/bin/mysqltuner line
	248 (#1)
Use of uninitialized value $num in numeric ge (>=) at /usr/bin/mysqltuner line
	251 (#1)
Use of uninitialized value $num in concatenation (.) or string at
	/usr/bin/mysqltuner line 255 (#1)

```

**Comment by vchepkov** [comment]
Server version: 5.1.73

**Comment by jmrenouard** [comment]
No sure but next errors: should be fixed in the next commit.
Use of uninitialized value $infoPFSMemory[0] in substitution (s///) at
    /usr/bin/mysqltuner line 2927 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

    To help you figure out what was undefined, perl will try to tell you the
    name of the variable (if any) that was undefined. In some cases it cannot
    do this, so it also tells you what operation you used the undefined value
    in.  Note, however, that perl optimizes your program and the operation
    displayed in the warning may not necessarily appear literally in your
    program.  For example, "that $foo" is usually optimized into "that "
    . $foo, and the warning will refer to the concatenation (.) operator,
    even though there is no . in your program.

**Comment by jmrenouard** [comment]
Last version should fix this ....

**Comment by vchepkov** [comment]
Yes, it did, thank you. Could you bump version number, please?

**Comment by vchepkov** [comment]
By the way, rpm complains about this string:

```
%changelog
* Thu Jan 5 2015 Jean-Marie RENOUARD <jmrenouard@gmail.com> %VERSION%-1
```

That's because Jan 5 2015 was Monday :)

**Comment by jmrenouard** [comment]
@vchepkov can you give us your feedback ?

**Comment by vchepkov** [comment]
I thought I did, sorry if I wasn't clear in my comment above
Yes, fix worked perfectly, thank you.
