### ISSUE TITLE
Example on mysqltuner.com doesn't download vulnerabilities database

### ISSUE THREAD

**Issue by php-coder** [major/MySQLTuner-perl#186]
Example on http://mysqltuner.com is missing the command for downloading vulnerabilities database. On the same time example on the main page on GitHub has it:
```console
wget http://mysqltuner.pl/ -O mysqltuner.pl
wget https://raw.githubusercontent.com/major/MySQLTuner-perl/master/basic_passwords.txt -O basic_passwords.txt
wget https://raw.githubusercontent.com/major/MySQLTuner-perl/master/vulnerabilities.csv -O vulnerabilities.csv
perl mysqltuner.pl
```
I suggest to update the example on the site.

**Comment by jmrenouard** [comment]
Hi@php-coder,
You can pull request mysqltuner on gh-pages branch of this project containaing Web page.

**Comment by jmrenouard** [comment]
Page updated
