### ISSUE TITLE
possible wrong suggestion in newer versions: [!!] Query cache should be disabled by default due to mutex contention.

### ISSUE THREAD

**Issue by DEV-Kapler** [major/MySQLTuner-perl#190]
Hi!

at first I want to thank you for the including MariaDB Galera Metrics!

But there is a little glitch. According to
[MariaDB KB about query-cache](https://mariadb.com/kb/en/mariadb/query-cache/#limitations)

> The query cache also needs to be disabled for MariaDB Galera cluster versions prior to "5.5.40-galera", "10.0.14-galera" and "10.1.2".

the message:
[!!] Query cache should be disabled by default due to mutex contention.

is NOT correct for newer(newest) Versions of MariaDB. This is a major benefit of the new version and has a big impact for performance.

Kind regards

Edgar

**Comment by jmrenouard** [comment]
Hi @DEV-Kapler 

Thanks for your feedback :)

Can you propose a pull request fixing this issue ?
If have_galera => query cache should be disabled for Galera Cluster
If version is ge 10.1 then query cache should be enabled.

Is it ok for you ?

**Comment by DEV-Kapler** [comment]
Hallo @jmrenouard 

i've never wrote something in pearl, but it is a good opportunity to start. I will try it the next two weeks. If I fail I'll let you know till 6th of april.

You will hear from me again :)

**Comment by jmrenouard** [comment]
@DEV-Kapler 
A journey of a thousand miles begins with a single step.

**Comment by jmrenouard** [comment]
Hi @DEV-Kapler 

Can you give your feedback ?

**Comment by jkavalik** [comment]
MariaDB does not say that query cache "should" be enabled for the new galera versions, just that it "may" be. Afaik the "mutex contention" is a general problem with the current QC implementation which makes it not scalable to multiprocessor machines as current servers usually are.

**Comment by jmrenouard** [comment]
Hi @jkavalik @DEV-Kapler 

Is there anybody that can propose a clean rule for this query cache status ?

In fact, some rules can be better to tell us what is the right use case for QC.

Thanks by advance,

**Comment by acs-ferreira** [comment]
Using MariaDB 10.2 or 10.4 here, the warning still there in the latest version.

**Comment by grooverdan** [comment]
fixed in #525

**Comment by mowny** [comment]
> fixed in #525

not really
1.8.1:
...
[!!] Query cache may be disabled by default due to mutex contention.
[OK] Query cache efficiency: 33.8% (1B cached / 5B selects)
[!!] Query cache prunes per day: 9464183
...
Variables to adjust:
    **query_cache_size (=0)**
    query_cache_type (=0)
    **query_cache_size (> 32M)**

Those variable settings are mutually exclusive.

About the query cache itself: Magento2 profits a lot from it _if_ it is behind varnish and also using redis, because the brunt of the traffic that would lead to contention is offloaded to these two, so the query cache can speed up magento's repetitive queries.

**Comment by grooverdan** [comment]
> Those variable settings are mutually exclusive.

Fair point.

Can you come up with a heuristic of selects vs updates/insert/replace/delete that would exemplify the Magento2 behind varnish (and probably other considerably read-only workloads)? Is there a heuristic of non-trivial selects that can be made (probably in the `hander_read*` in combination with `com_select` numbers that could also be considered an critieria for query cache enabling.

There's a recommended max of 128M for the query_cache_size currently. Is there a way to recommend more based on read/write queries and low-memory-prunes?

**Comment by jmrenouard** [comment]
Hi,

I most of all cases QC is a contention point and a pain point for scalability

I close this issue MySQL remove this part of code since MySQL 8.0

Feel free to PR best idea if needed

Best regards,
Jean-Marie
