### ISSUE TITLE
Authentication Bug with Passwords that have $ in them

### ISSUE THREAD

**Issue by daved314** [major/MySQLTuner-perl#195]
On line 699 of the current code release you have:

`$mysqllogin = "-u $opt{user} -p\"$opt{pass}\"" . $remotestring;`

This causes issues when a password has a $ in the string.  It can be fixed easily by utilizing single quotes

`$mysqllogin = "-u $opt{user} -p'$opt{pass}'" . $remotestring;`

**Comment by jmrenouard** [comment]
@daved314  Is it ok for you ?

**Comment by daved314** [comment]
all working!
