### ISSUE TITLE
qps reported as 0 on very active server - MariaDB 5.5

### ISSUE THREAD

**Issue by jkavalik** [major/MySQLTuner-perl#197]
MysqlTuner output snippets:

`Up for: 133d 1h 57m 23s (2 q [0.000 qps], 117M conn, TX: 207B, RX: 137B)`

MariaDB `\s` output parts:

`Server version:		5.5.33a-MariaDB-log MariaDB Server, wsrep_23.7.6.rXXXX`
`Uptime:			133 days 1 hour 53 min 1 sec`
`Threads: 122  Questions: 56765835915  Slow queries: 1856  Opens: 2096  Flush tables: 2  Open tables: 1296  Queries per second avg: 4937.026`

**Comment by jmrenouard** [comment]
Hi @jkavalik 

Thanks for this update :)

**Comment by jkavalik** [comment]
Hi @jmrenouard 
I forgot to add version, sorry: `MySQLTuner 1.6.10`
If you need some global status values to check, let me know.

**Comment by jmrenouard** [comment]
you should have 4937 qps

**Comment by jkavalik** [comment]
I believe I should, but instead the tuner output shows `2 q [0.000 qps]`, where I suppose the real numbers should be. Is it maybe some overflow because of the `Questions: 56765835915` part? I do not know perl so cannot tell.

**Comment by jkavalik** [comment]
I noticed that the same version is telling me there are 100% reads on the server which is wrong, there are lot of writes too.

**Comment by jkavalik** [comment]
Tried the tagged version 1.6.0 and it gives reasonable values (a different server this time, but with the same symptoms in current master version - 1.6.10):
`5B q [499.809 qps]`
`Reads / Writes: 93% / 7%`

**Comment by jkavalik** [comment]
Tried to locate the breaking commit:
this one shows reasonable numbers - https://github.com/major/MySQLTuner-perl/commit/eea101019e3db09d331b19957bb033097973c084#diff-2cc6ed630854d08fdcfd8c17c70d25ef

this one shows 0 qps and 0% writes - https://github.com/major/MySQLTuner-perl/commit/0ffe9507b660e35d76fbe86be5539f4dfb822523#diff-2cc6ed630854d08fdcfd8c17c70d25ef

here are the differences in output between these two versions - https://www.diffchecker.com/ol8qjzuw

**Comment by jkavalik** [comment]
Hi @jmrenouard
Looking at the output of --debug I see that the session status values are fetched after global status and probably rewrite them:

https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L959
