### ISSUE TITLE
Querying for "plugin" column in mysql.user while it doesn't exist in MySQL <= 5.1

### ISSUE THREAD

**Issue by kwaio** [major/MySQLTuner-perl#199]
Hi,

I hit this error : 
```
-------- Security Recommendations ------------------------------------------------------------------
...
[!!] failed to execute: SELECT CONCAT(user, '@', host) FROM mysql.user WHERE (password = '' OR password IS NULL) AND plugin NOT IN ('unix_socket', 'win_socket')
[!!] FAIL Execute SQL / return code: 256
```

the column "plugin" was introduced in MySQL-5.5
Can this query be changed for MySQL < 5.5 so it ignores the column "plugin" ?

**Comment by jmrenouard** [comment]
I think we just skip this tests for <= 5.1 version.

This version is deprecated and maybe full of unknown CVE. So test password is maybe not relevant.

What do you think about that ?

**Comment by jmrenouard** [comment]
Adding this message for <=5.1 version
No more password checks for MySQL version <=5.1
MySQL version <=5.1 are deprecated and end of support.

**Comment by jmrenouard** [comment]
this meesage have been added in my last commit.

**Comment by jmrenouard** [comment]
hi @kwaio 

Can you give us your feedback ?

**Comment by kwaio** [comment]
Sorry I moved on to other projects. Will update next time I run the script.

**Comment by jmrenouard** [comment]
@kwaio 

I closed this issue.

Feel free to reopen this ticket if needed.

**Comment by lnedry** [comment]
I'm also seeing this error and I am using MySQL 5.5.48.
