### ISSUE TITLE
Password with special characters

### ISSUE THREAD

**Issue by artasom** [major/MySQLTuner-perl#203]
Hello.

When I try to use the script, I get this error:

[!!] Attempted to use login credentials, but they were invalid.
 
My root password has a few characters that are not letters or numbers . If I change my password removing this "special" characters, I can use the script with no problem.

Best regards.

**Comment by jmrenouard** [comment]
Hi @artasom 

Do you use the last version ?

I have change way to handle password.

Is it a regression ?

Thanks for your help

**Comment by artasom** [comment]
Hi @jmrenouard 

Yes, I had downloaded the script the same day I posted the issue. So it is the version of a couple of days ago.

Best regards.

**Comment by jmrenouard** [comment]
Hi @artasom 

Can you try using backslashes(\) behind each special caracters, please ?

**Comment by artasom** [comment]
Hi @jmrenouard 

It didn't work :(

**Comment by jmrenouard** [comment]
what kind of special car. you are using ?

Can you give us some example(without leaving us your true password) ?

**Comment by artasom** [comment]
I am using part of the characters shown below (no space character between the characters and numbers and the special ones)
[charactersandnumbers] !!)%=$ [charactersandnumbers]
But I also tried a password consisting in 
[charactersandnumbers] $ [charactersandnumbers]
and it did not work.
I also tried your suggestion of the backslash behind
[charactersandnumbers] $\ [charactersandnumbers]
and it did not work also.

**Comment by jmrenouard** [comment]
Hi @artasom 
Can you try \$ using backslash before ?

Thanks.

**Comment by jmrenouard** [comment]
Hi @artasom 

My test is:
mysql>GRANT ALL PRIVILEGES on *.* TO 'toto'@'localhost' identified by '$#%1234AbC!';

root:vm1:MySQLTuner-perl/  |master ✓|$ perl mysqltuner.pl --user toto --pass $#%1234AbC!
 >>  MySQLTuner 1.6.11 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
[!!] Attempted to use login credentials, but they were invalid
root:vm1:MySQLTuner-perl/  |master ✓|$ perl mysqltuner.pl --user toto --pass '$#%1234AbC!'
 >>  MySQLTuner 1.6.11 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
[OK] Logged in using credentials passed on the command line

[--] Skipped version check for MySQLTuner script
[OK] Currently running supported MySQL version 5.7.12
[OK] Operating on 64-bit architecture

-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +ARCHIVE +BLACKHOLE +CSV -FEDERATED +InnoDB +MEMORY +MRG_MYISAM +MyISAM +PERFORMANCE_SCHEMA
[--] Data in InnoDB tables: 16K (Tables: 1)
[OK] Total fragmented tables: 0
....

**Comment by jmrenouard** [comment]
In conclusion, special characters work perfectly when using simple quotes for --pass option.
without simple quote, authentification failed.

You can also used .my.cnf file to avoid this problem. (described in main page)

**Comment by artasom** [comment]
Sorry for have not being able to reply earlier.
I have tried the following, to no avail:

mysql>ALTER USER 'root'@'localhost' IDENTIFIED BY 'ABC%abc1';

perl mysqltuner.pl --user root --password 'ABC%abc1'
 >>  MySQLTuner 1.6.11 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
[!!] Attempted to use login credentials, but they were invalid

perl mysqltuner.pl --user root --password ABC%abc1
 >>  MySQLTuner 1.6.11 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
[!!] Attempted to use login credentials, but they were invalid

What can I be doing wrong?

**Comment by artasom** [comment]
Just in case, mysql Server version: 5.7.12-log Homebrew

**Comment by 0xbsec** [comment]
@artasom, please try to execute `perl mysqltuner.pl --user root --pass 'ABC%abc1'` ( notice: **--pass** instead of **--password** ).

**Comment by artasom** [comment]
H @0xbsec. Thanks, finally I managed to be able to use the password with 'special' characters. My mistake for ussing --password and not --pass in the parameters...

**Comment by 0xbsec** [comment]
@artasom: Welcome. **--password** is an invalid option for mysqltuner.
@jmrenouard: Maybe there should be a warning message or something when mysqltuner is executed with an unkown option ?

**Comment by imic07** [comment]
hi, when i use the latest version 1.7.2, my password like this mysql_ADX..x , it can't work well, the error is [!!] Attempted to use login credentials, but they were invalid. 
even i use this cmd :   shell> ./mysqltuner.pl --user root -pass 'mysql_ADX..x'
still error :Attempted to use login credentials, but they were invalid
then i created a simple user and pass like this         testall/testall
it didn't work , why?itest this new simple user and pass, it is right on sqlyog;
shell> ./mysqltuner.pl --user testall --pass testall
the err is Attempted to use login credentials, but they were invalid
can somebody help me ?
