### ISSUE TITLE
Updater creates a corrupted file

### ISSUE THREAD

**Issue by Maks3w** [major/MySQLTuner-perl#204]
```bash
perl mysqltuner.pl --updateversion
 >>  MySQLTuner 1.6.10 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
[OK] Logged in using credentials from debian maintenance account.
[!!] There is a new version of MySQLTuner available (1.6.11)
[OK] Successfully updated MySQLTuner script
```

File contents (Only the begin)

```perl
HTTP/1.1 200 OK^M
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'^M
X-XSS-Protection: 1; mode=block^M
X-Frame-Options: deny^M
X-Content-Type-Options: nosniff^M
Strict-Transport-Security: max-age=31536000^M
ETag: "e56d6f8027f5cf1ec13784b63cfc175662e4917a"^M
Content-Type: text/plain; charset=utf-8^M
Cache-Control: max-age=300^M
X-GitHub-Request-Id: B91F1328:6093:107C3F76:5728CCEA^M
Content-Length: 147151^M
Accept-Ranges: bytes^M
Date: Tue, 03 May 2016 16:08:11 GMT^M
Via: 1.1 varnish^M
Connection: keep-alive^M
X-Served-By: cache-lhr6337-LHR^M
X-Cache: HIT^M
X-Cache-Hits: 1^M
Vary: Authorization,Accept-Encoding^M
Access-Control-Allow-Origin: *^M
X-Fastly-Request-ID: cf275070e744758b0206e1f15630185c06ae4acb^M
Expires: Tue, 03 May 2016 16:13:11 GMT^M
Source-Age: 0^M
^M
#!/usr/bin/env perl
# mysqltuner.pl - Version 1.6.11
```

Platform: Ubuntu 16.00 

> ii  libalgorithm-diff-perl             1.19.03-1                       all          module to find differences between files
ii  libalgorithm-diff-xs-perl          0.04-4build1                    amd64        module to find differences between files (XS accelerated)
ii  libalgorithm-merge-perl            0.08-3                          all          Perl module for three-way merge of textual data
ii  libapparmor-perl                   2.10.95-0ubuntu2                amd64        AppArmor library Perl bindings
ii  libarchive-zip-perl                1.56-2                          all          Perl module for manipulation of ZIP archives
ii  libauthen-sasl-perl                2.1600-1                        all          Authen::SASL - SASL Authentication framework
ii  libcgi-fast-perl                   1:2.10-1                        all          CGI subclass for work with FCGI
ii  libcgi-pm-perl                     4.26-1                          all          module for Common Gateway Interface applications
ii  libdbd-mysql-perl                  4.033-1build2                   amd64        Perl5 database interface to the MySQL database
ii  libdbi-perl                        1.634-1build1                   amd64        Perl Database Interface (DBI)
ii  libdpkg-perl                       1.18.4ubuntu1                   all          Dpkg perl modules
ii  libencode-locale-perl              1.05-1                          all          utility to determine the locale encoding
ii  libexporter-tiny-perl              0.042-1                         all          tiny exporter similar to Sub::Exporter
ii  libfcgi-perl                       0.77-1build1                    amd64        helper module for FastCGI
ii  libfile-fcntllock-perl             0.22-3                          amd64        Perl module for file locking with fcntl(2)
ii  libfile-listing-perl               6.04-1                          all          module to parse directory listings
ii  libfile-stripnondeterminism-perl   0.015-1                         all          Perl module for stripping non-determinism from files
ii  libfont-afm-perl                   1.20-1                          all          Font::AFM - Interface to Adobe Font Metrics files
ii  libhtml-form-perl                  6.03-1                          all          module that represents an HTML form element
ii  libhtml-format-perl                2.11-2                          all          module for transforming HTML into various formats
ii  libhtml-parser-perl                3.72-1                          amd64        collection of modules that parse HTML text documents
ii  libhtml-tagset-perl                3.20-2                          all          Data tables pertaining to HTML
ii  libhtml-template-perl              2.95-2                          all          module for using HTML templates with Perl
ii  libhtml-tree-perl                  5.03-2                          all          Perl module to represent and create HTML syntax trees
ii  libhttp-cookies-perl               6.01-1                          all          HTTP cookie jars
ii  libhttp-daemon-perl                6.01-1                          all          simple http server class
ii  libhttp-date-perl                  6.02-1                          all          module of date conversion routines
ii  libhttp-message-perl               6.11-1                          all          perl interface to HTTP style messages
ii  libhttp-negotiate-perl             6.00-2                          all          implementation of content negotiation
ii  libio-html-perl                    1.001-1                         all          open an HTML file with automatic charset detection
ii  libio-socket-inet6-perl            2.72-2                          all          object interface for AF_INET6 domain sockets
ii  libio-socket-ssl-perl              2.024-1                         all          Perl module implementing object oriented interface to SSL sockets
ii  liblist-moreutils-perl             0.413-1build1                   amd64        Perl module with additional list functions not found in List::Util
ii  liblocale-gettext-perl             1.07-1build1                    amd64        module using libc functions for internationalization in Perl
ii  liblwp-mediatypes-perl             6.02-1                          all          module to guess media type for a file or a URL
ii  liblwp-protocol-https-perl         6.06-2                          all          HTTPS driver for LWP::UserAgent
ii  libmail-sendmail-perl              0.79.16-1                       all          Send email from a perl script
ii  libmailtools-perl                  2.13-1                          all          Manipulate email in perl programs
ii  libnet-http-perl                   6.09-1                          all          module providing low-level HTTP connection client
ii  libnet-smtp-ssl-perl               1.03-1                          all          Perl module providing SSL support to Net::SMTP
ii  libnet-snmp-perl                   6.0.1-2                         all          Script SNMP connections
ii  libnet-ssleay-perl                 1.72-1build1                    amd64        Perl module for Secure Sockets Layer (SSL)
ii  libperl5.22:amd64                  5.22.1-9                        amd64        shared Perl library
ii  libsocket6-perl                    0.25-1build2                    amd64        Perl extensions for IPv6
ii  libsys-hostname-long-perl          1.5-1                           all          Figure out the long (fully-qualified) hostname
ii  libterm-readkey-perl               2.33-1build1                    amd64        perl module for simple terminal control
ii  libtext-charwidth-perl             0.04-7build5                    amd64        get display widths of characters on the terminal
ii  libtext-iconv-perl                 1.7-5build4                     amd64        converts between character sets in Perl
ii  libtext-wrapi18n-perl              0.06-7.1                        all          internationalized substitute of Text::Wrap
ii  libtimedate-perl                   2.3000-2                        all          collection of modules to manipulate date/time information
ii  liburi-perl                        1.71-1                          all          module to manipulate and access URI strings
ii  libwww-perl                        6.15-1                          all          simple and consistent interface to the world-wide web
ii  libwww-robotrules-perl             6.01-1                          all          database of robots.txt-derived permissions
ii  perl                               5.22.1-9                        amd64        Larry Wall's Practical Extraction and Report Language
ii  perl-base                          5.22.1-9                        amd64        minimal Perl system
rc  perl-modules                       5.18.2-2ubuntu1.1               all          Core Perl modules
ii  perl-modules-5.22                  5.22.1-9                        all          Core Perl modules

**Comment by jmrenouard** [comment]
Hi @Maks3w 
Bug reproduced.

Thanks for your feedback

**Comment by jmrenouard** [comment]
Hi @Maks3w

I have fixed it.

Can you give us your feedback ?

**Comment by Maks3w** [comment]
Hard to say until a most recent version exists :)

**Comment by jmrenouard** [comment]
I have increment version number :)

**Comment by jmrenouard** [comment]
@Maks3w Can you give us your feedback ?

**Comment by Maks3w** [comment]
It works now.

PD: When possible please tag the releases so new versions appear in relelase tab
