### ISSUE TITLE
--updateversion needs valid mysql credentials to run

### ISSUE THREAD

**Issue by jkavalik** [major/MySQLTuner-perl#211]
Imho when `--updateversion` is specified, the script should just update itself, not run anything else. But it instead fails before the version check and download if valid credentials are not supplied.

**Comment by jmrenouard** [comment]
Ok 
Nice idea :) 
Do you have a implementation code in mind ?

Thanks for your feedback !

**Comment by 0xbsec** [comment]
@jkavalik Please check if this issue is fixed.

**Comment by jmrenouard** [comment]
@jkavalik  @0xbsec 
Tests based on comment in related commit is ok for me.

Feel free to reopen this ticket if needed.

**Comment by jkavalik** [comment]
@0xbsec @jmrenouard  works great, thank you!
