### ISSUE TITLE
Request: make script work without root privileges 

### ISSUE THREAD

**Issue by francesco1119** [major/MySQLTuner-perl#212]
Hello, will it be possible to have th script work without root privileges?
Thank  you

**Comment by jmrenouard** [comment]
GRANT SELECT, PROCESS,EXECUTE, REPLICATION CLIENT,SHOW DATABASES,SHOW VIEW ON *.* FOR 'user@'localhost' identified by pwd1234;

**Comment by jmrenouard** [comment]
I changed FAQ for that !
