### ISSUE TITLE
json output, output nothings

### ISSUE THREAD

**Issue by Poil** [major/MySQLTuner-perl#213]
Hi,

With the tarball from master, (pretty)json output nothings (script exit code = 1)

Summary of my perl5 revision 5 version 20 subversion 2

*Edit* : missing module on my server but badprint print nothings

Best regards

**Comment by jmrenouard** [comment]
Hi @Poil,

Do you install JSON module ?

**Comment by Poil** [comment]
Hey,

Yes, it's now working, but when you don't have it, the "badprint" function don't output the warning

Best regards,

**Comment by jmrenouard** [comment]
It's strange because code says:
 eval "{ use JSON }";
        if ($@) {
            badprint "JSON Module is needed.";
            exit 1;
        }

so, if this module is not installed, badprint "JSON Module is needed." should be printed.

**Comment by Poil** [comment]
Yep, if I change "badprint" to "print", I have "JSON Module is needed."

**Comment by jmrenouard** [comment]
@Poil 
Changes have been done .
Is it better ?
