### ISSUE TITLE
Understand read out

### ISSUE THREAD

**Issue by freelancerteam** [major/MySQLTuner-perl#219]
I googled for a while but I didst find what a result like this mean:
Variables to adjust:
    join_buffer_size (> 128.0K, or always use indexes with joins)
    tmp_table_size (> 128M)
    max_heap_table_size (> 128M)
    innodb_buffer_pool_size (>= 871M) if possible.
    innodb_buffer_pool_instances (=1)

Specific the  (>  in front of a number and  if possible.

Thanks

**Comment by jmrenouard** [comment]
This variables should be set in your my.cnf configuration file.
This is the main configuration files for MySQL like server.

All this parameters(or variables) should be located under [mysqld] configuration block.

In general, this file is located in /etc/my.cnf or /etc/mycnf.d/*.conf

**Comment by freelancerteam** [comment]
I do understand all this, Thats not my question.
Specific the >. Thats it mean it should be greater then the number showing and if so how much great?

**Comment by 0xbsec** [comment]
@freelancerteam  Yes, it means it should be greater than the number showing. How much, depend on your situation.

**Comment by jmrenouard** [comment]
@freelancerteam @0xbsec 
It's a complex question indeed.
This question can have specific responses for each variable.

I don't know how to response clearly to this question.

Maybe, if someone wants to handle this stuff regarding all MySQL/MaraDB/Percona versions and related impacts, all contributors are welcomed.

Actually, we can't give a simple response to this question.

**Comment by jmrenouard** [comment]
Hi @freelancerteam , @0xbsec 

Can we closed this issue or do you want to work on it ?
I do know how to handle this issue.
We can maybe work on messages regarding each variable to adjust giving some sample value or valid intervals.

Thanks for your feedback
@jmrenouard
