### ISSUE TITLE
Interested in pull requests with code style refactoring?

### ISSUE THREAD

**Issue by wchristian** [major/MySQLTuner-perl#220]
Before i make the effort, i'd like to ask if the following is something you'd be interested in:

A lot of the code in there is overly verbose and violates DRY a lot, as well as breaks with many modern perl best practices. I'd be happy to do a few passes of tightening things up to make them more readable by reducing a lot of unnecessary code.

Would that be wasted effort, or something you'd like to merge in?

Example:

Before
```{perl}
sub hr_bytes {
    my $num = shift;
    if ( $num >= ( 1024**3 ) ) {    #GB
        return sprintf( "%.1f", ( $num / ( 1024**3 ) ) ) . "G";
    }
    elsif ( $num >= ( 1024**2 ) ) {    #MB
        return sprintf( "%.1f", ( $num / ( 1024**2 ) ) ) . "M";
    }
    elsif ( $num >= 1024 ) {           #KB
        return sprintf( "%.1f", ( $num / 1024 ) ) . "K";
    }
    else {
        return $num . "B";
    }
}
```
After
```{perl}
sub hr_bytes2 {
    my ( $num ) = @_;
    return sprintf "%.1fG", $num / 1024**3 if $num >= 1024**3;    #GB
    return sprintf "%.1fM", $num / 1024**2 if $num >= 1024**2;    #MB
    return sprintf "%.1fK", $num / 1024    if $num >= 1024;       #KB
    return $num . "B";
}
```

**Comment by jmrenouard** [comment]
Thanks@christian ok for me

**Comment by wchristian** [comment]
Alright, i've started some work in this branch: https://github.com/wchristian/MySQLTuner-perl/commits/style

It's quite work-in-progress, so i don't recommend merging right now, though i welcome comments and opinions if there are any.

Amusing observation: Due to the sheer amount of code, perltidy seems to be a little unstable.

**Comment by jmrenouard** [comment]
Ok perfect :)

Don't forget to add #220 in your commit message so that PR could be attached to this issue.

Thanks for your support @wchristian

**Comment by wchristian** [comment]
Well damn, it's picking up every force push i do as a new commit here. I hope that didn't generate any email spam.

In any case, began adding #220 to my commit messages.

I also completed a few commits that, after review and verification that things still seem to work, can be integrated into master.

With the first pieces of easy structural work done, the next few commits will be a whole bunch of deduplication of repeated messages. :)

**Comment by wchristian** [comment]
Getting into the meat of abbreviating checks by employing syntax like Test::Simple now, that last abbreviate commit is still experimental though.

**Comment by jmrenouard** [comment]
Hi @wchristian

First, thanks for your work and contribution !

There is a lot of modifications actually on your repository.
Can we stop developing and try to merge and validate it ?

Can you rebase your code with the actual version, please ?

I hope this patch won't introduced too much regressions and conflicts :)

Thanks for your feedback !

**Comment by jmrenouard** [comment]
@wchristian 

Can you submit a Pull Request for your code, please ?

@jmrenouard

**Comment by wchristian** [comment]
Yep, i'll do that over the weekend. I got sidetracked by another project. :)

**Comment by jmrenouard** [comment]
Hi @wchristian 

I will change some other thing in MySQL Tuner, I am waiting for your feedback regarding your refactoring.

Thanks by advance,
@jmrenouard

**Comment by jmrenouard** [comment]
Hi @wchristian 

We are waiting your PR :)

I will close this issue and it will be reopened if needed.
@jmrenouard
