### ISSUE TITLE
Script doesn't detect the mysql version properly, leading to erroneus password check.

### ISSUE THREAD

**Issue by surfrock66** [major/MySQLTuner-perl#223]
I am using mysql 5.7.12 on Ubuntu 16.04.  If I log into mysql and do SHOW VARIABLES the result I get is:
`mysql> SHOW VARIABLES like 'version';`
`+---------------+-----------------+`
`| Variable_name | Value           |`
`+---------------+-----------------+`
`| version       | 5.7.12-0ubuntu1 |`
`+---------------+-----------------+`
`1 row in set (0.00 sec)`

When I run mysql tuner, I get this error over and over:

`ERROR 1054 (42S22) at line 1: Unknown column 'password' in 'where clause'`

Upon investigating, the following check is failing:

https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L1403

I don't know perl well enough to propose a fix, but above is the exact string that version reports.

Thanks!

**Comment by surfrock66** [comment]
Suggested solution; again, I don't do perl so I don't want to propose something creating a syntactical error:

> You might want to mention that $str1 =~ "$str2" (not /$str2/) will check if $str2 is a substring of $str1.

Source: https://stackoverflow.com/questions/1175390/how-do-i-compare-two-strings-in-perl

**Comment by jmrenouard** [comment]
@surfrock66 
Can you give me you feedback please ?

**Comment by surfrock66** [comment]
That solved it, thanks!
