### ISSUE TITLE
wsrep_osu_method error

### ISSUE THREAD

**Issue by emphazer** [major/MySQLTuner-perl#224]
the line 
if ( trim( $myvar{'wsrep_OSU_method'} ) eq "TOI" ) { 
should be
if ( trim( $myvar{'wsrep_osu_method'} ) eq "TOI" ) {

it drops an error
you have to write it wsrep_osu_method

here the error

Use of uninitialized value $string in substitution (s///) at
	/root/mysqltuner.pl line 3146 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.
    
    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    anid the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.
    
Use of uninitialized value $string in substitution (s///) at
	/root/mysqltuner.pl line 3147 (#1)
Use of uninitialized value in string eq at /root/mysqltuner.pl line 3324 (#1)

**Comment by jmrenouard** [comment]
thanks @emphazer 

Can you tell me if 1.6.14 version is fixing your issue ?

**Comment by emphazer** [comment]
yesss! it does!
thx
