### ISSUE TITLE
Bug: false alert about missing PK of views

### ISSUE THREAD

**Issue by dmig** [major/MySQLTuner-perl#229]
Galera Metrics section shows list of alerts:
- Following table(s) don't have primary key
 - view1
 - view2
 - view3
 ...

Which are not correct, script should first check table type before reporting it.

**Comment by dmig** [comment]
Easy way:
`select TABLE_NAME from information_schema.tables where TABLE_TYPE='BASE TABLE'`
then iterate over TABLE_NAMEs

**Comment by dmig** [comment]
Here is a fix:
```sql
select CONCAT(c.table_schema,CONCAT('.', c.table_name))
from information_schema.columns c
join information_schema.tables t using (TABLE_SCHEMA, TABLE_NAME)
where c.table_schema not in ('mysql', 'information_schema', 'performance_schema')
  and t.table_type != 'VIEW'
group by c.table_schema,c.table_name
having sum(if(c.column_key in ('PRI','UNI'), 1,0)) = 0
```
Replace query on line https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L3245 with one above.

**Comment by jmrenouard** [comment]
Thanks @dmig 

Can you test last version ?

@jmrenouard

**Comment by dmig** [comment]
Perfect!

**Comment by evgkrsk** [comment]
I see same problem with mysqltune-1.7.4. How can I elaborate/fix it?
