### ISSUE TITLE
Bug: wrong advice about sunrpc.tcp_slot_table_entries

### ISSUE THREAD

**Issue by dmig** [major/MySQLTuner-perl#230]
On my systems (Ubuntu 16.04) mysqltuner tells, that
```
-------- System Linux Recommendations --------------------------------------------------------------
...
[!!] Initial TCP slot entries is < 1M, please consider having a value greater than 100
...
-------- Recommendations ---------------------------------------------------------------------------
General recommendations:
    setup Initial TCP slot entries greater than 100
...
Variables to adjust:
    sunrpc.tcp_slot_table_entries > 100 (echo 128 > /proc/sys/sunrpc/tcp_slot_table_entries)
...
```

That's incorrect, because `sunrpc.tcp_slot_table_entries` isn't applicable to this system.
To fix:
- see https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L1258
- wrap lines 1258-1268 into `if() {}` with check, if `/proc/sys/sunrpc` exists

**Comment by jmrenouard** [comment]
Thanks @dmig 

Can you check last version ?

@jmrenouard

**Comment by dmig** [comment]
Perfect!

**Comment by dmig** [comment]
Sorry, reopening with a bug:
line https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L1260 should look like this:
```
if ( -f "/proc/sys/sunrpc" and ($tcp_slot_entries eq '' or $tcp_slot_entries < 100) ) {
```
