### ISSUE TITLE
Escape Characters in Password

### ISSUE THREAD

**Issue by Ghan04** [major/MySQLTuner-perl#232]
It looks like my MySQL password is causing issues with the script - it is erroring out even though I am using the correct information, and throws a message about an unexpected EoF:

Please enter your MySQL administrative login: root
Please enter your MySQL administrative password: sh: -c: line 0: unexpected EOF while looking for matching ``'
sh: -c: line 1: syntax error: unexpected end of file
[!!] Attempted to use login credentials, but they were invalid.

My password here has a ` in it, which might be causing the issue. I haven't tried using a .cnf file to work around the issue yet, but I figured I'd report this in any case.

**Comment by jmrenouard** [comment]
Hi @Ghan04 

` charater is a speciel terminal chararter. 

Do you try to escape it ? 

Changing ` with \' may solve this issue.

@jmrenouard

**Comment by Ghan04** [comment]
Yep, escaping the character solved it, though I suppose it should probably do the escape in the script if possible? Catching the error and printing a message might be nice as well. Just some thoughts.

Thanks,
Ghan

**Comment by jmrenouard** [comment]
Hi @Ghan04 
Escaping caracter is due to shell specificities.

So I close this issue.
@jmrenouard
