### ISSUE TITLE
Use of uninitialized value in string eq at ./mysqltuner.pl line 2538 for some MySQL versions

### ISSUE THREAD

**Issue by pes-soft** [major/MySQLTuner-perl#237]
Hi,

skip_name_resolve is available in system variables since MySQL version 5.1.46 and 5.5.5. Running mysqltuner on earlier versions results in the warning message.

Instead maybe skip information could be displayed:
[--] Skipped name resolution test due to missing skip_name_resolve in system variables. ?More info?

Related MySQL bug reports:
Bug #37168 Missing variable - skip_name_resolve (https://bugs.mysql.com/bug.php?id=37168)
Bug #23606 --skip-name-resolve missing from SHOW VARIABLES (other skip options are shown)(https://bugs.mysql.com/bug.php?id=23606)

Tested on mysqltuner 1.6.15, MySQL 5.1.35.

**Comment by jmrenouard** [comment]
Hi @pes-soft 

Can you tell be if last version is in compliance with you needs ?

Tahanks for your support
@jmrenouard

**Comment by jmrenouard** [comment]
I close this issue feel free to reopen it if needed.
@jmrenouard

**Comment by pes-soft** [comment]
Hi @jmrenouard 

Works great. Thanks.

Btw:  "?More info?" can be removed from the info message.
