### ISSUE TITLE
InnoDB buffer pool alignment check appears backward

### ISSUE THREAD

**Issue by YearOfBenj** [major/MySQLTuner-perl#244]
I get an "innodb_buffer_pool_size is not aligned with value innodb_buffer_pool_chunk_size and innodb_buffer_pool_instances" error and "innodb_buffer_pool_size must always be equal to or a multiple of innodb_buffer_pool_chunk_size * innodb_buffer_pool_instances" recommendation even though they are perfectly aligned.  (256M pool size, 1 instance of 128M chunk size)

I believe the sense of the test simply needs to be reversed from
 
```if ( int($myvar{'innodb_buffer_pool_size'}) % ( int( $myvar{'innodb_buffer_pool_chunk_size'}) * int($myvar{'innodb_buffer_pool_in
stances'})) ne 0 ) {/*ALL GOOD*/} else {/*BAD NEWS*/}```

to

```if ( int($myvar{'innodb_buffer_pool_size'}) % ( int( $myvar{'innodb_buffer_pool_chunk_size'}) * int($myvar{'innodb_buffer_pool_in
stances'})) eq 0 ) {/*ALL GOOD*/} else {/*BAD NEWS*/}```

**Comment by jmrenouard** [comment]
Hi @YearOfBenj 

I change this issue.

Thanks for your deep look on this part.
@jmrenouard

**Comment by YearOfBenj** [comment]
My pleasure, thanks for the quick fix!

**Comment by jmrenouard** [comment]
I close this issue.

Feel free to reopen it if needed.

@jmrenouard
