### ISSUE TITLE
Error Unknown column 'plugin' in 'where clause' on CentOS 6 (MySQL 5.1.73)

### ISSUE THREAD

**Issue by rwky** [major/MySQLTuner-perl#245]
CentOS 6 has MySQL 5.1.73 when mysqltuner checks for passwordless accounts it fails due to the error  Unknown column 'plugin' in 'where clause'.

If I get a chance I'll submit a PR to fix this. If anyone else wants a go feel free to tackle it before me.

**Comment by jmrenouard** [comment]
Thnaks @rwky
