### ISSUE TITLE
Add option for using a "defaults-file" for credentials

### ISSUE THREAD

**Issue by simplerezo** [major/MySQLTuner-perl#247]
Currently only debian "default" configuration is allowed:
--defaults-file=/etc/mysql/debian.cnf

Would be nice to specify another custom file with an command line option "--defaults-file="...

**Comment by jmrenouard** [comment]
Hi @simplerezo 

check last version with --defaults-file.

BR,
@jmrenouard

**Comment by simplerezo** [comment]
Hi @jmrenouard 

It works for me!

Thank you!
