### ISSUE TITLE
Double quotes on password prompt breaks the script

### ISSUE THREAD

**Issue by blopper** [major/MySQLTuner-perl#251]
If you have double quotes ( " ) in your root mysql password mysqltuner will exit with an error unable to match " This is a shell error, see output bellow

`# ./mysqltuner.pl 

> >  MySQLTuner 1.7.0 - Major Hayden major@mhtx.net
> >  Bug reports, feature requests, and downloads at http://mysqltuner.com/
> >  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
Please enter your MySQL administrative login: root
Please enter your MySQL administrative password: sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
[!!] Attempted to use login credentials, but they were invalid.
[root@D2189 major-MySQLTuner-perl-3c53f7b]# `

**Comment by jmrenouard** [comment]
Hi @blopper 

Main issue regarding support double quotes password is that Unixoid Os interpolated systematically $ character as a environment variables.

So this is not an issue we can solve easily.

We will have other issue telling us that double quote password with $ doesn't work.

So I will need help if someone have a better idea regarding this issue.

Thanks for your feedback.

@jmrenouard

**Comment by blopper** [comment]
`$(printf '%q' $user_raw_passwd_input)` perhaps would do?

**Comment by jmrenouard** [comment]
$ mysqltuner.pl --user tuner --pass $(printf '%q' $user_raw_passwd_input)

I think it can works perfectly, no ?

**Comment by jmrenouard** [comment]
There is a previous issue regarding special character in password.
Password with special characters #203

**Comment by jmrenouard** [comment]
I close this item.

Feel free to reopen it if you want something to be done or patch mysqltuner.
