### ISSUE TITLE
Aditionnal recommendation (InnoDB log file size)

### ISSUE THREAD

**Issue by acs-ferreira** [major/MySQLTuner-perl#258]
Not really an issue, but a "notice", trying making things more consistent.

Here is my phpMyAdmin Advisor advice that is not present on MySQLTuner:

```
:: The InnoDB log file size is not an appropriate size, in relation to the InnoDB buffer pool.

Especially on a system with a lot of writes to InnoDB tables you should set innodb_log_file_size to 25% of innodb_buffer_pool_size. However the bigger this value, the longer the recovery time will be when database crashes, so this value should not be set much higher than 256 MiB. Please note however that you cannot simply change the value of this variable. You need to shutdown the server, remove the InnoDB log files, set the new value in my.cnf, start the server, then check the error logs if everything went fine. See also this blog entry
```

MySQLTuner Output:

```
General recommendations:
    Adjust your join queries to always utilize indexes
    Temporary table size is already large - reduce result set size
    Reduce your SELECT DISTINCT queries without LIMIT clauses
    Increase table_open_cache gradually to avoid file descriptor limits
    Read this before increasing table_open_cache over 64: http://bit.ly/1mi7c4C
    Beware that open_files_limit (5000) variable
    should be greater than table_open_cache ( 64)
Variables to adjust:
    join_buffer_size (> 256.0K, or always use indexes with joins)
    table_open_cache (> 64)
```

Maybe include this on this script ?

**Comment by jmrenouard** [comment]
Hi @acs-ferreira 

Thanks for this updates.

Is there any low and high limits for this size ?

I have read interesting article on Percona blog on this aspect 

https://www.percona.com/blog/2008/11/21/how-to-calculate-a-good-innodb-log-file-size/
https://www.percona.com/blog/2016/05/31/what-is-a-big-innodb_log_file_size/

I think this is not a so evident setting to used innodb buffer pool size / 4.

Thanks for your help and your subjection.

**Comment by jmrenouard** [comment]
Hi @acs-ferreira

This test have be added.

Can you give me you feedback ?
@jmrenouard

**Comment by acs-ferreira** [comment]
Seems OK to me.
Maybe wait some more feedback before close this?

**Comment by SnAFKe** [comment]
I'm not sure if i need to add or reduce 25% but in both case i have this

Ratio InnoDB log file size / InnoDb Buffer pool size (100 %): 64.0M/64.0M should be equal 25%

Case 1

innodb_buffer_pool_size = 64M
innodb_log_file_size = 16M

Case 2

innodb_buffer_pool_size = 64M
innodb_log_file_size = 256M

Always return me

innodb_log_file_size should be equals to 1/4 of buffer pool size (= 16M) if possible.

**Comment by acs-ferreira** [comment]
MySQL 5.5: https://dev.mysql.com/doc/refman/5.5/en/innodb-data-log-reconfiguration.html

MySQL 5.6: https://dev.mysql.com/doc/refman/5.6/en/innodb-data-log-reconfiguration.html

MySQL 5.7: https://dev.mysql.com/doc/refman/5.7/en/innodb-data-log-reconfiguration.html

**Comment by SnAFKe** [comment]
I did notice until now there is another ini overwrite my configuration that is why always getting the same innodb_log_file_size.

Now i'm getting 

[OK] InnoDB log file size / InnoDb Buffer pool size: 64.0M/64.0M should be equal 25%

But not should be 16.0M/64.0M

**Comment by acs-ferreira** [comment]
Have you followed the procedure on my previous post?
It is not simply a case of changing `innodb_log_file_size` to the new size and restarting MySQL...

**Comment by SnAFKe** [comment]
Do you mean innodb_fast_shutdown? yes i did and always show that.

**Comment by acs-ferreira** [comment]
No, move old log files:

1. Set `innodb_fast_shutdown = 0` with `mysql -uroot -pYOURPASSWORD -e"SET GLOBAL innodb_fast_shutdown = 0"`
2. Stop MySQL `service mysql stop` 
3. Move old LOG files: `mv /var/lib/mysql/ib_logfile[01] /tmp`
4. Change the value of `innodb_log_file_size` on `my.cnf` file
5. Start MySQL `service mysql start`

**Comment by SnAFKe** [comment]
Yes i did that but with the option 1 not 0 and always return me

[OK] InnoDB log file size / InnoDb Buffer pool size: 64.0M/64.0M should be equal 25%

**Comment by jmrenouard** [comment]
Hi @SnAFKe 

can you run mysqltuner with --debug option  ?

Thanks
@jmrenouard

**Comment by SnAFKe** [comment]
[tunerdebug.txt](https://github.com/major/MySQLTuner-perl/files/562768/tunerdebug.txt)

**Comment by jmrenouard** [comment]
Hi @SnAFKe 

Very strange.
details and last code:
 'innodb_buffer_pool_size' : 41943040,
'innodb_log_file_size' : 10485760,
'innodb_log_size_pct' : 25,

goodprint "InnoDB log file size / InnoDB Buffer pool size: "
          . hr_bytes( $myvar{'innodb_log_file_size'} ) . "/"
          . hr_bytes( $myvar{'innodb_buffer_pool_size'} ) . " should be equal 25%";

best regards,
@jmrenouard

**Comment by jmrenouard** [comment]
Hi

Can you give me your feeedback, please ?

Thanks

**Comment by SnAFKe** [comment]
Sorry for late response.

Still the issue.

[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (50 %): 8.0M * 2/32.0M should be equal 25%

[tunerdebug.txt](https://github.com/major/MySQLTuner-perl/files/673659/tunerdebug.txt)

**Comment by acs-ferreira** [comment]
Same issue here.

On `my.cnf`

```
innodb_log_file_size = 78M
innodb_buffer_pool_size = 312M
```
so 25%. Verified by:

```
MariaDB [(none)]> show global variables like '%innodb_log_file_size%';
+----------------------+----------+
| Variable_name        | Value    |
+----------------------+----------+
| innodb_log_file_size | 81788928 |
+----------------------+----------+
1 row in set (0.00 sec)
```

But on MySQLTuner:

```
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (50 %): 78.0M * 2/312.0M should be equal 25%
innodb_log_file_size should be equals to 1/4 of buffer pool size (=78M) if possible.
```

**Comment by Stinkykiller** [comment]
I would like to report same issue:

my.cnf:
> innodb_buffer_pool_size = 384M
> innodb_log_file_size = 96M

MySQL:
> MariaDB [(none)]> show global variables like '%innodb_log_file_size%';
> +----------------------+-----------+
> | Variable_name        | Value     |
> +----------------------+-----------+
> | innodb_log_file_size | 100663296 |
> +----------------------+-----------+

MySQLtuner:
> [!!] Ratio InnoDB log file size / InnoDB Buffer pool size (50 %): 96.0M * 2/384.0M should be equal 25%
> ....
> innodb_log_file_size should be equals to 1/4 of buffer pool size (=96M) if possible.

**Comment by jmrenouard** [comment]
Hi,

Implemented calculation:
 innodb_log_file_size * innodb_log_files_in_group = 0,25 * innodb_buffer_pool_size.

innodb_log_file_size=48M
innodb_log_files_in_group=2
innodb_buffer_pool_size=128M

Last message:
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (75 %): 48.0M * 2/128.0M should be equal 25%
innodb_log_file_size * innodb_log_files_in_group should be equals to 1/4 of buffer pool size (=64M) if possible.

**Comment by jmrenouard** [comment]
Duplicated with #271

**Comment by jmrenouard** [comment]
HI @acs-ferreira @SnAFKe @Stinkykiller 

Can you give me your feeedback, please ?

Thanks

**Comment by acs-ferreira** [comment]
What kind of feedback do you need @jmrenouard ?
Our issue here is that it reports the 25%, event if the value is correct, see my last message https://github.com/major/MySQLTuner-perl/issues/258#issuecomment-271592889.

**Comment by jmrenouard** [comment]
IHMO This ia duplicated ticket with #322

**Comment by jmrenouard** [comment]
Hi @acs-ferreira 

Related to #258 (comment).

Calculus Formula is
innodb_bufferpool_size~=(innodb_log_files_in_group * innodb_log_file_size)/4

In your case, Calculus formula used is:
innodb_bufferpool_size~= innodb_log_file_size/4
specifically in your case: 78.0M * 2/312.0M 
innodb_bufferpool_size is 312
innodb_log_file_size= 78M
innodb_log_files_in_group=2

So, in your case, all log files are sizing to 50% of buffer pool and that's why MT is warning you.

**Comment by ivanbaldo** [comment]
This should be closed I think, it works as advertised :-p
