### ISSUE TITLE
can't get script working on windows 2012

### ISSUE THREAD

**Issue by Duwe01** [major/MySQLTuner-perl#264]
Hello,

I'm trying to use the script locally on a windows 2012 server, which has mysql 5.5.42 installed.
Initially i had a lot of problems with authentication, which turned out to be that the script couldn't find mysqladmin.exe and mysql.exe, but returned the "Attempted to use login credentials, but they were invalid error" 
On windows it needs the whole path to the executables, and it doesn't seem to work well with spaces in the directory names, just in case someone else has this problem aswell (took me quite a bit of googling and trial and error to figure it out)
This is why i'm using a network share to point it to the files on the same server now, i use the following command to start mysqltuner (i've changed the servernames and passwords obviously):

mysqltuner.pl --mysqladmin "\\myserver\mysql\mysqladmin.exe" --mysqlcmd "\\myserver\mysql\mysql.exe" --forcemem 8192 --forceswap 4096 --verbose --outputfile "d:\temp\output.txt"

This doesn't give me a login error, but it seems to be trying to run serveral linux commands which cause it to fail, and i don't know how to fix it, is there anyone who can help me with this?
[--] * Windows OS(Win2012) is not fully supported.

 >>  MySQLTuner 1.7.0 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
[--] Unable to check for the latest MySQLTuner version
Please enter your MySQL administrative login: root
Please enter your MySQL administrative password: mypassword
'uname' is not recognized as an internal or external command,
operable program or batch file.
[--] Assuming 8192 MB of physical memory
[--] Assuming 4096 MB of swap space
'ps' is not recognized as an internal or external command,
operable program or batch file.
'ps' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
[!!] failed to execute: SELECT VERSION()
[!!] FAIL Execute SQL / return code: 256
[!!] You probably doesn't get enough privileges for running MySQLTuner ...

**Comment by jmrenouard** [comment]
Hi @Duwe01 

We need help for this feature.

Best regards,
@jmrenouard

**Comment by jmrenouard** [comment]
No awnser, I close this issue.
Feel free to reopen if needed.

No port avalaible for Windows.
