### ISSUE TITLE
error in query block Performance schema: TOP 15 queries with temp table to disk

### ISSUE THREAD

**Issue by xeonvs** [major/MySQLTuner-perl#265]
copy paste bug in query :)
need change statements_with_sorting to statements_with_temp_tables 

there is complete patch
http://pastebin.com/FCkVv17p

**Comment by jmrenouard** [comment]
Hi @xeonvs 

Can you check last version ?

BR
@jmrenouard

**Comment by xeonvs** [comment]
>Can you check last version ?
no changes in query.
line 3985 need replace 
use sys;select db, query, disk_tmp_tables from statements_with_sorting ORDER BY disk_tmp_tables DESC LIMIT 15;

by

use sys;select db, query, disk_tmp_tables from statements_with_temp_tables ORDER BY disk_tmp_tables DESC LIMIT 15;

**Comment by jmrenouard** [comment]
I forget to commit yesterday ;)

**Comment by xeonvs** [comment]
no changes in last commits ;)

**Comment by jmrenouard** [comment]
Ok 
I have fix it for good right now :)

**Comment by xeonvs** [comment]
good!
I tested, all ok.
