### ISSUE TITLE
Memory analyse is wrong

### ISSUE THREAD

**Issue by karek314** [major/MySQLTuner-perl#270]
```
[!!] Maximum reached memory usage: 56.7G (90.10% of installed RAM)
[!!] Maximum possible memory usage: 68.1G (108.27% of installed RAM)
  *** MySQL's maximum memory usage is dangerously high ***
  *** Add RAM before increasing MySQL buffer variables ***
```
This message is obviously wrong, my system never reaches 90% of memory used with this settings. I have also made test and set innodb pool size "correct" regarding to mysqltuner. But then i was running on 50% free ram free, of course after innodb pool has been mostly filled.

**Comment by jmrenouard** [comment]
Hi @karek314 
Can you give us all details regarding your mysql configuration and RAM installed in your system ?

Thanks,

**Comment by karek314** [comment]
innodbpool is set to 48gb, ram installed is 64gb. Other settings are mostly default, there are some tweaks which does not affect memory usage and i wouldn't add "help wanted" sticker to this issue, i don't need help. Help is needed for memory estimation formula which is incorrect.

**Comment by jmrenouard** [comment]
Hi @karek314 

I am a nice guy ok :)

I am pleased to help you for free and I would like you to understand that we try to build the best advisor for MySQL / MariaDB / Percona as well.

You are free and it's not so far of your education as you thought to use polite and well formulated explanations that couldn't be sadly understood.

So, if I used label Help Wanted, it's only for calling your followers to help contributors to help us to find out why you face this issue and get the ability to improve MySQLtuner or help you to find out why you get this type of result.
 
To understand memory model just have a look at a simple online calculator for InnoDB:
http://mysqlcalculator.com/

You can have a quick comparaison between your results and calculator results.

You should have a too high max_connections settings:
[!!] Maximum possible memory usage: 68.1G (108.27% of installed RAM)

@jmrenouard

**Comment by karek314** [comment]
Thanks for reply, but i understand how each setting affect memory usage. I think that Mysqltuner estimations are slightly too high.
`[!!] Maximum possible memory usage: 68.1G (108.27% of installed RAM)` - as i understand this is result made of including max allowed concurrent connections this is calculated on the top of previous calculations which i believe are slightly higher, maybe for double safety for less experienced administrators - not sure, didn't go through code of mysqltuner.

`[!!] Maximum reached memory usage: 56.7G (90.10% of installed RAM)` - But this result is not true. I need to add that i have waited until my innodb pool filled completely, as database is used very intensively across all stored informations after a while entire innodb pool is filled as much as it can since in this case database is slightly bigger than innodb pool.

Maybe estimation is slightly bigger than actual result for the sake of stability when less experienced user use it. Anyway in that case i agree to disagree, imo in most cases result is slightly to high, it could have contain some more details which include or additional informations like what is actual result without safe factor addition or something similar.

**Comment by jmrenouard** [comment]
Hi @karek314 

This calculation is to avoid OOM kill.

Attacks is very simple to perform:
1° perform a lot of select to fill innodb buffer pull
2° create a lot fo connections.

So, if you like you can propose a better algorithm for memory calculation based on your experimented everyday works that can provide a general purpose and safety mode to be sure that nobody can kill a mysql server using simple select and simple connection loop.
