### ISSUE TITLE
Incorrect innodb log file size calculation

### ISSUE THREAD

**Issue by miao606** [major/MySQLTuner-perl#271]
Innodb log file size = $myvar{'innodb_log_file_size'} * $myvar{'innodb_log_files_in_group'}

**Comment by xPaw** [comment]
I seem to be hitting this issue on ccb435904c80d38c2d97a6f00030d0519486dd02.

```[OK] InnoDB buffer pool / data size: 32.0G/22.3G
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (50 %): 8.0G * 2/32.0G should be equal 25%

innodb_log_file_size should be equals to 1/4 of buffer pool size (=8G) if possible.```

MySQL is reporting 8 GiB for the log file and 32 GiB for the buffer pool.

**Comment by jmrenouard** [comment]
Hi @miao606 

Can you tell us if last version solves this issue ?

**Comment by obissick** [comment]
Based on InnoDB log file size * # log files / InnoDB Buffer pool size, Yes the calculations were correct.

**Comment by jmrenouard** [comment]
Hi @obissick 

Duplicated with #258

**Comment by jmrenouard** [comment]
I will close this ticket and the main discussion can be on #771 issue.

BR
