### ISSUE TITLE
Software doesn't escape SQL statements in basic_passwords.txt

### ISSUE THREAD

**Issue by jasonbrianhall** [major/MySQLTuner-perl#278]
Using the Linux dictionary file, I discovered that it errors out on single tick entries.    A tick should be escaped with a double ''

For example Bob'sBurgers should be Bob''sBurgers

It doesn't attempt to escape any character which would allow a SQL injection if somebody put something malicious in the password file.

**Comment by jmrenouard** [comment]
Hi @jasonbrianhall 
I don't know exactly how to handle this kind of "hack" on your server. 

It means that you running mysqltuner.pl with an untrusted password file list.
2 reasons obviously for that:
1° Untrusted password list source 
2° untrusted server for mysqltuner.pl execution.

In the two cases, I can do more actually for that.
Password list is a dumb list without special characters within.

**Comment by jasonbrianhall** [comment]
It's pretty simple.  There are certain well known characters that need
escaped in MySQL.  See this page.
http://stackoverflow.com/questions/1086918/what-characters-have-to-be-escaped-to-prevent-mysql-injections

When you have see one of these characters, simply escape it by running
through an escapeSQL() routine and then use the result for the SQL
query.

If you don't escape these characters, MySQL will return an error 256.

I'm running it against the standard dictionary file in Linux, which is trusted.

**Comment by jmrenouard** [comment]
hi @jasonbrianhall 

Done !
