### ISSUE TITLE
Doesn't work for remote server on AWS

### ISSUE THREAD

**Issue by stanicek** [major/MySQLTuner-perl#279]
It seems mysqltuner is trying to open logs on remote server. Could the analysis be done without these logs when we are operating with remote servers?

Can't open /rdsdbdata/log/error/mysql-error.log for read: No such file or
        directory at ./mysqltuner.pl line 1095 (#2)
    (S inplace) The implicit opening of a file through use of the <>
    filehandle, either implicitly under the -n or -p command-line
    switches, or explicitly, failed for the indicated reason.  Usually this
    is because you don't have read permission for a file which you named on
    the command line.

Uncaught exception from user code:
        Can't open /rdsdbdata/log/error/mysql-error.log for read: No such file or directory at ./mysqltuner.pl line 1095.
 at ./mysqltuner.pl line 1095
        main::get_file_contents('/rdsdbdata/log/error/mysql-error.log') called at ./mysqltuner.pl line 1128
        main::log_file_recommandations() called at ./mysqltuner.pl line 5872

Thanks

Pepa

**Comment by jmrenouard** [comment]
Hi @stanicek 

Test to check error log file is readable has been added.

**Comment by jmrenouard** [comment]
@stanicek

This issue is solved ?

**Comment by jmrenouard** [comment]
I closed this issue.

**Comment by stanicek** [comment]
Hi,

sorry for not to respond earlier. 

The fix works for me, it skips the log analysis. 

I got following output, seems ok:
-------- Log file Recommendations ------------------------------------------------------------------
[--] Log file: /rdsdbdata/log/error/mysql-error.log(0B)
[!!] Log file /rdsdbdata/log/error/mysql-error.log doesn't exist
[!!] Log file /rdsdbdata/log/error/mysql-error.log isn't readable.

Thanks.
