### ISSUE TITLE
on mysql 5.7.17, the tuner is not working anymore.

### ISSUE THREAD

**Issue by MBj1703** [major/MySQLTuner-perl#288]
on mysql 5.7.17, the tuner is not working anymore.
Got: Your MySQL version  is EOL software!  Upgrade soon!

**Comment by jmrenouard** [comment]
Hi @MBj1703 

I don't get the same message on mysql 5.7.17.

Can you tell me more on your version and OS you run mysql tuner ?

Thnaks by advance,

mroot:vm1:share/  |detached: ✓|$ mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.17 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 

root:vm1:MySQLTuner-perl/  |master ✓|$ perl mysqltuner.pl
 >>  MySQLTuner 1.7.0 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[OK] Currently running supported MySQL version 5.7.17

**Comment by jmrenouard** [comment]
hi @MBj1703 

Do you face the same issue ?
Can you send debug info with option --debug on mysqltuner ?
