### ISSUE TITLE
How to grant all necessary requirements?

### ISSUE THREAD

**Issue by loopsysdev** [major/MySQLTuner-perl#290]
According to the README this script needs "Unrestricted read access to the MySQL server", but this is not elaborated on. As a non-DBA, I don't know what this actually entails. For example, would `GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO foo@localhost;` be enough? At that point the script no longer complains at least. I don't want to give any write access to this script.

**Comment by jmrenouard** [comment]
HI,

The anwser in the README.md :
Question: What's minimum privileges needed by a specific mysqltuner user in database ?

    mysql>GRANT SELECT, PROCESS,EXECUTE, REPLICATION CLIENT,SHOW DATABASES,SHOW VIEW ON *.* FOR 'mysqltuner'@'localhost' identified by pwd1234;

Have a nice day.
