### ISSUE TITLE
Take into account chroot setting

### ISSUE THREAD

**Issue by anatoli26** [major/MySQLTuner-perl#292]
I'm getting:

`[!!] Log file /var/log/log.err doesn't exist`
`[!!] Log file /var/log/log.err isn't readable.`

But the file does exist, just under the chroot prefix (/srv/mysqld): /srv/mysqld/var/log/log.err

**Comment by jmrenouard** [comment]
Hi,

We take information into MySQL/MariaDB variables.
So if error_log contains /var/log/log.err, I can figure out how to detect chroot env.

We can add a variable to force value for error log. 

Thank for your feedback

**Comment by anatoli26** [comment]
@jmrenouard, thanks for the explanation. I believe it would be better to get the value from the config, it'd preserve the simplicity.

**Comment by jmrenouard** [comment]
Hi @anatoli26 

In this case, it can be the simpliest thing to do.
Actually, the only sure way to get the proper settings is asking mysql or mariadb himself asking loaded value.

I don't know how we can fix that issue !

I must admit we need help on this topic.

Best regards,

**Comment by anatoli26** [comment]
@jmrenouard, it appears you are right, it's quite difficult to discover automatically the config file loaded by mysqld. 

Here's a an article about different ways, though none is a definitive solution: https://www.psce.com/blog/2012/04/01/how-to-find-mysql-configuration-file/.

If it would be possible to get the config file somehow (with heuristics of the article or specifying it by an option, e.g.: `mysqltuner.pl /etc/my.cnf`, it would be possible to extract the chroot var with something like this:

`perl -lne 'print $1 if /^chroot\s*=\s*([\/A-z0-9\._-]*)/' < /etc/my.cnf`


Then, there are 2 additional options to get the chroot path:

``readlink -f /proc/`pidof mysqld`/root``

and

``cat /proc/`pidof mysqld`/environ | tr '\0' '\n' | grep Chr``

The main problem is that both commands require elevated privs. I'm not sure if the former command requires root or the privs of the running mysqld, but the later does require root. At the same time, to access mysqld files like logs, the script probably will need some privs anyway...

Then there is another problem: how to discover the PID if there are multiple instances running (the pidfile variable is also relative to chroot)?

After analyzing all this, I believe the most simple and straightforward option is to specify the path to the config as a parameter (`mysqltuner.pl /etc/my.cnf`) and then extract from there the chroot var. And if the config is not specified, then no special chroot processing.

**Comment by jmrenouard** [comment]
Hi @anatoli26 

We face an other difficulty: what about /etc/my.cnf.d configuration sub directory ?
It can be very difficult to explore ....

I don't see very simple solution for chroot service ...

**Comment by jmrenouard** [comment]
Hi,

Better use of selinux rules or container solutions.

I closed this issue.
