### ISSUE TITLE
MacPorts packaging

### ISSUE THREAD

**Issue by ctreleaven** [major/MySQLTuner-perl#293]
I contribute to the MacPorts project [1] and I'd like to make mysqltuner available through our packaging system.

The situation is complicated, however, by the fact that MacPorts makes it possible to run multiple MySQL/MariaDB/Percona databases simultaneously.  Through MacPorts, one can have two (or more) database servers running at the same time on the same machine.  This is accomplished by manipulating the installs so that each goes into non-conflicting destinations.  For example, the 'mysqladmin' binary for MariaDB 10.1 goes into '/opt/local/lib/mariadb-10.1/bin/mysqladmin'.  For MySQL 5.7 the equivalent binary does in '/opt/local/lib/mysql-5.7/bin/mysqladmin'.  Similar manipulations are done for the my.cnf, datadir, socket, etc.  (By default network is disabled with 'skip-networking' in each my.cnf.  A note reminds the user about the potential port conflict if they wish to enable networking.)

What is the simplest way to use mysqltuner in our environment?  Is there a configuration file where I can set defaults for:

--mysqlcmd <path>
--mysqladmin <path>
--socket <socket>
maybe optionallly:
--host <hostname>
--socket <socket>

Thanks for any assistance.

[1] https://www.macports.org

**Comment by jmrenouard** [comment]
By default, if you can connect for command line with
$ mysql 
command it will be the same with mysqltuner.pl

**Comment by jmrenouard** [comment]
Best way is to get a .my.cnf file configurated for passwordless access.

**Comment by ctreleaven** [comment]
But we need to be able to choose WHICH db-server to connect to!  

My thought is to have, for example, a mysqltuner-mysql57 script and a mysqltuner-mariadb10.2 script (etc).  The script would use the correct versions of the mysql program and the right socket for local access.  But then it gets more complicated if the user is connecting to a remote server.

**Comment by jmrenouard** [comment]
Why not packaging mysqltuner as is ?

In fact, mysqltuner works with mysql client so if you can connect directly with mysql it will work same with mysqltuner.

Best regards,

**Comment by jmrenouard** [comment]
Hi @ctreleaven 

Do you get some news about MAC packaging ?

Thanks by advance,

**Comment by ctreleaven** [comment]
@jmrenouard 

I put it aside.  I think I know how I can work around this situation but events have conspired so that I haven't done it.  And no one else has been asking for a port.

Feel free to close this ticket if you wish.

**Comment by jmrenouard** [comment]
Hi @ctreleaven 

I closed this issue.
