### ISSUE TITLE
Advice for performance schema given for wrong version?

### ISSUE THREAD

**Issue by lichesser** [major/MySQLTuner-perl#300]
The script gives the advice to install/activate the performance schema for a MySQL 5.5 server. AFAIK performance schema is only available for 5.6+ .

The code checks for `mysql_version_ge( 5, 5 )`  which probably should be `mysql_version_ge( 5, 6 )` .

The advice given in the else part also suggests performance schema is only for 5.6+
`"Performance shouldn't be activated for MySQL and MariaDB 5.5 and lower version"`

**Comment by jmrenouard** [comment]
Hi @lichesser 

Thanks for your feedback. 
You are completely right.

BR.
