### ISSUE TITLE
Unknown option: pfstat

### ISSUE THREAD

**Issue by davidak** [major/MySQLTuner-perl#301]
I executed

`mysqltuner --buffers --dbstat --idxstat --sysstat --pfstat`

like described in the Readme and got

`Unknown option: pfstat`

Maybe the Readme needs to get updated.

---

MySQLTuner 1.6.18
NixOS 16.09.1698.2da8a5d (Flounder)

**Comment by jmrenouard** [comment]
Options --pfstat for MySQL tuner 1.7.0.

Documentation is related to last version.

I closed this issue because it works on the last version.

For information related to your current version, run
perldoc mysqltuner
