### ISSUE TITLE
Bad if query_cache_type=1, bad if query_cache_type=0

### ISSUE THREAD

**Issue by josenobile** [major/MySQLTuner-perl#302]
Hello, 

Check this: https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L2790-L2819

If query_cache_type = 0
badprint "Query cache is disabled";
else
 badprint  "Query cache may be disabled by default due to mutex contention.";
        push( @adjvars, "query_cache_type (=0)" );

What is the recommendation?

Using 10.1.18-MariaDB-cll-lve

**Comment by acs-ferreira** [comment]
For:
````
If query_cache_type = 0
badprint "Query cache is disabled";
````
Simply indicates it is disabled.

For:
````
badprint "Query cache may be disabled by default due to mutex contention.";
````
Read:
https://dev.mysql.com/doc/refman/5.7/en/query-cache-configuration.html

> If query_cache_size is 0, you should also set query_cache_type variable to 0. In this case, the server does not acquire the query cache mutex at all, which means that the query cache cannot be enabled at runtime and there is reduced overhead in query execution.

**Comment by josenobile** [comment]
Hello, 

Why use badprint to say it is disabled? instead of a info message?

**Comment by jmrenouard** [comment]
Hello,

Can you provide us debug result (option --debug) ?

Thanks by advance,

**Comment by yannik995** [comment]
I have got this issue, too.
10.1.21-MariaDB
If Query Cache is enabled: 
[!!] Query cache may be disabled by default due to mutex contention.
If Query Cache ist disabled:
[!!] Query cache is disabled 

```
-------- Performance Metrics -----------------------------------------------------------------------
[--] Up for: 3m 40s (4K q [19.255 qps], 727 conn, TX: 36M, RX: 829K)
[--] Reads / Writes: 68% / 32%
[--] Binary logging is disabled
[--] Physical Memory     : 15.7G
[--] Max MySQL memory    : 4.6G
[--] Other process memory: 154.3M
[--] Total buffers: 4.2G global + 5.7M per thread (80 max threads)
[--] P_S Max memory usage: 0B
[DG] $VAR1 = [];

[--] Galera GCache Max memory usage: 0B
[DG] $VAR1 = [];

[DG] $VAR1 = [];

[OK] Maximum reached memory usage: 4.3G (27.20% of installed RAM)
[OK] Maximum possible memory usage: 4.6G (29.67% of installed RAM)
[OK] Overall possible memory usage with other process is compatible with memory available
[OK] Slow queries: 0% (1/4K)
[OK] Highest usage of available connections: 12% (10/80)
[OK] Aborted connections: 0.00%  (0/727)
[!!] Query cache is disabled
[OK] Sorts requiring temporary tables: 0% (0 temp sorts / 352 sorts)
[OK] No joins without indexes
[OK] Temporary tables created on disk: 1% (3 on disk / 299 total)
[OK] Thread cache hit rate: 98% (10 created / 727 connections)
[OK] Table cache hit rate: 99% (944 open / 950 opened)
[OK] Open file limit used: 0% (60/65K)
[OK] Table locks acquired immediately: 100% (3K immediate / 3K locks)
```

**Comment by josenobile** [comment]
Hello, 

Why you need debug if the error is visible in the source code?

Anyway, the debug related to grep cache and cache ON/OFF

[DG] V: aria_pagecache_age_threshold = 300
[DG] V: aria_pagecache_buffer_size = 134217728
[DG] V: aria_pagecache_division_limit = 100
[DG] V: aria_pagecache_file_hash_size = 512
[DG] V: binlog_cache_size = 32768
[DG] V: binlog_stmt_cache_size = 32768
[DG] V: have_query_cache = YES
[DG] V: host_cache_size = 368
[DG] V: innodb_disable_sort_file_cache = OFF
[DG] V: innodb_ft_cache_size = 8000000
[DG] V: innodb_ft_result_cache_limit = 2000000000
[DG] V: innodb_ft_total_cache_size = 640000000
[DG] V: join_cache_level = 2
[DG] V: key_cache_age_threshold = 300
[DG] V: key_cache_block_size = 1024
[DG] V: key_cache_division_limit = 100
[DG] V: key_cache_file_hash_size = 512
[DG] V: key_cache_segments = 0
[DG] V: log_slow_filter = admin,filesort,filesort_on_disk,full_join,full_scan,query_cache,query_cache_miss,tmp_table,tmp_table_on_disk
[DG] V: max_binlog_cache_size = 18446744073709547520
[DG] V: max_binlog_stmt_cache_size = 18446744073709547520
[DG] V: metadata_locks_cache_size = 1024
[DG] V: optimizer_switch = index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=off,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=off
[DG] V: query_cache_limit = 0
[DG] V: query_cache_min_res_unit = 4096
[DG] V: query_cache_size = 0
[DG] V: query_cache_strip_comments = OFF
[DG] V: query_cache_type = OFF
[DG] V: query_cache_wlock_invalidate = OFF
[DG] V: stored_program_cache = 256
[DG] V: table_definition_cache = 30000
[DG] V: table_open_cache = 30000
[DG] V: thread_cache_size = 12
[DG] V: aria_pagecache_age_threshold = 300
[DG] V: aria_pagecache_buffer_size = 134217728
[DG] V: aria_pagecache_division_limit = 100
[DG] V: aria_pagecache_file_hash_size = 512
[DG] V: binlog_cache_size = 32768
[DG] V: binlog_stmt_cache_size = 32768
[DG] V: have_query_cache = YES
[DG] V: host_cache_size = 368
[DG] V: innodb_disable_sort_file_cache = OFF
[DG] V: innodb_ft_cache_size = 8000000
[DG] V: innodb_ft_result_cache_limit = 2000000000
[DG] V: innodb_ft_total_cache_size = 640000000
[DG] V: join_cache_level = 2
[DG] V: key_cache_age_threshold = 300
[DG] V: key_cache_block_size = 1024
[DG] V: key_cache_division_limit = 100
[DG] V: key_cache_file_hash_size = 512
[DG] V: key_cache_segments = 0
[DG] V: log_slow_filter = admin,filesort,filesort_on_disk,full_join,full_scan,query_cache,query_cache_miss,tmp_table,tmp_table_on_disk
[DG] V: max_binlog_cache_size = 18446744073709547520
[DG] V: max_binlog_stmt_cache_size = 18446744073709547520
[DG] V: metadata_locks_cache_size = 1024
[DG] V: optimizer_switch = index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=off,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=off
[DG] V: query_cache_limit = 0
[DG] V: query_cache_min_res_unit = 4096
[DG] V: query_cache_size = 0
[DG] V: query_cache_strip_comments = OFF
[DG] V: query_cache_type = OFF
[DG] V: query_cache_wlock_invalidate = OFF
[DG] V: stored_program_cache = 256
[DG] V: table_definition_cache = 30000
[DG] V: table_open_cache = 30000
[DG] V: thread_cache_size = 12
[DG] V: Aria_pagecache_blocks_not_flushed = 0
[DG] V: Aria_pagecache_blocks_unused = 15706
[DG] V: Aria_pagecache_blocks_used = 1731
[DG] V: Aria_pagecache_read_requests = 8930510
[DG] V: Aria_pagecache_reads = 73945
[DG] V: Aria_pagecache_write_requests = 1781122
[DG] V: Aria_pagecache_writes = 72648
[DG] V: Binlog_cache_disk_use = 0
[DG] V: Binlog_cache_use = 0
[DG] V: Binlog_stmt_cache_disk_use = 0
[DG] V: Binlog_stmt_cache_use = 0
[DG] V: Com_assign_to_keycache = 0
[DG] V: Innodb_encryption_rotation_pages_read_from_cache = 0
[DG] V: Qcache_free_blocks = 0
[DG] V: Qcache_free_memory = 0
[DG] V: Qcache_hits = 0
[DG] V: Qcache_inserts = 0
[DG] V: Qcache_lowmem_prunes = 0
[DG] V: Qcache_not_cached = 0
[DG] V: Qcache_queries_in_cache = 0
[DG] V: Qcache_total_blocks = 0
[DG] V: Ssl_callback_cache_hits = 0
[DG] V: Ssl_session_cache_hits = 0
[DG] V: Ssl_session_cache_misses = 0
[DG] V: Ssl_session_cache_mode = NONE
[DG] V: Ssl_session_cache_overflows = 0
[DG] V: Ssl_session_cache_size = 0
[DG] V: Ssl_session_cache_timeouts = 0
[DG] V: Ssl_used_session_cache_entries = 0
[DG] V: Subquery_cache_hit = 450
[DG] V: Subquery_cache_miss = 178486
[DG] V: Threads_cached = 10
[DG] V: Aria_pagecache_blocks_not_flushed = 0
[DG] V: Aria_pagecache_blocks_unused = 15706
[DG] V: Aria_pagecache_blocks_used = 1731
[DG] V: Aria_pagecache_read_requests = 8930510
[DG] V: Aria_pagecache_reads = 73945
[DG] V: Aria_pagecache_write_requests = 1781122
[DG] V: Aria_pagecache_writes = 72648
[DG] V: Binlog_cache_disk_use = 0
[DG] V: Binlog_cache_use = 0
[DG] V: Binlog_stmt_cache_disk_use = 0
[DG] V: Binlog_stmt_cache_use = 0
[DG] V: Com_assign_to_keycache = 0
[DG] V: Innodb_encryption_rotation_pages_read_from_cache = 0
[DG] V: Qcache_free_blocks = 0
[DG] V: Qcache_free_memory = 0
[DG] V: Qcache_hits = 0
[DG] V: Qcache_inserts = 0
[DG] V: Qcache_lowmem_prunes = 0
[DG] V: Qcache_not_cached = 0
[DG] V: Qcache_queries_in_cache = 0
[DG] V: Qcache_total_blocks = 0
[DG] V: Ssl_callback_cache_hits = 0
[DG] V: Ssl_session_cache_hits = 0
[DG] V: Ssl_session_cache_misses = 0
[DG] V: Ssl_session_cache_mode = NONE
[DG] V: Ssl_session_cache_overflows = 0
[DG] V: Ssl_session_cache_size = 0
[DG] V: Ssl_session_cache_timeouts = 0
[DG] V: Ssl_used_session_cache_entries = 0
[DG] V: Subquery_cache_hit = 450
[DG] V: Subquery_cache_miss = 178486
[DG] V: Threads_cached = 10
[!!] Query cache is disabled
query_cache_size (>= 8M)
                        'Aria_pagecache_writes' : '72648',
                        'Aria_pagecache_blocks_used' : '1731',
                        'Aria_pagecache_blocks_unused' : '15706',
                        'Binlog_stmt_cache_use' : '0',
                        'Innodb_encryption_rotation_pages_read_from_cache' : '0',
                        'Binlog_cache_use' : '0',
                        'Ssl_session_cache_timeouts' : '0',
                        'Aria_pagecache_blocks_not_flushed' : '0',
                        'Ssl_used_session_cache_entries' : '0',
                        'Ssl_session_cache_size' : '0',
                        'Ssl_callback_cache_hits' : '0',
                        'Ssl_session_cache_mode' : 'NONE',
                        'Binlog_cache_disk_use' : '0',
                        'Subquery_cache_hit' : '450',
                        'Qcache_queries_in_cache' : '0',
                        'Binlog_stmt_cache_disk_use' : '0',
                        'Subquery_cache_miss' : '178486',
                        'Qcache_free_blocks' : '0',
                        'Aria_pagecache_write_requests' : '1781122',
                        'Qcache_not_cached' : '0',
                        'Com_assign_to_keycache' : '0',
                        'Qcache_inserts' : '0',
                        'Ssl_session_cache_hits' : '0',
                        'Qcache_hits' : 0,
                        'Ssl_session_cache_misses' : '0',
                        'Ssl_session_cache_overflows' : '0',
                        'Aria_pagecache_read_requests' : 8930510,
                        'Aria_pagecache_reads' : 73945,
                        'Qcache_total_blocks' : '0',
                        'Qcache_lowmem_prunes' : 0,
                        'Threads_cached' : '10',
                        'Qcache_free_memory' : '0',
                              'table_cache_hit_rate' : 38,
                              'thread_cache_hit_rate' : 99,
                              'query_cache_prunes_per_day' : 0,
                              'query_cache_efficiency' : '0.0',
                           'aria_pagecache_buffer_size' : 134217728,
                           'query_cache_strip_comments' : 'OFF',
                           'join_cache_level' : '2',
                           'innodb_ft_cache_size' : '8000000',
                           'query_cache_min_res_unit' : '4096',
                           'key_cache_age_threshold' : '300',
                           'host_cache_size' : '368',
                           'innodb_ft_total_cache_size' : '640000000',
                           'key_cache_division_limit' : '100',
                           'query_cache_wlock_invalidate' : 'OFF',
                           'stored_program_cache' : '256',
                           'max_binlog_cache_size' : '18446744073709547520',
                           'table_open_cache' : '30000',
                           'innodb_ft_result_cache_limit' : '2000000000',
                           'innodb_disable_sort_file_cache' : 'OFF',
                           'query_cache_size' : 0,
                           'thread_cache_size' : '12',
                           'table_definition_cache' : '30000',
                           'aria_pagecache_age_threshold' : '300',
                           'key_cache_block_size' : 1024,
                           'key_cache_segments' : '0',
                           'key_cache_file_hash_size' : '512',
                           'query_cache_limit' : '0',
                           'have_query_cache' : 'YES',
                           'aria_pagecache_division_limit' : '100',
                           'binlog_stmt_cache_size' : '32768',
                           'binlog_cache_size' : '32768',
                           'log_slow_filter' : 'admin,filesort,filesort_on_disk,full_join,full_scan,query_cache,query_cache_miss,tmp_table,tmp_table_on_disk',
                           'optimizer_switch' : 'index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=off,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=off',
                           'aria_pagecache_file_hash_size' : '512',
                           'query_cache_type' : 'OFF',
                           'max_binlog_stmt_cache_size' : '18446744073709547520',
                           'metadata_locks_cache_size' : '1024',
                                  'query_cache_size (>= 8M)',

**Comment by jmrenouard** [comment]
Can you give us feedback ?

**Comment by jmrenouard** [comment]
Hi @josenobile Hi @acs-ferreira 

Can we close this issue, I not longer experiment this issue.

Thanks for your feedback.
