### ISSUE TITLE
bad calculation for pct_wkeys_from_mem

### ISSUE THREAD

**Issue by josenobile** [major/MySQLTuner-perl#303]
Hello, 

[!!] Write Key buffer hit rate: 0.0% (7 cached / 7 writes)

It should be 100%, not?

**Comment by jmrenouard** [comment]
Hi @josenobile 

Yes :)

**Comment by jmrenouard** [comment]
Hi @josenobile 

Can you give you feedback on last committed version ?

**Comment by josenobile** [comment]
Hello, 

I tested the last version (1.7.1), the bug about cache still. This bug (#303) I couldn't test because at the moment I don't have 100% Write buffer hit rate.

**Comment by jmrenouard** [comment]
Hi I close this issue.
