### ISSUE TITLE
Add quotes

### ISSUE THREAD

**Issue by knutov** [major/MySQLTuner-perl#311]
I ran mysqltuner and got recommendations
```
OPTIMIZE TABLE b1533-UkcF.b_sec_session; -- can free 4448 MB
```

But this is not correct mysql command, so may be it's better to generate this with correct quotes like
```
OPTIMIZE TABLE `b1533-UkcF`.b_sec_session; -- can free 4448 MB
```

As I remember there was other cases with lack of quotes/backticks somewhere.

**Comment by knutov** [comment]
Also, it will be useful to have some options to output only this type of recomendations, so they will be able to executed via cron, something like

```
mysqltuner.pl --only-optimize-table | mysql
```

**Comment by jmrenouard** [comment]
Hi @knutov 
innodb-defragment=1 is also a good alternative :)

I have add quotes for you as first intention.

**Comment by knutov** [comment]
I checked the source and it's definitely wrong.
```
OPTIMIZE TABLE `$table_name`;
```
will generate 

```
OPTIMIZE TABLE `b1533-UkcF.b_sec_session`;
```

which will leads to errors like no selected database + table does not exists.

Right format seems to be 

```
OPTIMIZE TABLE `$DB`.`$TABLE`;
```

Not sure how to better fix it, may be regexp to add quotas to $table_name?

**Comment by jmrenouard** [comment]
No anwser, I close this issue.
Modification have been made in the code and works perfectly for me.

Feel free to reopen it if needed.

**Comment by knutov** [comment]
@jmrenouard Sorry, I missed notifications from github.

I tested latest version minute ago and everything works. Thanks!
