### ISSUE TITLE
Use https instead of http

### ISSUE THREAD

**Issue by Goury** [major/MySQLTuner-perl#317]
Because of obvious reasons

**Comment by jmrenouard** [comment]
thanks for your feedback 
I change timeout and that all because https call is only performed for retrieving last version.

commit in few minutes.

**Comment by pes-soft** [comment]
Freshly cloned mysqltuner, executed: `./mysqltuner.pl --checkversion`, returned `[OK] You have the latest version of MySQLTuner(1.7.2)`

Btw, there are 2 URLs in doc/comments section which point to http://github.com/major/MySQLTuner-perl. So for full change to HTTPS which would include doc, these could be updated too.

**Comment by foxycode** [comment]
Not sure if this is right place. Is it about site `https://mysqltuner.pl/`? Because that one still isn't working. I can help configure Let's Encrypt if you want.

**Comment by jmrenouard** [comment]
This issue is fixed: MySQL tuner 1.7.17+ is using following URLs in https.

https://raw.githubusercontent.com/major/MySQLTuner-perl/master/mysqltuner.pl
