### ISSUE TITLE
Schedule for releases on github

### ISSUE THREAD

**Issue by dasrecht** [major/MySQLTuner-perl#320]
Hi there

First of all, many thanks for the ongoing work on the MySQL tuner. It's a perfect tool to get an overview over the metrics and find issues.

As a lot of people might provision their systems via configuration management tools so are we. And this brings me directly to the point.

I wanted to ask if there's a plan of creating releases again when a merge to master is done, this way people can pin versions instead of always pulling the master version.

The last release has been done in August 2016 https://github.com/major/MySQLTuner-perl/releases so it might be time for a new one :)

/bastian

**Comment by jmrenouard** [comment]
Hi @dasrecht 

Thanks for your support message :)

It can be be very nice if we can provide a new release for mysqltuner.

I would like to be sure all is ok !

I will do it in less than a week.

**Comment by jmrenouard** [comment]
Done
