### ISSUE TITLE
mysqltuner.pl doesn't shows Performance Metrics part in the output.

### ISSUE THREAD

**Issue by tehseenkn** [major/MySQLTuner-perl#323]
I am new in MySql Tunning performer. I am using  cygwin to execute mysqltuner.pl script it's running but doesn't show Performance Metrics in the out put. 

I have putted mysqltuner.pl in cygwin directory /usr/local/bin 
change the mode by command chmod +x mysqltuner.pl
after that i run it with command ./mysqltuner.pl  --user xyz --pass xyz --host 127.0.0.1
it working but Performance Metrics doesn't shows in the output screen and also shows 
failed to execute \`!] failed to execute: SHOW TABLE STATUS FROM \`db
[!!] FAIL Execute SQL / return code: 256

any solution?

**Comment by jmrenouard** [comment]
Hi @tehseenkn 

What is your MySQL server version ?

**Comment by tehseenkn** [comment]
MySql Server 5.6.14 is running in my system.

**Comment by jmrenouard** [comment]
Ok

In order to get it works perfectly on MySQL 5.6

git clone https://github.com/mysql/mysql-sys.git
cd mysql-sys
mysql < sys_56.sql

Then  rerun mysqltuner.pl --verbose

**Comment by tehseenkn** [comment]
thanks its working for me. Now mysqltuner.pl is showing performance metrics.

**Comment by jmrenouard** [comment]
Hi @tehseenkn 

I close this issue.
