### ISSUE TITLE
variables not uninitialized

### ISSUE THREAD

**Issue by mia0x75** [major/MySQLTuner-perl#325]
[OK] Node and whole cluster at the same level: 
Use of uninitialized value $mystat{"wsrep_local_state_comment"} in string eq at
	./tuner.pl line 5127 (#1)
[!!] Node is not synced
Use of uninitialized value $mystat{"wsrep_local_state_comment"} in
	concatenation (.) or string at ./tuner.pl line 5132 (#1)
[--] Node State : 
Use of uninitialized value $mystat{"wsrep_local_cert_failures"} in numeric eq
	(==) at ./tuner.pl line 5134 (#1)

**Comment by jmrenouard** [comment]
Hi @mia0x75 

Can you tell me more on version ?
Can you send--debug output for this script ?

**Comment by lapause** [comment]
I have the same problem, 3900+ lines of warning when running the script, which makes it unusable without redirecting stderr output elsewhere.

- [Complete stderr output](https://pastebin.com/1dn3DrGs)
- Version: 1.7.3
- OS: Ubuntu 16.04.2

Issue title should be read _Use of uninitialized values_.

**Comment by sergey-dryabzhinsky** [comment]
Same problem.

- stderr output (cutted):
```
Use of uninitialized value in concatenation (.) or string at
        /usr/bin/mysqltuner line 1244, <$fh> line 2 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    anid the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.

Use of uninitialized value $maj in int at /usr/bin/mysqltuner line 1883, <$fh>
        line 2 (#1)
Use of uninitialized value $cve[1] in int at /usr/bin/mysqltuner line 1250,
        <$fh> line 2 (#1)
Use of uninitialized value in concatenation (.) or string at
        /usr/bin/mysqltuner line 1244, <$fh> line 4 (#1)
Use of uninitialized value $maj in int at /usr/bin/mysqltuner line 1883, <$fh>
        line 4 (#1)
Use of uninitialized value $cve[1] in int at /usr/bin/mysqltuner line 1250,
        <$fh> line 4 (#1)
Use of uninitialized value in concatenation (.) or string at
        /usr/bin/mysqltuner line 1244, <$fh> line 6 (#1)
Use of uninitialized value $maj in int at /usr/bin/mysqltuner line 1883, <$fh>
        line 6 (#1)
Use of uninitialized value $cve[1] in int at /usr/bin/mysqltuner line 1250,
        <$fh> line 6 (#1)
...
```
- Version: 1.7.3 +git d5c4ae85f85bcee08ddea080f975688bcfd39744
- OS: Ubuntu 14.04.5 amd64
- MariaDB 10.1.25

**Comment by sergey-dryabzhinsky** [comment]
Seems like something broken in latest CVE csv-file.

**Comment by sergey-dryabzhinsky** [comment]
Yes!
New csv file is broken.
It contains empty lines!
So script can't process them.

**Comment by jmrenouard** [comment]
Can you tell me if it's better now ?

**Comment by jmrenouard** [comment]
Hi @mia0x75 

I think you problem is different than CVE issue !

Can you give me your debug output (option --debug) ?

Thanks

**Comment by sergey-dryabzhinsky** [comment]
@jmrenouard Confirm. No more errors.

**Comment by lapause** [comment]
@jmrenouard I can also confirm, no more errors on output. Thanks a lot.

**Comment by jmrenouard** [comment]
Hi,

Thanks for your precious feedback.
