### ISSUE TITLE
MariaDB 10.2.x support

### ISSUE THREAD

**Issue by mia0x75** [major/MySQLTuner-perl#326]
You might already know, innodb is now the default storage engine of MariaDB 10.2, so the tool need to be revised to support it.

Error msgs on 10.2:
[!!] InnoDB is enabled but isn't being used
[!!] failed to execute: SHOW TABLE STATUS FROM \`#mysql50#.rocksdb\` # <- this is for rocksdb
[!!] Thread cache hit rate: -12% (136 created / 121 connections) # <- no idea why the hit ratio is negative here
[!!] InnoDB Storage engine is disabled. InnoDB is the default storage engine

Suggestion from the tool:
Add skip-innodb to MySQL configuration to disable InnoDB

**Comment by jmrenouard** [comment]
Hi @mia0x75 

Help is needed for this new version :)

PR welcomed ...

**Comment by jmrenouard** [comment]
Hi @mia0x75 

Can you give us you feedback ?

I think innodb and rocksdb should be used at the same time.

MariaDB 10.2 works fine on our servers.

Can we close this issue related to MariaDB 10.2 ?

If you face issue related to rocksdb, can you open a specific issue for that ?

thanks by advance,

**Comment by rotate4all** [comment]
Works fine over here. All recommendations are in order. 
Using Server version: 10.2.18-MariaDB MariaDB Server along with InnoDB tables.
The issue at hand is most likely related to rocksdb.
