### ISSUE TITLE
~/.my.cnf credentials problem

### ISSUE THREAD

**Issue by temporaryaccount** [major/MySQLTuner-perl#329]
I have a ~/.my.cnf file with these contents:

```
[mysqladmin]
password = <redacted>
user = root
```

MySQLTuner refuses to run and gives the following error:

```
 >>  MySQLTuner 1.7.2 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[!!] failed to execute: SELECT VERSION()
[!!] FAIL Execute SQL / return code: 256
[!!] You probably doesn't get enough privileges for running MySQLTuner ...
```

When I remove the ~/.my.cnf file everything is working normally (i.e. MySQLTuner asks for my username and password). When I change the `[mysqladmin]` line to `[client]` MySQLTuner also works correctly (without asking for credentials) but I want to use the saved password only for the mysqladmin program.

**Comment by jmrenouard** [comment]
Hi @temporaryaccount 

As explained, we need a credentials in .my.cnf in [client] block
[mysqladmin] block is not enougth.
In this case, you will need [mysql] block also.

BR,

**Comment by temporaryaccount** [comment]
If I wanted `MySQLTuner` to use the credentials in `.my.cnf` I would've done exactly that. But I don't want it, I want `mysqladmin` to use `.my.cnf` and `MySQLTuner` to ask for credentials. The bug is that when `MySQLTuner` fails to find the `[client]` section in `.my.cnf` it generates an error instead of asking for the credentials as normally.

Thank you.

**Comment by jmrenouard** [comment]
Hi @temporaryaccount 

MySQL Tuner is not created to ask you password for access for each individual program(i.e: mysql, mysqladmin,...).

In fact, access with password is determined by mysqladmin ping only.
This means that if mysqladmin can access without any password all other programs are suppossed to access the same way.

BR,

**Comment by temporaryaccount** [comment]
> This means that if mysqladmin can access without any password all other programs are suppossed to access the same way.

Please allow me to disagree. There is a reason that one can use different `[sections]` in .my.cnf file like `[mysqladmin]` and `[client]` - for each its own. If I have only the `[mysqladmin]` section mysqladmin.exe uses it, mysql.exe doesn't use it.

But if you are thinking differently then you can close this issue of course. Thank you.

**Comment by jmrenouard** [comment]
Hi @temporaryaccount 

I'm agree with you and mysqltuner is basically coded to used one UNIX account with a simple directive [client].

Feel free to create a dedicated UNIX user for mysqltuner usage only.

Best regards,

**Comment by temporaryaccount** [comment]
Well that's one possible work-around, thank you.

If you are not planning to enhance the robustness of the .my.cnf parser in the future then this issue can be safely closed, otherwise, I think something like this pseude-code (I don't know Perl) would be the right way:

```
if (user_set_from_cmdline || passwd_set_from_cmdline) {
    // use the specified credentials
}
else if (file_exists_and_readable('~/.my.cnf')) {
    client = ini_read_section('[client]', '~/.my.cnf');
    if (!client || !client.username || !client.password) {
        username, password = ask_for_credentials();
    } else {
        username = client.username;
        password = client.password;
    }
} else {
    username, password = ask_for_credentials();
}
```

**Comment by jmrenouard** [comment]
Hi @temporaryaccount 

In fact, I propose to create a UNIX account dedicated for MySQLtuner usage.
This account can contain his own .my.cnf.
It is also very easy to create a dedicated MySQL/MariaDB account for tuning.

I propose you this simple workaround.
This is also a good security advice because you can perform analyze through non-super-admin account.

Best regards,
