### ISSUE TITLE
encode --outputfile in UTF-8 (not US-ASCII)

### ISSUE THREAD

**Issue by GETandSELECT** [major/MySQLTuner-perl#333]
Hey

thanks for awesome software. Your script a great help. Is there a reason why the output is in us-ascii?

GitHub Gist require the files in UTF-8 (upload via API).

```
file -i result_mysqltuner.txt
result_mysqltuner.txt: text/plain; charset=us-ascii

gist-paste -p result_mysqltuner.txt
Error: source sequence is illegal/malformed utf-8

iconv -f US-ASCII -t UTF-8 result_mysqltuner.txt > result_mysqltuner_uft8.txt
iconv: illegal input sequence at position 804244
```

thanks

**Comment by jmrenouard** [comment]
Hi @GETandSELECT 

Thanks for this useful commands I will archive :)

Do you find which character is rising this error ? Do you know how to find them ?

Thanks for you help
@jmrenouard

**Comment by GETandSELECT** [comment]
Hi @jmrenouard 

No I don't know.
I tested on macOS box and the file is also us-ascii

```
$ file -I /tmp/result_mysqltuner.txt 
/tmp/result_mysqltuner.txt: text/plain; charset=us-ascii
```

I recommend encode the output file in UTF-8.

**Comment by jmrenouard** [comment]
Hi @GETandSELECT 
I don't change anything :)

I just thank you for command you share with us ...

**Comment by jmrenouard** [comment]
Hi, can you send me a mysqltuner.txt samples for this issue ?

**Comment by jmrenouard** [comment]
Hi, can do anything without any feedback ?

Feel free to reopen issue if you get some feedback for this strange issue.
