### ISSUE TITLE
no ndb engine analysis

### ISSUE THREAD

**Issue by imic07** [major/MySQLTuner-perl#336]
my engine is ndbcluster, why there is no NDBCLUSTER Metrics, hope add it
![image](https://user-images.githubusercontent.com/16321067/28148884-1408cf66-67bc-11e7-910b-f3b0fd825e1a.png)

**Comment by jmrenouard** [comment]
Hi @imic07 

Nice idea help wanted for this features.

Do you get some ideas about metrics to check and display ?

Thanks,

**Comment by jmrenouard** [comment]
Pull request welcome
