### ISSUE TITLE
use File::Map for reading the log file

### ISSUE THREAD

**Issue by phirestalker** [major/MySQLTuner-perl#337]
since MYSQL has NEVER heard of log rotating, log files can get larger than 10GB. Currently, this script attempts to load the whole file into memory. It would be safer to use something like File::Map which uses mmap to access the file.

**Comment by jmrenouard** [comment]
Hi,

Yes nice idea.
I order to limit dependencies a other way is to read line by line also.

Pull request welcomes !

**Comment by jmrenouard** [comment]
Hi @phirestalker 

@tompmeyer changes code in order to be ableto read line by line without extra Perl module needed.

Is last commit version solved your issue ?

Thanks by advance,

**Comment by phirestalker** [comment]
I'm no longer running the database, so I can't test.

**Comment by jmrenouard** [comment]
Hi @tompmeyer 

I will close this issue. thanks for your PR.

Have a nice day.
