### ISSUE TITLE
Incorrect table name in recommendation

### ISSUE THREAD

**Issue by zharovdv** [major/MySQLTuner-perl#339]
If database have dot in name (eg.: create database `example.com`;) you will get incorrect recommendations like:

General recommendations:
    Run OPTIMIZE TABLE to defragment tables for better performance
      OPTIMIZE TABLE **`example`.`com`;**

**Comment by jmrenouard** [comment]
Hi @zharovdv 

Thanks for your feedback.

Line 2151: we push in 1.7.4 
OPTIMIZE TABLE `$table_schema`.`$table_name` recommandations

   push( @generalrec,
"  OPTIMIZE TABLE `$table_schema`.`$table_name`; -- can free $data_free MB"
            );


Are you using the master branch on git hub ?

thanks for your feedback

**Comment by zharovdv** [comment]
>>  MySQLTuner 1.7.4 - Major Hayden <major@mhtx.net>

my ( $table_schema, $table_name ) = split( /\./, $full_table_name ); 
problem line as i understand - you can't use any kind of separator to get schema name and table name - from full_table_name

**Comment by jmrenouard** [comment]
It works for me.
mysql> optimize table rental;                                                                                                                                                                    +---------------+----------+----------+-------------------------------------------------------------------+
| Table         | Op       | Msg_type | Msg_text                                                          |
+---------------+----------+----------+-------------------------------------------------------------------+
| sakila.rental | optimize | note     | Table does not support optimize, doing recreate + analyze instead |
| sakila.rental | optimize | status   | OK                                                                |
+---------------+----------+----------+-------------------------------------------------------------------+
2 rows in set (0.58 sec)

mysql> optimize table sakila.rental;                                                                                                                                                             +---------------+----------+----------+-------------------------------------------------------------------+
| Table         | Op       | Msg_type | Msg_text                                                          |
+---------------+----------+----------+-------------------------------------------------------------------+
| sakila.rental | optimize | note     | Table does not support optimize, doing recreate + analyze instead |
| sakila.rental | optimize | status   | OK                                                                |
+---------------+----------+----------+-------------------------------------------------------------------+
2 rows in set (0.60 sec)
