### ISSUE TITLE
MariaDB 10.0.x support

### ISSUE THREAD

**Issue by minecrafter** [major/MySQLTuner-perl#34]
mysqltuner does not like MariaDB 10.0.x for some reason. [Here](https://gist.github.com/minecrafter/96b8c5311fee5385aed1) is output from it.

MariaDB 10.0.x is essentially MySQL 5.6, so I'd love for support to be added.

I am running Ubuntu 12.04 and MariaDB 10.0.4-MariaDB-1~precise-log.

**Comment by centminmod** [comment]
seems problem might be back now that MariaDB 10 tagged an extra -MariaDB suffix

    [!!] Currently running unsupported MySQL version 10.0.17-MariaDB
