### ISSUE TITLE
debian credentials not overridable from commandline

### ISSUE THREAD

**Issue by tomas-mazak** [major/MySQLTuner-perl#341]
Hi there,

when running mysqltuner on Ubuntu, it apparently checks for Debian-based distro and then use `/etc/mysql/debian.cnf` as the defaults file to load the credentials from.

However, if the credentials in this file are not valid for some reason, e.g. customer deleted the user in database, I would expect to be able to provide another defaults file, like:
```
mysqltuner.pl --defaults-file=/root/my.cnf
```

Even though this option exists, it does not have an effect in this case, what I think is a bug.

Cheers,

Tomas

**Comment by jmrenouard** [comment]
Hi,

Can you tell me if 17.4 is fixing your issue ?

**Comment by jmrenouard** [comment]
Hi @tomas-mazak 

Can you give us some feedback ?

Thanks by advance,

**Comment by jmrenouard** [comment]
Hi @tomas-mazak 

I close this issue because I think this is already fixed since a moment.

Best regards
