### ISSUE TITLE
Getting overwhelmed from the result report

### ISSUE THREAD

**Issue by macnux** [major/MySQLTuner-perl#342]
Hi,
Today I found the MariaDB server was down without reason !! and an email was sent to me from my server that there is a high load.
I'm sure that Mysql causes the problem. I download the script and run, it gives me that report
![untitled](https://user-images.githubusercontent.com/3065946/29664276-384863ee-88cf-11e7-9db0-b0b206e9a575.png)
My VPS is:
CentOS 7
2 GB memory
And I'm using MariaDB 10.1.26 
what should I do in my critical situation? should I allow query cache at first? and what this line means
[!!] Overall possible memory usage with other process exceeded memory

Regards,

**Comment by jmrenouard** [comment]
Hi,

1° Increase RAM on you server.
2° max_heap_table and tmp_table_size  should be increased.
3° skip-resolve-name
4° Query_cache_type=0

I closed this item.
BR,

**Comment by macnux** [comment]
I'm sorry one last thing.
Some people turn caching for better MariaDB load and they recommend me the following
query_cache_type = 1
query_cache_limit = 256K
query_cache_min_res_unit = 2k
query_cache_size = 80M
What is your opinion ?

Regards,
