### ISSUE TITLE
Lots of vulnerabilities shows up when I run mysqltuner against Aurora

### ISSUE THREAD

**Issue by vroad** [major/MySQLTuner-perl#344]
Does mysqltuner currently support Aurora?
The tool told me that the DB version I'm using has more than 200 vulnerabilities.
I guess it's just because Aurora is based on older MySQL version (5.6.10).

I'm using Aurora 1.11 now. It's not the latest version, though it shouldn't have vulnerabilities that are found 4 years ago.

**Comment by jmrenouard** [comment]
Hi @vroad 

We are not supporting vulnerabilities for Aurora.
In order to get Aurora vulnerabilities, you can consult this list:
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=Aurora+

**Comment by jmrenouard** [comment]
You can also consult updates policy here:
http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Aurora.DatabaseEngineUpdates.html

**Comment by vroad** [comment]
@jmrenouard Wouldn't it be better to warn about this and disable the feature when Aurora specific system properties are detected from DB?

Users like me may mistakenly run vulnerabilities check even if Aurora is not in supported DB list.
