### ISSUE TITLE
Mysql 5.7.18 - Amazon Linux - Your MySQL version  is EOL software!  Upgrade soon!

### ISSUE THREAD

**Issue by Dan904** [major/MySQLTuner-perl#349]
Recently just upgraded mysql to 5.7 on amazon linux and mysqltunner doesn't seem to be connecting to mysql and showing " Your MySQL version  is EOL software!  Upgrade soon!" when I just updated. Any help would be appreciated! 

Here is the output.

>>  MySQLTuner 1.7.4 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[!!] Successfully authenticated with no password - SECURITY RISK!
[!!] failed to execute: SHOW VARIABLES
[!!] FAIL Execute SQL / return code: 256
[!!] failed to execute: SHOW GLOBAL VARIABLES
[!!] FAIL Execute SQL / return code: 256
[!!] failed to execute: SHOW STATUS
[!!] FAIL Execute SQL / return code: 256
[!!] failed to execute: SHOW GLOBAL STATUS
[!!] FAIL Execute SQL / return code: 256
Use of uninitialized value $myvar{"version"} in pattern match (m//) at
        mysqltuner.pl line 1881 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    anid the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.

Use of uninitialized value $mysqlvermajor in int at mysqltuner.pl line 1908 (#1)
Use of uninitialized value $myvar{"version"} in concatenation (.) or string at
        mysqltuner.pl line 1886 (#1)
[!!] Your MySQL version  is EOL software!  Upgrade soon!
[OK] Operating on 64-bit architecture
Use of uninitialized value $file in string at mysqltuner.pl line 1155 (#1)
Use of uninitialized value $hostname in concatenation (.) or string at
        mysqltuner.pl line 1158 (#1)
Use of uninitialized value $datadir in string ne at mysqltuner.pl line 1161 (#1)

-------- Log file Recommendations ------------------------------------------------------------------
Use of uninitialized value $myvar{"log_error"} in concatenation (.) or string
        at mysqltuner.pl line 1172 (#1)
Use of uninitialized value $myvar{"log_error"} in stat at mysqltuner.pl line
        1172 (#1)
[--] Log file: (0B)
Use of uninitialized value $myvar{"log_error"} in string at mysqltuner.pl line
        1175 (#1)
Use of uninitialized value $myvar{"log_error"} in concatenation (.) or string
        at mysqltuner.pl line 1179 (#1)
[!!] Log file  doesn't exist
Use of uninitialized value $myvar{"log_error"} in string at mysqltuner.pl line
        1181 (#1)
Use of uninitialized value $myvar{"log_error"} in concatenation (.) or string
        at mysqltuner.pl line 1185 (#1)
[!!] Log file  isn't readable.

-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +Archive -BDB -Federated +InnoDB -ISAM -NDBCluster
[--] Data in InnoDB tables: 321K (Tables: 70)
[!!] Total fragmented tables: 44

-------- Security Recommendations ------------------------------------------------------------------
Use of uninitialized value $myvar{"version"} in pattern match (m//) at
        mysqltuner.pl line 1686 (#1)
[OK] There are no anonymous accounts for any database users
Use of uninitialized value $mysqlvermajor in int at mysqltuner.pl line 1921 (#1)
[!!] No more password checks for MySQL version <=5.1
[!!] MySQL version <=5.1 are deprecated and end of support.

-------- CVE Security Recommendations --------------------------------------------------------------
[--] Skipped due to --cvefile option undefined
Use of uninitialized value $mystat{"Questions"} in numeric lt (<) at
        mysqltuner.pl line 2250 (#1)
[!!] Your server has not answered any queries - cannot continue...

**Comment by jmrenouard** [comment]
Hi @Dan904 

It seems that you get a authentication issue.

Can you check and use username and password option to check this part, please ?

BR,

**Comment by peku33** [comment]
I had the same issue after uprgading mysql to 5.7 on Gentoo Linux.
I needed to run mysql_upgrade script and then restart mysql server.

**Comment by jmrenouard** [comment]
Hi,

Actually, we are not supporting cloud based mysql/mariaDB/percona.

But you are both right that code related to each version checks is a real mess :)

**Comment by jmrenouard** [comment]
Hi @Dan904,

Is it better on last version ?
