### ISSUE TITLE
Use of uninitialized value $engine in concatenation (.) or string

### ISSUE THREAD

**Issue by mia0x75** [major/MySQLTuner-perl#350]
Use of uninitialized value $engine in concatenation (.) or string at
	mysql-tuner.pl line 2032, <STDIN> line 2 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.
    
    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    and the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.

MariaDB 10.2.10 on Fedora 25

**Comment by Reborns** [comment]
Almost the same error on version 1.7.7
`Use of uninitialized value $_[0] in concatenation (.) or string at
        /opt/tools/mysqltuner.pl line 233 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.`

**Comment by jmrenouard** [comment]
Show be better now :)

**Comment by jmrenouard** [comment]
No anwser 

Feel free to reopen issue if needed with details.

**Comment by weberhofer** [comment]
Hi  @jmrenouard, this issue is still here:

# mysqltuner.pl 
 >>  MySQLTuner 1.7.17 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[OK] Currently running supported MySQL version 10.2.25-MariaDB
[OK] Operating on 64-bit architecture
 
-------- Log file Recommendations ------------------------------------------------------------------
[!!] Log file  doesn't exist
 
-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +Aria +CSV +InnoDB +MEMORY +MRG_MyISAM +MyISAM +PERFORMANCE_SCHEMA +SEQUENCE 
Use of uninitialized value $engine in concatenation (.) or string at
	/usr/bin/mysqltuner.pl line 2200 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

**Comment by weberhofer** [comment]
On another server having the same linux version I don't see this issue. The result in the mentione section is:
```
-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +Aria +CSV +InnoDB +MEMORY +MRG_MyISAM +MyISAM +PERFORMANCE_SCHEMA +SEQUENCE 
[--] Data in InnoDB tables: 6.6G (Tables: 5369)
[--] Data in MyISAM tables: 1.3G (Tables: 4246)
[--] Data in MEMORY tables: 0B (Tables: 13)
[OK] Total fragmented tables: 0
```
So it seems to make a difference is the sections with "MEMORY tables" is visible or not.

**Comment by jmrenouard** [comment]
OK I reopen this issue

**Comment by weberhofer** [comment]
@jmrenouard Please let me know how I can help.

**Comment by jmrenouard** [comment]
@weberhofer 

Can you tell me if it's better for you ?

**Comment by grooverdan** [comment]
trim should be after next in https://github.com/major/MySQLTuner-perl/commit/6aa887d5a5e10d7dbcc7fd0e24908301fe33ae82#diff-126d6c210bc4ad821cc428b8034b177003fc7171ac178088fdf6ce91cb787867R2201-R2202
subsequent tests don't need `trim($engine)`

**Comment by jmrenouard** [comment]
Feel this is OK now ?
Feel free to reopen
