### ISSUE TITLE
failed to execute sql

### ISSUE THREAD

**Issue by mia0x75** [major/MySQLTuner-perl#351]
[!!] failed to execute: SELECT CONCAT(CONCAT(TABLE_SCHEMA, '.'), TABLE_NAME),DATA_FREE FROM information_schema.TABLES WHERE TABLE_SCHEMA NOT IN ('information_schema','performance_schema', 'mysql') AND DATA_LENGTH/1024/1024>100 AND DATA_FREE*100/(DATA_LENGTH+INDEX_LENGTH+DATA_FREE) > 10 AND NOT ENGINE='MEMORY' 
[!!] FAIL Execute SQL / return code: 256

```
MariaDB [drafts]> SELECT CONCAT(CONCAT(TABLE_SCHEMA, '.'), TABLE_NAME),DATA_FREE FROM information_schema.TABLES WHERE TABLE_SCHEMA='drafts';
+-----------------------------------------------+----------------------+
| CONCAT(CONCAT(TABLE_SCHEMA, '.'), TABLE_NAME) | DATA_FREE            |
+-----------------------------------------------+----------------------+
| drafts.foo                                    | 18446744068759729344 |
+-----------------------------------------------+----------------------+
1 row in set (0.00 sec)

MariaDB [drafts]> SELECT COUNT(*) FROM foo;
+----------+
| COUNT(*) |
+----------+
|  2611952 |
+----------+
1 row in set (31.66 sec)
```
Table foo has more than 200 columns, in TokuDB format.

MariaDB 10.2.10 on Fedora 25

**Comment by jmrenouard** [comment]
Hi @mia0x75 

We are facing a lot of issue with infor for TokuDB.

**Comment by jmrenouard** [comment]
TokuDB is not longer active since feb. 2015.

Can we close this item ?

**Comment by mia0x75** [comment]
FYI
https://github.com/percona/percona-server/tree/5.7/storage/tokudb

**Comment by jmrenouard** [comment]
Nothing new on this storage engine
Seems to be dead
https://github.com/percona/percona-server/tree/8.0/storage/tokudb

I closed this issue
