### ISSUE TITLE
query_cache_type & query_cache_size check

### ISSUE THREAD

**Issue by mia0x75** [major/MySQLTuner-perl#352]
- mysql
query_cache_type is disabled by default start from MySQL 5.6

-mariadb
query_cache_type is disabled by default start from MariaDB 10.1.7

For reference
http://www.tocker.ca/2013/09/27/how-do-you-use-the-query-cache.html

**Comment by jmrenouard** [comment]
Hi @mia0x75 
We are checking that query cache is disabled actually.
What is expected behaviour, so ?

Thanks for your feedback !

**Comment by mia0x75** [comment]
Sorry, I'm using 1.7.1, and after upgrade to latest git version, the recommendation is disappeared. Please close it, thx.
