### ISSUE TITLE
Handle case where authentication is via external plugin

### ISSUE THREAD

**Issue by racker-markh** [major/MySQLTuner-perl#358]
I use auth_pam_compat to allow certain users to login using their AD credentials on an appropriately configured linux server:
e.g.
```
# create Database
create database foo_db
# create a standard user with only access to that database from a specific IP
grant all on foo_db.* to 'foo_user'@'10.0.0.1' identified by 'aRandomPassword';
# allow an AD user access to the database from anywhere and grant access to the db.
create user 'ad_user_faz'@'%' identified with auth_pam_compat;
grant all on foo_db.* to 'ad_user_faz'@'%';
```

When running mysqltuner we would get warnings like:
```
[!!] User 'ad_user_faz@%' has no password set.
...
[!!] User 'ad_user_faz@%' hasn't specific host restriction
```

While we can accept the warnings about specific host restrictions (It's a valid warning, but in this case we control the network environment), but it would be great if mysqltuner would check whether  mysql.user.plugin = auth_pam_compat for the 'no password set' warning, since these users are only able to login using a password. 

Alternatively check whether this field is set to mysql_native_password and only error if this is the case when the password field is blank.

Regards
Mark

(Thanks for a great tool!!)

**Comment by jmrenouard** [comment]
Hi @racker-markh 

We don't get this kind of platform to validate this type of config.

I'm asking some help :)

**Comment by racker-markh** [comment]
#361

**Comment by jmrenouard** [comment]
Hi @racker-markh 

Can we close this ticket ?

**Comment by racker-markh** [comment]
Hi, yes that's fine. It was merged a good while back :)
