### ISSUE TITLE
[!!] There is no basic password file list!

### ISSUE THREAD

**Issue by slrslr** [major/MySQLTuner-perl#359]
The mysqltunner.pl returned this line:

[!!] There is no basic password file list!

Please where can i see explanation what this mean and how to fix it? I am using CentOS 6, MySQL 5.5

**Comment by mia0x75** [comment]
README:

`
wget http://mysqltuner.pl/ -O mysqltuner.pl
wget https://raw.githubusercontent.com/major/MySQLTuner-perl/master/basic_passwords.txt -O basic_passwords.txt
wget https://raw.githubusercontent.com/major/MySQLTuner-perl/master/vulnerabilities.csv -O vulnerabilities.csv
perl mysqltuner.pl
`

**Comment by jmrenouard** [comment]
Hi @slrslr Hi @mia0x75 

Thanks for anwser :)

**Comment by slrslr** [comment]
@mia0x75 
After following Your advice, i found the warning disappeared, maybe instead of that i see:
[--] There are 612 basic passwords in the list.
i assume it means i am using alot of weak (basic) passwords, indeed when attempted to migrate to server with higher mysql version, it forced password reset.
