### ISSUE TITLE
[!!] Query cache may be disabled by default due to mutex contention.

### ISSUE THREAD

**Issue by slrslr** [major/MySQLTuner-perl#360]
The mysqltunner.pl returned this line:

[!!] Query cache may be disabled by default due to mutex contention.

How can i discover if i should disable mutex contenion?
I am using CentOS 6, MySQL 5.5 (cPanel control panel)

**Comment by jmrenouard** [comment]
Hi @slrslr 

Query cache is producing Mutex contention on request.
This cache is single threaded and each access produce a global read access lock.
So disabling QC avoid contention generation.

BR,
