### ISSUE TITLE
Sys schema on MariaDB

### ISSUE THREAD

**Issue by Steve8291** [major/MySQLTuner-perl#362]
I've just installed and ran mysqltuner for the first time and it is recommending that I install Sys schema.
`Consider installing Sys schema from https://github.com/mysql/mysql-sys` 
Could someone please suggest if I should do this since it appears that mysql-sys is built only for MySQL and I am running MariaDB 10.1.25

**Comment by jmrenouard** [comment]
Hi @Steve8291 

MariaDB 10.1 is mostly a MySQL 5.6 
used sys_56.sql
https://github.com/mysql/mysql-sys

You will have some error messages and you could safely ignore them.

BR,

**Comment by Zeuh** [comment]
Perhaps add some documentations about MariaDB support/no support ?

**Comment by zolez** [comment]
you can find some workaround here: https://github.com/mysql/mysql-sys/pull/99

**Comment by jmrenouard** [comment]
Hi 3 links to understand sysschema and MariaDB.

https://jira.mariadb.org/browse/MDEV-9077
https://github.com/good-dba/mariadb-sys
https://www.fromdual.com/mysql-sys-schema-in-mariadb-10-2

Best regards,
@jmrenouard

**Comment by jmrenouard** [comment]
Feel free to reopen issue if needed

**Comment by Steve8291** [comment]
Thank you @jmrenouard
