### ISSUE TITLE
Wrong sort order in MySQLTuner report

### ISSUE THREAD

**Issue by makhomed** [major/MySQLTuner-perl#363]
Wrong sort order in MySQLTuner report.
```
mysqltuner.pl  --pfstat --nocolor 
```
output, for example:
```
...
-------- Performance schema: Top IO type order by max latency --------------------------------------
[--]  +-- 1: sql/casetest	886.27 us
[--]  +-- 2: sql/file_parser	8.76 us
[--]  +-- 3: csv/data	737.07 us
[--]  +-- 4: csv/metadata	674.95 ms
[--]  +-- 5: sql/slow_log	516.14 ms
[--]  +-- 6: innodb/innodb_log_file	5.08 s
[--]  +-- 7: innodb/innodb_parallel_dblwrite_file	4.65 s
[--]  +-- 8: myisam/dfile	39.63 ms
[--]  +-- 9: sql/ERRMSG	38.07 us
[--]  +-- 10: sql/pid	37.46 us
[--]  +-- 11: innodb/innodb_data_file	3.72 s
[--]  +-- 12: sql/global_ddl_log	3.37 us
[--]  +-- 13: sql/dbopt	28.99 us
[--]  +-- 14: myisam/kfile	28.86 us
[--]  +-- 15: archive/data	2.69 us
[--]  +-- 16: sql/FRM	162.88 ms
[--]  +-- 17: mysys/cnf	16.66 us
[--]  +-- 18: mysys/charset	11.34 us
[--]  +-- 19: sql/io_cache	1.46 s
...
```
output sorted by max_latency as strings, 
but it should be sorted as time values - numbers considering value suffixes.

Server version:
```
5.7.20-18-log Percona Server (GPL), Release 18, Revision 7ce54a6deef
```
This bug appears in many different reports if using  ```--pfstat`` command line argument,
"Top IO type order by max latency" provided here only for example.

**Comment by jmrenouard** [comment]
Hi @makhomed 

YES, I already catch this point and need some energy to fix it :)

**Comment by jmrenouard** [comment]
Done :)

**Comment by jmrenouard** [comment]
Hi @makhomed

Some feedback ?

**Comment by makhomed** [comment]
> Some feedback ?

I update MySQLTuner to version 1.7.7 and run command ```mysqltuner.pl  --pfstat --nocolor ``` again.

I see such output:
```
...
-------- Performance schema: Top IO type order by max latency --------------------------------------
[--]  +-- 1: innodb/innodb_log_file     2441294253972
[--]  +-- 2: innodb/innodb_parallel_dblwrite_file       2116861389559
[--]  +-- 3: innodb/innodb_data_file    555420690510
[--]  +-- 4: sql/slow_log       104308973300
[--]  +-- 5: sql/io_cache       65438153648
[--]  +-- 6: sql/file_parser    12332183360
[--]  +-- 7: sql/FRM    10860977736
[--]  +-- 8: myisam/dfile       2682012704
[--]  +-- 9: innodb/innodb_temp_file    2054924592
[--]  +-- 10: sql/ERRMSG        1308793472
[--]  +-- 11: sql/casetest      1181705280
[--]  +-- 12: myisam/kfile      453027204
[--]  +-- 13: mysys/charset     302732192
[--]  +-- 14: csv/metadata      241109848
[--]  +-- 15: mysys/cnf 149227372
[--]  +-- 16: csv/data  53699996
[--]  +-- 17: sql/dbopt 31285296
[--]  +-- 18: sql/pid   30076452
[--]  +-- 19: archive/data      27400464
[--]  +-- 20: sql/misc  12986176
[--]  +-- 21: sql/global_ddl_log        6102768
...
```

Order is right, but now I can't understand what numbers 2441294253972 and 2116861389559
mean. This numbers are not human readable now. I expect to see here human readable numbers,
as string with suffixes, like "5.08 s" and so on. Like it was in previous versions but in right order.

Server version:
```
Server version: 5.7.20-19-log Percona Server (GPL), Release 19, Revision 3c5d3e5d53c
```
Server uptime: ```61d 12h 42m```

**Comment by jmrenouard** [comment]
Hi @makhomed 

This is max_latency found by instruments in performance_schema.

Best regards

**Comment by jmrenouard** [comment]
Can we close this ticket and open a new issue in order to tell we can add human readeable value ?

**Comment by makhomed** [comment]
Yes, you can do it.
Or I should create new issue about human readable value?
As for me, this is cosmetic and low priority bug.

For example, bug  #386 is critical and high priority, from my point of view.
