### ISSUE TITLE
mysqltuner hangs as soon as log in.

### ISSUE THREAD

**Issue by dpark77** [major/MySQLTuner-perl#368]
# perl mysqltuner.pl --debug
 >>  MySQLTuner 1.7.5 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[DG] MySQL Client: /bin/mysql would have been started with the following arguments:
--socket=/mysql/mysql.sock

[DG] MySQL Client: /bin/mysql
[DG] /bin/mysqladmin  ping 2>&1
Please enter your MySQL administrative login: user
Please enter your MySQL administrative password: [DG] Physical Memory: 33525571584
[DG] Swap Memory: 0

I have Centos 7.4, Mariadb/Mysql 5.5.56 installed.

**Comment by jmrenouard** [comment]
Hi @dpark77 

What about behaviour when using --user and --password in command line ?
