### ISSUE TITLE
Enable performance_schema recommendation on MariaDB 10.0.12+

### ISSUE THREAD

**Issue by Justin-L-Franks** [major/MySQLTuner-perl#369]
MariaDB has disabled the performance schema [since version 10.0.12](https://mariadb.com/kb/en/library/mariadb-10012-release-notes/), due to [performance reasons](https://mariadb.com/kb/en/library/performance-schema-overview/#activating-the-performance-schema).

So the recommendation to enable the performance schema on MariaDB 10.0.12+ should be suppressed.

**Comment by jmrenouard** [comment]
thanks for feedback around MariaDB 10.0 and performance schema issue :)

**Comment by Justin-L-Franks** [comment]
There's a slight error in the commit regarding this issue. The performance schema was disabled by default starting with MariaDB 10.0.12, and has continued to be disabled by default through to the current version (through 10.13.x).

The commit only checks if the MariaDB version is equal to 10.0.x. This means that early versions of 10.0.x, where the performance schema is still active by default, the "should be disabled" message is shown. Although it could be argued that it for 10.0.0 through 10.0.11, the message should still be shown, since it is mostly the same; the performance issues were just not discovered until 10.0.12.

But more importantly, the commit does not show the "performance schema should be disabled" message at all for 10.11.x, 10.12.x, or 10.13.x.

Instead of: (starting at [line 3428](https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L3428) in the current code)

```
if ( mysql_version_eq( 10, 0 ) ) {
        push( @generalrec,
"Performance shouldn't be activated for MariaDB 10.0 for performance issue"
        );
        push( @adjvars, "performance_schema = OFF disable PFS" );
        return;
    }
```
It should be, if you decide to go with MariaDB >= 10.0:

```
if ( mysql_version_ge( 10, 0 ) ) {  
        push( @generalrec,
"Performance schema shouldn't be activated for MariaDB >= 10.0 for performance issue" 
        );
        push( @adjvars, "performance_schema = OFF disable PFS" );
        return;
    }
```
Or, optionally, if you decide to go with MariaDB >= 10.0.12
```
if ( mysql_version_ge( 10, 0, 12 ) ) {  
        push( @generalrec,
"Performance schema shouldn't be activated for MariaDB >= 10.0.12 for performance issue" 
        );
        push( @adjvars, "performance_schema = OFF disable PFS" );
        return;
    }
```

**Comment by micah** [comment]
@jmrenouard this issue seems like it should be re-opened, in light of the comments above by @Justin-L-Franks
