### ISSUE TITLE
Latest version has a regression with colored outout

### ISSUE THREAD

**Issue by ddarbyson** [major/MySQLTuner-perl#371]
I use MySQL Tuner to output to HTML via `ansifilter`:

```bash
/usr/local/bin/mysqltuner | ansifilter --html > /var/www/html/reports/mysqltuner_2018-02-19.html
```

This no longer works as STDOUT is always being detected and enabling --nocolor by default... This should not be assumed.

The last working version was 1.6.18.

**Comment by jmrenouard** [comment]
@ddarbyson 

Fix added.

**Comment by ddarbyson** [comment]
@jmrenouard just tested... still doesn't produce coloured output as desired

`/usr/local/bin/mysqltuner | ansifilter`

The last working version was 1.6.18.

**Comment by jmrenouard** [comment]
Ok,

When mysqltuner is used with piped command color shouldn't be dispalyed.
mysqltuner.pl | less for example is very hard to read with color tags.


In your case, I have add a special option to force color for this kind off piped command.

mysqltuner.pl -color  | ansifilter
should behaves as you expected.

**Comment by ddarbyson** [comment]
Sorry @jmrenouard that doesn't work:

`/usr/local/bin/mysqltuner --color | ansifilter` does not output colour

I'll keep testing until it does.

**Comment by ddarbyson** [comment]
any luck?

**Comment by jmrenouard** [comment]
Hi @ddarbyson 

My last tests:
1° mysqltuner.pl without option => colors are present
2° mysqltuner.pl --nocolor => colors are not present
3° mysqltuner.pl | less => colors are not present
4° mysqltuner.pl --color | less  => colors are present


Moreover, with this test in Html, I retrieve my color in the output.
perl mysqltuner.pl --color | ansifilter -H
... 
-------- Replication Metrics -----------------------------------------------------------------------
[<span style="color:#0000f0;">--</span>] Galera Synchronous replication: NO
[<span style="color:#0000f0;">--</span>] No replication slave(s) for this server.
[<span style="color:#0000f0;">--</span>] This is a standalone server.
 ...
I think I cannot understand what's going wrong :)

**Comment by ddarbyson** [comment]
Hey @jmrenouard 

I tested again, and got exactly the same results as you. Even with ansifilter. 

I think what threw me off in v1.6.18 I was able to run `/usr/local/bin/mysqltuner | ansifilter` and see coloured output... I didn't test `/usr/local/bin/mysqltuner --color | ansifilter -H`.

This does in fact work. Your `--color` options fixes my issue.

Thank you.
