### ISSUE TITLE
mariabackup sst method

### ISSUE THREAD

**Issue by wiza** [major/MySQLTuner-perl#372]
MySQLTuner gives warning:
[!!] Galera SST method is not xtrabackup based.
when wsrep_sst_method=mariabackup

mariabackup is fork of xtrabackup so probably should be counted as xtrabackup based.

**Comment by jmrenouard** [comment]
Tell me if 1.7.6 fix this issue :)

**Comment by wiza** [comment]
Tested with 1.7.7., works, thanks!
