### ISSUE TITLE
Unknown column 'password' in 'where clause'

### ISSUE THREAD

**Issue by fmonts** [major/MySQLTuner-perl#373]
I updated mysqltuner to the latest version and I see a lot of errors in the step where it checks for common passwords.

I'm using Percona Server 5.7.21-20

And example of failing query:
`SELECT CONCAT(user, '@', host) FROM mysql.user WHERE IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD('86') OR IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD(UPPER('86')) OR IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD(CONCAT(UPPER(LEFT('86', 1)), SUBSTRING('86', 2, LENGTH('86'))))`

> [!!] FAIL Execute SQL / return code: 256

The error is `Unknown column 'password' in 'where clause'`

**Comment by Trashtravis** [comment]
Hey fam I had same issue on mysql community version 5.7.21

ISSUE:
It's really silly on line 
`1698:   "IF(plugin='mysql_native_password', authentication_string, password)";
`
Quick fix:
Add quotes to the word password. so the line will be like:
` "IF(plugin='mysql_native_password', authentication_string, password)"; `

Save and run again the script.

**Comment by fmonts** [comment]
Thank you!

**Comment by xXxSPYxXx** [comment]
Thy, its help. Need fix in main branch

**Comment by jmrenouard** [comment]
HI, anybody get some feedback ?

**Comment by Trashtravis** [comment]
Hi @jmrenouard it works fine for me now. 

> Tested

 on mysql community version 5.7.21

Thanks

**Comment by jmrenouard** [comment]
Thanks

**Comment by kavin-90** [comment]
I'm getting same error as OP is getting :/

**Comment by virms77** [comment]
Thanks!
