### ISSUE TITLE
Recommendation: HA_ERR_FOUND_DUPP_KEY crash on slave

### ISSUE THREAD

**Issue by marciofoz** [major/MySQLTuner-perl#374]
Hi!.
I'm using Percona XtraDB Cluster 5.7.19 with 3 nodes. After run MySQLTuner 1.7.7 I see this recommendation:
"Set wsrep_slave_threads to 1 in case of HA_ERR_FOUND_DUPP_KEY crash on slave"
I don't use any slave and all nodes are master/master, I think this message could be displayed only if any slave is configured/in use.
BR.

**Comment by jmrenouard** [comment]
Hi @marciofoz 
I never get this kind of error on my platform.

Can you give us more feedback on this issue ?

**Comment by marciofoz** [comment]
Hi @jmrenouard 
Bellow more informations, feel free to ask anything else.

perl mysqltuner.pl  --verbose
 >  MySQLTuner 1.7.9 - Major Hayden <major@mhtx.net>
....
------- Galera Metrics ----------------------------------------------------------------------------
[--] Galera is enabled.
[--] GCache is using 0B
[OK] wsrep_slave_threads is equal to 2, 3 or 4 times number of CPU(s)
[OK] gcs.fc_limit should be equal to 5 * wsrep_slave_threads
[--] wsrep parallel slave can cause frequent inconsistency crash.
[OK] gcs.fc_limit is equal to 5 * wsrep_slave_threads
[OK] gcs.fc_factor is equal to 0.8
[OK] Flow control fraction seems to be OK (wsrep_flow_control_paused<=0.02)
-------- Replication Metrics -----------------------------------------------------------------------
[--] Galera Synchronous replication: YES
[--] No replication slave(s) for this server.
[--] Binlog format: ROW
[--] XA support enabled: ON
[--] Semi synchronous replication Master: Not Activated
[--] Semi synchronous replication Slave: Not Activated
[--] This is a standalone server
....
Variables to adjust:
    vm.swappiness <= 10 (echo 10 > /proc/sys/vm/swappiness)
    fs.aio-max-nr > 1M (echo 1048576 > /proc/sys/fs/aio-max-nr)
    join_buffer_size (> 256.0K, or always use indexes with joins)
    table_open_cache (> 4096)
    performance_schema = ON enable PFS
    Set wsrep_slave_threads to 1 in case of HA_ERR_FOUND_DUPP_KEY crash on slave

-----------------
MY.CNF file:
[mysqld]
skip-name-resolve = ON
performance_schema = OFF
log_timestamps = SYSTEM
disable-partition-engine-check = ON
explicit_defaults_for_timestamp = 1        
server-id = 1
datadir = /data/mysql
socket = /data/mysql/mysql.sock
log-error = /var/log/mysqld.log
pid-file = /var/run/mysqld/mysqld.pid
symbolic-links = 0
binlog_format = ROW
max-binlog-size = 500M
log_slave_updates = on
expire_logs_days = 1
tmpdir = /var/tmp

tmp-table-size = 64M
max-heap-table-size = 64M
query-cache-type = 0
query-cache-size = 0
max-connections = 250
thread-cache-size = 50
open-files-limit = 65535
table-definition-cache = 1024
table-open-cache = 4096
wait_timeout = 600
interactive_timeout = 600

innodb_autoinc_lock_mode = 2
innodb-flush-method = O_DIRECT
innodb-log-files-in-group = 2
innodb-log-file-size = 512M
innodb-flush-log-at-trx-commit = 0
innodb-file-per-table = 1
innodb-buffer-pool-size = 7G
innodb_track_changed_pages = ON
innodb_buffer_pool_instances = 7
innodb_page_cleaners = 7
thread_handling = pool-of-threads
thread_pool_size = 16
default_storage_engine = InnoDB
max_allowed_packet = 128M
slow_query_log = 1 
slow_query_log_file = /var/log/mysql/slow_query.log
long_query_time = 3 
userstat = 1
[client]
socket=/data/mysql/mysql.sock
!includedir /etc/my.cnf.d/

-----------------
WSREP.CNF file:
log-bin = server2
proxy_protocol_networks = fd00:faca:0:a0::/118
bind_address = fd00:faca:0:a0::92
wsrep_provider= /usr/lib64/galera3/libgalera_smm.so
wsrep_cluster_name = cluster-mysql
wsrep_cluster_address = gcomm://[fd00:faca:0:a0::91],[fd00:faca:0:a0::92],[fd00:faca:0:a0::93]
wsrep_provider_options = "gmcast.listen_addr=tcp://[::]:4567;gcache.size=1G;gcs.fc_factor=0.8;gcs.fc_limit=80"
wsrep_retry_autocommit = 3
wsrep_node_name = server2
wsrep_node_address = [fd00:faca:0:a0::92]
wsrep_sst_method = xtrabackup-v2
wsrep_sst_auth = bkpuser:123
pxc_strict_mode = PERMISSIVE
wsrep_slave_threads = 16
wsrep_log_conflicts
wsrep_notify_cmd = /data/mysql/monitor_sql
[sst]
sockopt = "pf=ip6"
inno-apply-opts = "--use-memory=2G"
progress = 1
time = 1

-----------------
rpm -qa | grep -i percona 
Percona-XtraDB-Cluster-shared-compat-57-5.7.21-29.26.1.el7.x86_64
Percona-XtraDB-Cluster-shared-57-5.7.21-29.26.1.el7.x86_64
Percona-XtraDB-Cluster-server-57-5.7.21-29.26.1.el7.x86_64
Percona-XtraDB-Cluster-client-57-5.7.21-29.26.1.el7.x86_64
Percona-XtraDB-Cluster-57-5.7.21-29.26.1.el7.x86_64
percona-release-0.1-5.noarch
percona-toolkit-3.0.8-1.el7.x86_64
percona-xtrabackup-24-2.4.10-1.el7.x86_64

Centos 7.4

**Comment by 59090939** [comment]
Wsrep_slave_threads=1 disappears this information, running multiple threads from the node, easily causing conflicts

**Comment by jmrenouard** [comment]
I close this issue. thanks to @59090939 for its explanations.

Feel free to reopen it if needed.
