### ISSUE TITLE
MySql stopped unexpectedly after tunning

### ISSUE THREAD

**Issue by macnux** [major/MySQLTuner-perl#382]
Hello
I'm using **MariaDB 10.1** on **CentOS 7** with **4GB RAM** to run a WordPress website.
I'm using the following settings on my.cnf:

```
innodb_buffer_pool_size = 1G
innodb_log_file_size = 128M
innodb_buffer_pool_instances = 1
tmp_table_size= 256M
max_heap_table_size = 256M
query_cache_type = 1
query_cache_limit = 256K
query_cache_min_res_unit = 2k
query_cache_size = 0
query_cache_type = 0
skip-name-resolve
thread_cache_size = 16
local-infile=0
```
Sudenly, Mysql server stopped !! I don't know the reason. 
If the reason is high load due to visitors, how to optimize the above settings to be able to accommodate a high number of visitors?

And these are the red indications shown from the script report:
```
-------- MyISAM Metrics ----------------------------------------------------------------------------
[!!] Key buffer used: 18.2% (24M used / 134M cache)
[!!] Read Key buffer hit rate: 75.0% (4 cached / 1 reads)

-------- InnoDB Metrics ----------------------------------------------------------------------------
[!!] InnoDB Write Log efficiency: 78.7% (425 hits/ 540 total)
```

Any help is appreciated.
Regards,

**Comment by jmrenouard** [comment]
hi @macnux 

Response are located into your error log.

If not try to investigated on out of RAM and OOM Kill issue.

**Comment by jmrenouard** [comment]
No awnser, I close this issue.

Feel free to reopen if needed.
