### ISSUE TITLE
RPMs for Centos 6 and 7

### ISSUE THREAD

**Issue by daniel-lucio** [major/MySQLTuner-perl#384]
If someone cares, I have published the RPM's with all perl dependencies (RPM as well)
http://inside-out.xyz/technology/mysql-tuner-1-7-2-rpm-for-centos-6-7.html

**Comment by jmrenouard** [comment]
Hi @daniel-lucio 

You can build rpm using: build/build_rpm.sh to build an updated RPM.

Help welcome ;)

**Comment by daniel-lucio** [comment]
I know, I just put all in a public repo for everybody

**Comment by jmrenouard** [comment]
Hi @daniel-lucio 
Thanks for your feedback.

What can you do to help you on this topic ?

**Comment by jmrenouard** [comment]
We can deliver a version 1.7.14 release.
