### ISSUE TITLE
MySQLTuner don't understand Thread Pool in Percona Server 5.7

### ISSUE THREAD

**Issue by makhomed** [major/MySQLTuner-perl#386]
MySQLTuner 1.7.9, Percona Server 5.7 (full support).

configuration file ```/etc/percona-server.conf.d/mysqld.cnf```:
```mysql
thread_handling = pool-of-threads
thread_pool_size = 12
max_connections = 256
```

MySQLTuner reports about very high memory usage and 256 threads simultaneously:
```
-------- Performance Metrics -----------------------------------------------------------------------
[--] Physical Memory     : 32.0G
[--] Max MySQL memory    : 84.6G
[--] Other process memory: 468.2M
[--] Total buffers: 16.5G global + 272.2M per thread (256 max threads)
[!!] Maximum possible memory usage: 84.6G (264.36% of installed RAM)
[OK] Highest usage of available connections: 0% (1/256)
```

But this is not true, then ```thread_handling = pool-of-threads``` enabled 
Percona Server can run maximum 12 threads simultaneously. More details:
https://www.percona.com/doc/percona-server/LATEST/performance/threadpool.html#thread-pool
https://www.percona.com/forums/questions-discussions/mysql-and-percona-server/43960-max_connections-and-thread-pooling

P.S. 

```
-------- ThreadPool Metrics ------------------------------------------------------------------------
[--] ThreadPool stat is enabled.
[--] Thread Pool Size: 12 thread(s).
[!!] thread_pool_size between 16 and 36 when using InnoDB storage engine.
```

Also strange recommendation to have thread_pool_size between 16 and 36 when using InnoDB storage engine - server have only 6 physical cores and only 12 threads (with HT) can run simultaneously. 

If I change thread_pool_size from 12 to 16 or 36 - it does not help to improve mysql performance.

**Comment by jmrenouard** [comment]
Hi @makhomed 

Thanks for your feedback.

Pull Requests welcome :)

**Comment by jmrenouard** [comment]
Can we close this issue ?

**Comment by makhomed** [comment]
> Can we close this issue ?

I try latest stable version, MySQLTuner 1.7.12,
This bug is not fixed yet, and still exists in MySQLTuner.

Percona Server config fragment:

```
max_connections=2048
thread_handling=pool-of-threads
thread_pool_size=16
```
MySQLTuner output fragment:

```
[--] Physical Memory     : 110.2G
[--] Max MySQL memory    : 577.0G
[--] Total buffers: 32.5G global + 272.2M per thread (2048 max threads)
[!!] Maximum possible memory usage: 577.0G (523.77% of installed RAM)
[!!] Overall possible memory usage with other process exceeded memory
```
MySQLTuner reports about very high memory usage and 2048 threads simultaneously.

But this is not true, then ```thread_handling=pool-of-threads``` enabled
Percona Server can run maximum ```thread_pool_size=16``` threads simultaneously.

**Comment by makhomed** [comment]
> do you get some times to investigate on this aspect 
> and share some rules of calculation for this thread-pool related to different value ?

I investigate this aspect and found what current MySQLTuner 
rule for ```Maximum possible memory usage``` is correct, sorry.

But I found two other bugs in MySQLTuner related to ```thread_handling=pool-of-threads``` mode:

1. Currently MySQLTuner can't detect ```thread_handling=pool-of-threads``` mode
because check for 'pools-of-threads'  value, not for 'pool-of-threads'. 

2. Currently MySQLTuner do useless recommendations about ```thread_cache_size```
when ```thread_handling=pool-of-threads``` mode - in this mode 
value of ```thread_cache_size``` variable is ignored by server.

I write patch to fix these two bugs:

```diff
--- mysqltuner.pl-orig  2018-09-25 18:24:48.643939499 +0300
+++ mysqltuner.pl       2018-09-26 00:31:17.647049996 +0300
@@ -3070,16 +3070,19 @@
     }

     # Thread cache
-    if ( $myvar{'thread_cache_size'} eq 0 ) {
-        badprint "Thread cache is disabled";
-        push( @generalrec, "Set thread_cache_size to 4 as a starting value" );
-        push( @adjvars,    "thread_cache_size (start at 4)" );
+    if ( defined( $myvar{'thread_handling'} )
+        and $myvar{'thread_handling'} eq 'pool-of-threads' )
+    {
+        # https://www.percona.com/doc/percona-server/LATEST/performance/threadpool.html
+        # When thread pool is enabled, the value of the thread_cache_size variable
+        # is ignored. The Threads_cached status variable contains 0 in this case.
+        infoprint "Thread cache not used with thread_handling=pool-of-threads";
     }
     else {
-        if ( defined( $myvar{'thread_handling'} )
-            and $myvar{'thread_handling'} eq 'pools-of-threads' )
-        {
-            infoprint "Thread cache hit rate: not used with pool-of-threads";
+        if ( $myvar{'thread_cache_size'} eq 0 ) {
+            badprint "Thread cache is disabled";
+            push( @generalrec, "Set thread_cache_size to 4 as a starting value" );
+            push( @adjvars,    "thread_cache_size (start at 4)" );
         }
         else {
             if ( $mycalc{'thread_cache_hit_rate'} <= 50 ) {
```

**Comment by jmrenouard** [comment]
Hi @makhomed 

Can you give us your feedback ?

Our patch has be applied in the code.

**Comment by makhomed** [comment]
> Can you give us your feedback ?
> Our patch has be applied in the code.

Work as expected, but have two style drawbacks:

1. Big fragment of commented code in lines 3073-3083.
2. Wrong indentation of lines 3092, 3093, 3098.

I prepare patch, which fixes all these style drawbacks:

```diff
--- mysqltuner.pl-orig  2018-09-26 11:32:35.442454649 +0300
+++ mysqltuner.pl       2018-09-26 11:34:48.397660288 +0300
@@ -3070,18 +3070,6 @@
     }

     # Thread cache
-#    if ( $myvar{'thread_cache_size'} eq 0 ) {
-#        badprint "Thread cache is disabled";
-#        push( @generalrec, "Set thread_cache_size to 4 as a starting value" );
-#        push( @adjvars,    "thread_cache_size (start at 4)" );
-#    }
-#    else {
-#        if ( defined( $myvar{'thread_handling'} )
-#            and $myvar{'thread_handling'} eq 'pools-of-threads' )
-#        {
-#            infoprint "Thread cache hit rate: not used with pool-of-threads";
-#        }
-
     if ( defined( $myvar{'thread_handling'} )
         and $myvar{'thread_handling'} eq 'pool-of-threads' )
     {
@@ -3089,13 +3077,13 @@
         # When thread pool is enabled, the value of the thread_cache_size variable
         # is ignored. The Threads_cached status variable contains 0 in this case.
         infoprint "Thread cache not used with thread_handling=pool-of-threads";
-     }
-     else {
+    }
+    else {
         if ( $myvar{'thread_cache_size'} eq 0 ) {
             badprint "Thread cache is disabled";
             push( @generalrec, "Set thread_cache_size to 4 as a starting value" );
             push( @adjvars,    "thread_cache_size (start at 4)" );
-         }
+        }
         else {
             if ( $mycalc{'thread_cache_hit_rate'} <= 50 ) {
                 badprint
```
