### ISSUE TITLE
Incorrectly assumes 32bit architecture on s390x systems

### ISSUE THREAD

**Issue by ariabamdad** [major/MySQLTuner-perl#390]
Running on s390x architecture (IBM z Systems), mysqltuner incorrectly assumes we are not running on a 64 bit system based on the series of if statements in the relevant section of the code.   

When running on s390x architecture and SUSE SLES 12
uname returns :  Linux
uname -m returns:  s390x
uname -a returns:  Linux servername 4.4.103-6.33-default #1 SMP Wed Dec 13 13:25:31 UTC 2017 (e430cfc) s390x s390x s390x GNU/Linux

Thank you.

**Comment by ariabamdad** [comment]
Hi @jmrenouard 

There are very few distributions that still support 32 bit architecture on this platform.  The 32 bit arch would/should return just s390 (without the x at the end).  This is how the Linux distributions are identified with respect to 32 or 64 bit.   So, s390 for 32 bit and s390x for 64 bit.  However, I do not have access to a 32 bit distribution that will run on my new hardware so I cannot be 100% sure.

Thanks

**Comment by jmrenouard** [comment]
in check_architecture
elsif ( `uname` !~ /SunOS/ && `uname -m` =~ /64/ && `uname -m` !~ /s390x/ ) {
        $arch = 64;
        goodprint "Operating on 64-bit architecture";
    }
Allow us to detect that s390x in not a 64 bits archi.

**Comment by jmrenouard** [comment]
Hi @ariabamdad 

This is fixed in last commit.

**Comment by jmrenouard** [comment]
Can you tell me if it's better now ?

**Comment by ariabamdad** [comment]
Hi @jmrenouard ,

I confirm this is fixed!

Thank you.
