### ISSUE TITLE
Peak and max memory usage estimated incorrectly

### ISSUE THREAD

**Issue by Am1GO** [major/MySQLTuner-perl#393]
https://github.com/major/MySQLTuner-perl/blob/2f9fc715b14aba8caee21e49c8a7cf0a91d02236/mysqltuner.pl#L2351
https://github.com/major/MySQLTuner-perl/blob/2f9fc715b14aba8caee21e49c8a7cf0a91d02236/mysqltuner.pl#L2361
`get_gcache_memory()` should not be added to the memory usage estimations because `gcache.size` is not in-memory but on-disk RingBuffer file size.

**Comment by jmrenouard** [comment]
Can you give us some feedback ?

**Comment by Am1GO** [comment]
What kind of feedback do you expect?

**Comment by jmrenouard** [comment]
Hi @Am1GO 

Can you tell me, if using last version, you get the proer result you expect.

I apply your recommandations.

**Comment by Am1GO** [comment]
Ah, I didn't notice e7980611a10eec3511b6f5c8ea292da08e0777ab.
Now memory usage estimation works properly, thank you!
