### ISSUE TITLE
Travis-Ci: Following test are incorrect

### ISSUE THREAD

**Issue by jmrenouard** [major/MySQLTuner-perl#401]
Hi,

In .travis.yml, following databse are not set properly for unknow reasons:
MariaDB 5.5/MySQL 5.5/MySQL 5.7 and MYSQL 8.0 tests install MySQL 5.6 instead awiated version.

MariaDB 10.0/10.1/10.3 and MySQL 5.6 tests are OK
All Percona Version are not included actually for same reason.

**Comment by tholu** [comment]
The Travis builds seem to be canceled/broken completely. What's the current status of this?

**Comment by grooverdan** [comment]
fixed per #541 #543
