### ISSUE TITLE
Tagging versions

### ISSUE THREAD

**Issue by weberhofer** [major/MySQLTuner-perl#405]
Thank you for this great script which I'm using quite frequently!

I'm also packaging the software for the openSUSE and would like to ask you for tagging releases, which simplifies the creation of reproduceable builds of our RPM packages.

**Comment by jmrenouard** [comment]
Hi @weberhofer 

Can you help us to improve building script in build sub directory ?

I will fix one or two issues and tag your new version !

**Comment by jmrenouard** [comment]
Yes nice idea :)

**Comment by jmrenouard** [comment]
I will publish a new release for each increment of version.

I close this ticket and process changes like this.

**Comment by weberhofer** [comment]
@jmrenouard, sorry for not responding for such a long while! Thanks a lot for changing your release process, I'll update the openSUSE repos soon.

**Comment by dvershinin** [comment]
@jmrenouard this was missed for 1.7.15:

* Last GitHub release is 1.7.13
* The version delivered via mysqltuner.pl is 1.7.15

**Comment by weberhofer** [comment]
Yes, please tag!

**Comment by jmrenouard** [comment]
Done
