### ISSUE TITLE
MySQLtuner extremely slow

### ISSUE THREAD

**Issue by raxon1s** [major/MySQLTuner-perl#406]
Mysqltuner does lot of time to complete. More than 3-4 hours. Tested in 3-4 different machines.

The problem is in the function get_other_process_memory()
if i add return 0; then it completes fast. 

Any idea?

**Comment by jmrenouard** [comment]
Hi @raxon1s 

Can you tell us more ?
OS version, MySQL version ?

Do you get some debug info ?

**Comment by XtreamCodes** [comment]
OS is UBUNTU 14.04 64bit
Mariadb 10.x ( tested all, and does the same )

when i run with debug enabled, it still stucks without getting any useful information.

**Comment by jmrenouard** [comment]
Hi, 

I close this issue.

In 1.7.14 a new option --noprocess is available. Disabling process calculations.

Best regards,
