### ISSUE TITLE
Error 256 when connecting through the port 3306 to the MariaDB

### ISSUE THREAD

**Issue by januzi** [major/MySQLTuner-perl#407]
There are some major problems that I can't fix by myself. Basically, everything is working ok when the mysql (mariadb is the same thing, right?) is running on socket, but when it's attached to the 127.0.0.1, then the hell breaks loose.

1. Every account, even root one, fails with the "return code 256" 
2. As soon as I run phpmyadmin, after I ran mysqltuner, I get 100% cpu usage (with messages like "too may open files" in the mysql_error.log).
3. I've tried mysqltuner without [client] settings, with just everything typed as command arguments and it didn't help at all (even --socket)
4. --verbose says that the queries are all f*** up, like "SHOW TABLE STATUS FROM slash`mysql`slash"

Ctrl+C or waiting for mysqltuner to end it's calculation doesn't change anything, mysql will still brag about open files limit (even with the 10k set up with the ulimit).

**Comment by jmrenouard** [comment]
Hi @januzi 

Do you try to connect manually using mysql in command line  ?

If this method works mysqltuner will works because mysqltuner is based on mysql client utility.

**Comment by jmrenouard** [comment]
From https://github.com/major/MySQLTuner-perl/blob/master/USAGE.md

CONNECTION AND AUTHENTICATION
--host <hostname>           Connect to a remote host to perform tests (default: localhost)
--socket <socket>           Use a different socket for a local connection
--port <port>               Port to use for connection (default: 3306)
--user <username>           Username to use for authentication
--userenv <envvar>          Name of env variable which contains username to use for authentication
--pass <password>           Password to use for authentication
--passenv <envvar>          Name of env variable which contains password to use for authentication
--ssl-ca <path>             Path to public key
--mysqladmin <path>         Path to a custom mysqladmin executable
--mysqlcmd <path>           Path to a custom mysql executable
--defaults-file <path>      Path to a custom .my.cnf

**Comment by jmrenouard** [comment]
Don't hesitate to share more details remated to this connection issue if you get strange behaviour.
