### ISSUE TITLE
About innodb_log_file_size changing recommendation

### ISSUE THREAD

**Issue by acs-ferreira** [major/MySQLTuner-perl#408]
Actually:

> Before changing innodb_log_file_size and/or innodb_log_files_in_group read this: http://bit.ly/2wgkDvS

First of ,all, the link does not exists.

Second, it differs from 5.6 to 5.7/8.

See:
https://dev.mysql.com/doc/refman/5.6/en/innodb-redo-log.html (5.6)
https://dev.mysql.com/doc/refman/8.0/en/innodb-redo-log.html (5.7/8)

IMO, the link should point to the current (8) version.

Regards.

**Comment by matthewlenz** [comment]
With 5.5 this recommendation:

innodb_log_file_size should be (=2G) if possible, so InnoDB total log files size equals to 25% of buffer pool size.

Will result in the server not being able to start. Max combined innodb_log_file_size for <= 5.6.2 should have a ceiling of (4096MB / log files in group) - 1MB.

**Comment by jmrenouard** [comment]
@matthewlenz 
Your comment is taken into account.
When MySQL 5.6.2 and lower is detected:
            "For MySQL 5.6.2 and lower, max combined innodb_log_file_size should have a ceiling of (4096MB / log files in group) - 1MB.");
