### ISSUE TITLE
Missing password is not recognized

### ISSUE THREAD

**Issue by danielmarschall** [major/MySQLTuner-perl#412]
I have the latest version 1.7.13 running on Maria DB 10.1.26-MariaDB-0+deb9u1 .
I noticed that it did not recognize that I have a user which has no password set.
The reason is that the following line of code presents a string "password" rather than the field "password". So the later checks `is null` and `= ''` always succeed.

Here is a fix that works for me:

Find:
`"IF(plugin='mysql_native_password', authentication_string, 'password')";`

Replace with:
`"IF(plugin='mysql_native_password', authentication_string, password)";`

**Comment by plutocrat** [comment]
Didn't work for me. Edited line 1726 to remove the '' around password and still got the same error. 
As far as I can gather, if plugin is set to mysql_native_password, then it should only be looking in the Password field. 

I fiddled around with things and this seemed to work:

`    if ( $myvar{'version'} =~ /5\.7|10\..*MariaDB*/ ) {
        $PASS_COLUMN_NAME = "IF(plugin='mysql_native_password', 'authentication_string', 'Password')";
    }
`

**Comment by StKox** [comment]
Still open in 1.7.14. I can confirm daniels post. Removing the two apostrophes surrounding 'password' is working well.

**Comment by jmrenouard** [comment]
Modifications made

**Comment by tholu** [comment]
This change breaks the fix for #373 (ff2a47e4618326ede36ca8553981ac7c66ad36f), see also #427.

**Comment by jmrenouard** [comment]
Tested and improved on last version.
Don't face any issue with last version.

**Comment by jmrenouard** [comment]
It's ok for me now.
