### ISSUE TITLE
innodb_log_file_size as variables to adjust, but already exists with this value

### ISSUE THREAD

**Issue by Daijobou** [major/MySQLTuner-perl#417]
MySQLTuner 1.7.14 / 10.1.37-MariaDB

Hello, I get every time this line in "Variables to adjust":
`innodb_log_file_size should be (=1G) if possible, so InnoDB total log files size equals to 25% of buffer pool size.`

but its alreay set in config
`innodb_log_file_size = 1G`

Other variables change recommendation, when I update config, but this line always appear. My mistake or a bug?

**Comment by jmrenouard** [comment]
Maybe a bug

**Comment by acs-ferreira** [comment]
What is the value of `innodb_log_files_in_group`?
If not `1`, that message is normal.

**Comment by Daijobou** [comment]
innodb_log_files_in_group is not set and default 2 (source: https://mariadb.com/kb/en/library/innodb-system-variables/#innodb_log_files_in_group)

My setting is
```
innodb_buffer_pool_size = 12G
innodb_buffer_pool_instances = 12
innodb_log_file_size = 1G
```

**Comment by jmrenouard** [comment]
Hi @Daijobou 
innodb_log_files_in_group differs from innodb_buffer_pool_instances.

If you want to be ok with MT just put innodb_buffer_pool_instances innodb_log_files_in_group = 2

**Comment by jmrenouard** [comment]
https://mariadb.com/kb/en/library/innodb-system-variables/#innodb_log_files_in_group
default value: 2
innodb_buffer_pool_instances  differs from innodb_log_files_in_group 

Your setting is 
innodb_buffer_pool_instances = 12
not 
innodb_log_files_in_group =12

**Comment by Daijobou** [comment]
@jmrenouard 
Sorry, I have missed the answer. With this settings
```
innodb_buffer_pool_size = 12G
innodb_buffer_pool_instances = 12
innodb_log_files_in_group = 2
innodb_log_file_size = 1G
```

I still get this warning
> innodb_log_file_size should be (=1G) if possible, so InnoDB total log files size equals to 25% of buffer pool size.

Server-Version: 10.3.17 with 128 GB RAM.

**Comment by Raphael67** [comment]
Just to be sure can you do `SHOW VARIABLES LIKE "innodb_log_file_size";` while the server is running.

**Comment by Daijobou** [comment]
```
MariaDB [(none)]> SHOW VARIABLES LIKE "innodb_log_file_size";
+----------------------+------------+
| Variable_name        | Value      |
+----------------------+------------+
| innodb_log_file_size | 1073741824 |
+----------------------+------------+
1 row in set (0.000 sec)

```

**Comment by Raphael67** [comment]
The problem is that MT round the value of `innodb_buffer_pool_size / innodb_log_files_in_group / 4` to the nearest integer with a call to the function `hr_bytes_rnd`. 
So the result `1.5` become `1`.

Using the function `hr_bytes` instead will print:
`innodb_log_file_size should be (=1.5G) if possible, so InnoDB total log files size equals to 25% of buffer pool size.`
Which make more sens to me.
