### ISSUE TITLE
Wrong value about innodb_buffer_pool_instances with MySQL 5.6

### ISSUE THREAD

**Issue by stonio** [major/MySQLTuner-perl#419]
Wrong information about **innodb_buffer_pool_instances** using MySQL 5.6:

```
-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[--] InnoDB Buffers
[--]  +-- InnoDB Buffer Pool: 128.0M
[--]  +-- InnoDB Buffer Pool Instances: 8
[--]  +-- InnoDB Additional Mem Pool: 8.0M



Variables to adjust:
    innodb_buffer_pool_instances (=1)
```

However, this variable is already set to default value 1.
If you read note in [MySQL 5.6 Reference Manual](https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_buffer_pool_instances):
> A bug in MySQL 5.6 causes SHOW VARIABLES to report an innodb_buffer_pool_instances value of 8 when innodb_buffer_pool_size is less than 1GB and only one buffer pool instance is present (Bug #18343670).

**Comment by jmrenouard** [comment]
INTERNALS.md updated with related information.

**Comment by jmrenouard** [comment]
Thanks for your feedback :)
