### ISSUE TITLE
Illegal division by zero

### ISSUE THREAD

**Issue by vesatoivonen** [major/MySQLTuner-perl#423]
Running freshly cloned repo and mariadb 10.3.12

```
 Illegal division by zero at mysqltuner.pl line 2573 (#1)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.
    
Uncaught exception from user code:
    Illegal division by zero at mysqltuner.pl line 2573.
    main::calculations() called at mysqltuner.pl line 6307
```

**Comment by jmrenouard** [comment]
Hi @vesatoivonen 

Do you restart your server just before running mysqltuner ?

This expression $mystat{'Uptime'}  returns 0.

So, this means that you don't let mariaDb run during enougth time in order to get accurated information.

**Comment by jmrenouard** [comment]
Adding a test for uptime = 0 and set up uptime to 1 sec. at least

**Comment by vesatoivonen** [comment]
Actually, yes.
I have since lost the command chain used, but it was something like `sudo systemctl restart mysql.service && perl mysqltuner.pl`

**Comment by jmrenouard** [comment]
You should wait at least a complete day to see useful information in your status.

**Comment by vesatoivonen** [comment]
OK, thanks a lot!
