### ISSUE TITLE
Do not redistribute the script without TLS

### ISSUE THREAD

**Issue by mablae** [major/MySQLTuner-perl#424]

**Comment by jmrenouard** [comment]
Hi @mablae 

Can you tell me more ?

 Thanks by advance,

**Comment by mablae** [comment]
I just saw the http Link in readme. Was not aware of that redirect to https

**Comment by mowny** [comment]
> I just saw the http Link in readme. Was not aware of that redirect to https

Interception can still happen _before_ the redirect.
