### ISSUE TITLE
Can't use command line after MySQLTuner

### ISSUE THREAD

**Issue by MalikKrak** [major/MySQLTuner-perl#425]
Hi

after I used MySQLTuner I can not use command line, for example I need change password of user, how to do that? DB is MariaDB 10.1.37

thanks

> $ sudo mysql
> mysql: unknown variable 'query_cache_size=0'
> $ sudo mariadb
> mysql: unknown variable 'query_cache_size=0'

**Comment by jmrenouard** [comment]
Modifications made are not placed in the right section.
query_cache_size placed in client or mysql section instead of server or mysqld section

**Comment by MalikKrak** [comment]
So it is a bug in the MySQLTuner script ?

**Comment by jmrenouard** [comment]
No, it's a configuration section issue in your configuration file.

**Comment by MalikKrak** [comment]
But CLI commands was working before I used this script.

**Comment by MalikKrak** [comment]
because the error is
```
sudo mysql -u root -p
mysql: unknown variable 'query_cache_type=0'
```
and here is the part from mariadb.conf
```
# mysqltuner.pl
query_cache_type = 0
query_cache_size = 0
performance_schema = ON
innodb_log_file_size = 16M
innodb_buffer_pool_instances = 1
```

**Comment by acs-ferreira** [comment]
The script does not write anything to your server, it only reads and recommends. Period. The changes are up to you and you should apply them **ONLY** if you know what you are doing.

See also https://github.com/major/MySQLTuner-perl#warning
