### ISSUE TITLE
Installed Sysschema with 'admin' account

### ISSUE THREAD

**Issue by diplatis** [major/MySQLTuner-perl#426]
Hi,

I installed the schema following the instrunctions on a MariaDB 10.1 server installed with Plesk which doesn't have a 'root' account rather than 'admin' account and after that I saw in the sql files that there is
`DEFINER = 'root'@'localhost'`

Is this a problem? What should I do?

**Comment by jmrenouard** [comment]
Hi @diplatis 
Maybe you should try to change it with admin.

Best regards,

**Comment by jmrenouard** [comment]
use --user option to solve this issue.
