### ISSUE TITLE
Update version command

### ISSUE THREAD

**Issue by Sn4kY** [major/MySQLTuner-perl#428]
Hi.

The updateversion seems not design to do only an update to the new version (if available).
Is it possible to add or modify this option to do just an update ?
I've using this option to update the script on all my servers, when I upgrade the system packages (aptitude upgrade), but don't be interrested to run an check at the same time.

best regards.
Pierre.

**Comment by jmrenouard** [comment]
Hi @Sn4kY 

Can you give us more technical details in the way you want to use it ?

Thanks

**Comment by Sn4kY** [comment]
Hi.
Maybe an --updateversion-only to do only an update, without doing any other checks ?

Many thanks.

**Comment by jmrenouard** [comment]
Hi @Sn4kY 
perl --checkversion --updateversion cause MySQLtuner stopping after update.
