### ISSUE TITLE
Add recommendation on table_definition_cache

### ISSUE THREAD

**Issue by acs-ferreira** [major/MySQLTuner-perl#433]
See https://www.fromdual.com/node/1305

I believe that in a rule of thumb, we should count tables and recommend to have the first prime number after it.

**Comment by ChrisSchwerdt** [comment]
It looks like there's an issue here where you accidentally typed `$$nbtables` instead of `$nbtables`: https://github.com/major/MySQLTuner-perl/commit/143b80b3a6d6a13f7d0a5f271b4e59ffbf223b7e#diff-2cc6ed630854d08fdcfd8c17c70d25efR3249. This is causing an error:

```
Uncaught exception from user code:
	Can't use string ("2254") as a SCALAR ref while "strict refs" in use at mysqltuner.pl line 3250.
	main::mysql_stats() called at mysqltuner.pl line 6377
```
