### ISSUE TITLE
Add note about join_buffer_size

### ISSUE THREAD

**Issue by acs-ferreira** [major/MySQLTuner-perl#434]
As the script keeps recommending to increase `join_buffer_size` until JOINs not using indexes are found and increasing too much that value not only does not solve tables not using indexes problems, i believe a note should be added at the bottom stating that:

> Note! We will suggest raising the 'join_buffer_size' until JOINs not using indexes are found. See https://dev.mysql.com/doc/internals/en/join-buffer-size.html (specially the conclusions at the bottom of the page).

Or something like this.

**Comment by downhiller** [comment]
This needs revisiting, as that is now a dead link.  Since I didn't visit it before it died, I'm not sure what it should be now.  Is it just https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_join_buffer_size ?
