### ISSUE TITLE
Generating .html reports

### ISSUE THREAD

**Issue by Steve8291** [major/MySQLTuner-perl#448]
Any chance you could give an example of how to generate an .html report from the command line? Looks like this should be possible but I just can't figure out how to make it work.
Thanks.

**Comment by jmrenouard** [comment]
Hi @Steve8291 

Yes it's possible to do that :)

Let me document it in README page.

**Comment by Steve8291** [comment]
I didn't see anything in the new README. Did you decide not to do this? I've been trying with the following command but it doesn't seem to output useful .html
`perl mysqltuner.pl --silent --reportfile /tmp/result_mysqltuner.txt --template=/mysqltuner_dir/template_example.tpl`

**Comment by jmrenouard** [comment]
I will document this part before closing it :) You are right

**Comment by jmrenouard** [comment]
Usage is documented in USAGE section.

Not documentation regarding template development.

**Comment by jmrenouard** [comment]
A basic example based on python j2

perl mysqltuner.pl --verbose --json | j2 -f json MySQLTuner-perl/templates/basic.html.j2 > variables.html

**Comment by jmrenouard** [comment]
Update documentation needed

**Comment by Steve8291** [comment]
Thanks @jmrenouard 
I have actually been using the `aha` package to output .html
It works very nicely and gives me colored output.
Here is what I run:
```
mysqltuner.pl --color > "$mysqltuner_output"
aha --black --title "MySQLTuner" -f "$mysqltuner_output" > "$html_file"
```
The `aha --black` option outputs black background with white text. Colors from mysqltuner.pl are retained.
Might be worth mentioning `aha` in the docs because it's also a really simple solution.
Here is a one liner:
`perl mysqltuner.pl --color | aha --black --title "MySQLTuner" > mysqltuner.htm`

**Comment by jmrenouard** [comment]
Thanks @Steve8291 

README updated with aha information

Works fine for me 

Closing this issue
