### ISSUE TITLE
Wrong report of  InnoDB Storage engine status

### ISSUE THREAD

**Issue by schemacs** [major/MySQLTuner-perl#450]
if run with `--skipsize`, the report says:
```
[!!] InnoDB Storage engine is disabled. InnoDB is the default storage engine
```
for `enginestats` is not collected at 

https://github.com/major/MySQLTuner-perl/blob/ece567129290ac08d2fb85c2f359b1a9f72359fd/mysqltuner.pl#L5491

so this wrong warning is the side effect of `--skipsize`?

**Comment by jmrenouard** [comment]
Now message is
-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] Skipped due to --skipsize option
