### ISSUE TITLE
Issue importing sys_10.sql

### ISSUE THREAD

**Issue by zeki893** [major/MySQLTuner-perl#452]
>ERROR at line 21: Failed to open file './tables/sys_config_data_10.sql   -- ported', error: 2

There seems to be  a lot of lines with -- comments at the end that are breaking the import. 
What am I supposed to do with them? 

> SOURCE ./tables/sys_config_data_10.sql   -- ported
SOURCE ./functions/format_path.sql   -- not possible to port b/c P_S is too old
SOURCE ./functions/ps_is_account_enabled.sql   -- not possible to port b/c P_S is too old
SOURCE ./views/p_s/ps_check_lost_instrumentation.sql   -- not possible to port b/c P_S is too old
SOURCE ./views/p_s/processlist.sql   -- See also further down!
SOURCE ./views/p_s/x_processlist.sql   -- See also further down!
SOURCE ./views/p_s/sessions.sql   -- See also further down!
SOURCE ./views/p_s/x_sessions.sql   -- See also further down!
SOURCE ./views/p_s/user_summary.sql   -- to port! Error which I do not understand
SOURCE ./views/p_s/x_user_summary.sql   -- to port! Error which I do not understand
SOURCE ./views/p_s/host_summary.sql   -- to port! Error which I do not understand
SOURCE ./views/p_s/x_host_summary.sql   -- to port! Error which I do not understand
SOURCE ./views/p_s/metrics_56.sql   -- not possible to port b/c P_S is too old
SOURCE ./procedures/ps_trace_thread.sql   -- to port!
SOURCE ./procedures/ps_setup_reset_to_default.sql   -- differrent, to port!

**Comment by ericx** [comment]
I had the same problem.
mariadb version:
mysql  Ver 15.1 Distrib 10.1.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

I stripped all the end-of-line comments and it ran fine.

**Comment by jmrenouard** [comment]
Solution given into README.md

**Comment by hrvoj3e** [comment]
Sorry for commenting on a closed issue. 

Another solution is to add semicolon on those lines.
E.g. using vim and global replace
```
:%s/.sql   -- /.sql;   -- /g
```
Or just add semicolons on all commands:
```
:%s/.sql/.sql;/g
```

Line 
```
SOURCE ./tables/sys_config_data_10.sql   -- ported
```
becomes
```
SOURCE ./tables/sys_config_data_10.sql;   -- ported
                  ----- semicolon ----^ 
```

**Comment by TrapoSAMA** [comment]
hi! error in mariadb10.3  with comment -- ported and other
