### ISSUE TITLE
Cannot calculate MyISAM index size - re-run script as root user

### ISSUE THREAD

**Issue by acs-ferreira** [major/MySQLTuner-perl#453]
Script has been run as root user (both OS and MySQL).

`[!!] Cannot calculate MyISAM index size - re-run script as root user`

- 8.0.17 MySQL Community Server
- Ubuntu 18.04
- MySQLTuner 1.7.15

**Comment by jmrenouard** [comment]
New message is:
MyISAM Metrics are disabled on last MySQL versions. for MySQL 8.0

 On MySQL oracle too few information to perform calculations

mysql> show global status like 'myis%';
Empty set (0.00 sec)

mysql> show global variables like 'myis%';
+---------------------------+----------------------+
| Variable_name             | Value                |
+---------------------------+----------------------+
| myisam_data_pointer_size  | 6                    |
| myisam_max_sort_file_size | 9223372036853727232  |
| myisam_mmap_size          | 18446744073709551615 |
| myisam_recover_options    | OFF                  |
| myisam_repair_threads     | 1                    |
| myisam_sort_buffer_size   | 8388608              |
| myisam_stats_method       | nulls_unequal        |
| myisam_use_mmap           | OFF                  |
+---------------------------+----------------------+
8 rows in set (0.00 sec)

**Comment by jmrenouard** [comment]
Last version 1.7.16 should fix this issue.

**Comment by downhiller** [comment]
I still get this error message on 1.7.20
