### ISSUE TITLE
question not an issue...

### ISSUE THREAD

**Issue by edwardsmarkf** [major/MySQLTuner-perl#458]
first off, totally AWESOME concept you have going here.  thank you so much for providing it.

is there any sort of paid service where we can submit the results & get back specific suggestions on what to include/change in my.cnf for a Mariadb 10.2.27 installation?

**Comment by jmrenouard** [comment]
Hi @edwardsmarkf 

You can adress me your needs if you like.
The only point is that I'm based in France and can only work remotly.

Best regards,
jmrenouard@gmail.com

**Comment by jmrenouard** [comment]
Hi @edwardsmarkf 

You can also address your needs to MariaDB corporate (main editor of MariaDB server).

BR,

**Comment by edwardsmarkf** [comment]
hello - there is no problem with you in France, so long as you understand that i completely approve of your president's wife Brigette. 😁     

i am a programmer and never really got to deep into db tuning, hence the need.

here is what i am seeing:

[!!] /var/log/mariadb.err.log contains 1 warning(s).
[!!] Query cache may be disabled by default due to mutex contention.
[!!] Query cache efficiency: 0.0% (0 cached / 1 selects)
[!!] Key buffer used: 18.2% (24M used / 134M cache)
[!!] InnoDB buffer pool / data size: 512.0M/576.5M
[!!] InnoDB Read buffer efficiency: 23.03% (2562 hits/ 11127 total)
[!!] InnoDB Write Log efficiency: 0% (2 hits/ 0 total)

and here is my.cnf

[mysqld]
sql_mode=NO_ENGINE_SUBSTITUTION
innodb_log_file_size = 64M              # 2019-10-14
max_allowed_packet = 64M                #   2019-10-14
skip-name-resolve                       ## 2019-10-16
innodb_buffer_pool_size = 512M
table_definition_cache = 1000000        # 2019-10-14 - changed from 400 (default)
skip-networking=0
#skip-networking=1
## added 2019-05-09
plugin_load_add = server_audit
log_error=/var/log/mariadb.err.log      ## added 2019-06-13


Server version: 10.2.27-MariaDB MariaDB Server

**Comment by jmrenouard** [comment]
Hi @edwardsmarkf , 

Can you  send us exact needs on my mail box ?

I think a Github issue is not real good place to talk about that.

Thanks by advance,
Jean-Marie

**Comment by edwardsmarkf** [comment]
hi - i sent to your email -- hopefully, you received it.

**Comment by edwardsmarkf** [comment]
hi - i have sent you a couple of emails - did you receive them?
