### ISSUE TITLE
Please add support for --protocol=TCP

### ISSUE THREAD

**Issue by rnav1234** [major/MySQLTuner-perl#474]
Some MySQL installations do not have socket files available for those **--protocol=TCP** is required. There seems to be no way to coax mysqltuner.pl into connecting in that case. 
Workaround: With suitable permissions adding a socket file and then specifying --socket=/path/to/sock seems to work nicely.

**Comment by SamAdum** [comment]
temporarily, you can edit mysqltuner.pl and replace this line (+/- l756) : 
`        $remotestring = " -h $opt{host} -P $opt{port} ";`
with
`        $remotestring = " -h $opt{host} -P $opt{port}  --protocol=tcp";`

I'll try to do a PR

**Comment by jmrenouard** [comment]
Done !

**Comment by gggeek** [comment]
FWIW, using an IP address instead of hostname always worked for me to force the mysql client to use TCP instead of pipes...
