### ISSUE TITLE
Error "Can't use string ("3423") as a SCALAR ref while "strict refs" in use at /root/mysqltuner.pl line 3249."

### ISSUE THREAD

**Issue by BrunnoPrego** [major/MySQLTuner-perl#477]
I am getting this error when executing the mysqltuner:

 >>  MySQLTuner 1.7.19 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[OK] Logged in using credentials passed on the command line
[OK] Currently running supported MySQL version 10.3.21-MariaDB-log
[OK] Operating on 64-bit architecture

-------- Log file Recommendations ------------------------------------------------------------------
[OK] Log file /var/lib/mysql/ve0216a.prego.net.br.err exists
[--] Log file: /var/lib/mysql/ve0216a.prego.net.br.err(6M)
[OK] Log file /var/lib/mysql/ve0216a.prego.net.br.err is readable.
[OK] Log file /var/lib/mysql/ve0216a.prego.net.br.err is not empty
[OK] Log file /var/lib/mysql/ve0216a.prego.net.br.err is smaller than 32 Mb
[!!] /var/lib/mysql/ve0216a.prego.net.br.err contains 28843 warning(s).
[!!] /var/lib/mysql/ve0216a.prego.net.br.err contains 578 error(s).
[--] 19 start(s) detected in /var/lib/mysql/ve0216a.prego.net.br.err
[--] 1) 2020-01-31 22:44:24 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 2) 2020-01-31 22:38:18 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 3) 2020-01-31 22:15:01 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 4) 2019-12-13 10:21:46 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 5) 2019-12-07  0:53:35 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 6) 2019-11-11 20:21:50 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 7) 2019-10-22  5:55:40 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 8) 2019-10-16  7:53:35 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 9) 2019-10-16  7:53:27 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 10) 2019-08-01 18:09:16 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 1 shutdown(s) detected in /var/lib/mysql/ve0216a.prego.net.br.err
[--] 1) 2019-06-02 15:38:07 0 [Note] /usr/sbin/mysqld: Shutdown complete

-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +Aria +CSV +InnoDB +MEMORY +MRG_MyISAM +MyISAM +PERFORMANCE_SCHEMA +SEQUENCE
[--] Data in MyISAM tables: 3.5M (Tables: 217)
[--] Data in InnoDB tables: 2.8G (Tables: 3006)
[--] Data in MEMORY tables: 0B (Tables: 30)
[OK] Total fragmented tables: 0

-------- Analysis Performance Metrics --------------------------------------------------------------
[--] innodb_stats_on_metadata: OFF
[OK] No stat updates during querying INFORMATION_SCHEMA.

-------- Security Recommendations ------------------------------------------------------------------
[OK] There are no anonymous accounts for any database users
[OK] All database users have passwords assigned
[--] There are 620 basic passwords in the list.

-------- CVE Security Recommendations --------------------------------------------------------------
[OK] NO SECURITY CVE FOUND FOR YOUR VERSION

-------- Performance Metrics -----------------------------------------------------------------------
[--] Up for: 2d 10h 3m 34s (2M q [9.696 qps], 49K conn, TX: 8G, RX: 276M)
[--] Reads / Writes: 78% / 22%
[--] Binary logging is disabled
[--] Physical Memory     : 15.4G
[--] Max MySQL memory    : 6.2G
[--] Other process memory: 0B
[--] Total buffers: 3.7G global + 16.3M per thread (151 max threads)
[--] P_S Max memory usage: 104M
[--] Galera GCache Max memory usage: 0B
[OK] Maximum reached memory usage: 4.0G (26.15% of installed RAM)
[OK] Maximum possible memory usage: 6.2G (40.20% of installed RAM)
[OK] Overall possible memory usage with other process is compatible with memory available
[OK] Slow queries: 0% (16/2M)
[OK] Highest usage of available connections: 9% (15/151)
[OK] Aborted connections: 0.00%  (0/49303)
[!!] Query cache may be disabled by default due to mutex contention.
[OK] Query cache efficiency: 40.1% (953K cached / 2M selects)
[!!] Query cache prunes per day: 18157
[OK] Sorts requiring temporary tables: 0% (12 temp sorts / 56K sorts)
[!!] Joins performed without indexes: 1027
[!!] Temporary tables created on disk: 99% (52K on disk / 52K total)
[OK] Thread cache hit rate: 99% (28 created / 49K connections)
[!!] Table cache hit rate: 3% (2K open / 61K opened)
Can't use string ("3423") as a SCALAR ref while "strict refs" in use at
        /root/mysqltuner.pl line 3249 (#1)
    (F) Only hard references are allowed by "strict refs".  Symbolic
    references are disallowed.  See perlref.

Uncaught exception from user code:
        Can't use string ("3423") as a SCALAR ref while "strict refs" in use at /root/mysqltuner.pl line 3249.
        main::mysql_stats() called at /root/mysqltuner.pl line 6377
[!!] table_definition_cache(400) is lower than number of tables(3423)

Can you help-me to understand and solve this?

**Comment by grooverdan** [comment]
I can't tell exactly which line 6377 maps up to in your mysqltuner version. 3423 is obviously the number of tables and is used around the table_definition_cache recommendations and these nor the select_one implemention has been changed after this bug report.

I've tested against 10.3.28-MariaDB and could not generate an error though numerous table definition cache paths. Maybe it was a MariaDB bug at the time.

If you could tests against with https://raw.githubusercontent.com/major/MySQLTuner-perl/master/mysqltuner.pl and report the line number if the same error, or your current MariaDB version that might getting to the cause of the problem if it still exists.

**Comment by jmrenouard** [comment]
Hi @grooverdan @BrunnoPrego 

Can't reproduce this issue and no feedback given on this issue 

Thanks for your comprehension
