### ISSUE TITLE
Recommendation on metadata_locks_hash_instances

### ISSUE THREAD

**Issue by lchenay** [major/MySQLTuner-perl#478]
Please add a recommendation on metadata_locks_hash_instances for Mysql < 8.0.13.

Default value is 8, fit to small server (up to 4-8 CPU). But could be a contention issue on big mysql server.

Recommended value is 2 per CPU. 

https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_metadata_locks_hash_instances

**Comment by jmrenouard** [comment]
Hi @lchenay 
MySQL 8.0 is now deprecated

So, we won't include this advice in MT

Thanks for your comprehension
