### ISSUE TITLE
Recommendation on innodb_adaptive_hash_index_partitions

### ISSUE THREAD

**Issue by lchenay** [major/MySQLTuner-perl#479]
"Adaptive Hash Index" (AHI) has been a source of contention on mysql prior to mysql 5.6 (or percona 5.5).

For mysql > 5.6, recommended value for innodb_adaptive_hash_index_parts is 0.5 per CPU
For percona > 5.5, recommended value for innodb_adaptive_hash_index_partitions is 0.5 per CPU
(perconna and mysql doesn't use same variables's name)

For mysql <= 5.6 && persona <= 5.5 : it could be a source of contention with huge load as AHI will only use 1 CPU. People have to do benchmark using innodb_adaptive_hash_index to activate or not the AHI.

CF : https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_adaptive_hash_index
CF : https://www.percona.com/blog/2016/04/12/is-adaptive-hash-index-in-innodb-right-for-my-workload/

**Comment by jmrenouard** [comment]
Hi,
I closed this issue MySQL 5.6 is no longer support 
https://endoflife.software/applications/databases/mysql

Best regards,
Jean-Marie
