### ISSUE TITLE
MySQLTuner does not work

### ISSUE THREAD

**Issue by Nirjonadda** [major/MySQLTuner-perl#483]
We do run MySQLTuner but this does not completed. Please can you let me know that how can fix this issue?

![ScreenShot00036](https://user-images.githubusercontent.com/6899856/75568516-b396a080-5a53-11ea-8ffb-b46b120cd7a7.png)

**Comment by mathieu-aubin** [comment]
Try this.. maybe

- Stop your sql instance
- Rotate or empty the log file at /var/log/mysqld.log
- Restart your sql server
- Try again

I believe your 32Mb logfile is giving you issues. **Probably** your sql instance logs are set to some high verbosity logging which results in big log files. Also, it could be that there are never any log file rotation being done on the actual file - which means your logfiles contains everything from the initial start of the instance, whenever the machine was created.

To rotate your logs automatically and thus keep them relevant and of a decent size on a daily or, even, weekly/monthly basis, check out _logrotate_

Hope this helps. Also, check if there is a `skip-log` option of some sort (i have no idea)

**Comment by jmrenouard** [comment]
Hi,

First as @mathieu-aubin says implementing a log rotation can be nice.

Maybe a control other file size greater than 200 Mb can be nice with a message advising implementing a log rotation strategy can be good.

BR,

**Comment by grooverdan** [comment]
closed via:
https://github.com/major/MySQLTuner-perl/commit/938b434e413fdb186901704f0be692ce48bfc610#diff-126d6c210bc4ad821cc428b8034b177003fc7171ac178088fdf6ce91cb787867R1301

Last 30k line are read.

**Comment by jmrenouard** [comment]
Fell free to reopen if needed
