### ISSUE TITLE
Stuck at logfile detection

### ISSUE THREAD

**Issue by coolrecep** [major/MySQLTuner-perl#486]
`
[root@server ~]# perl mysqltuner.pl --outputfile /tmp/result_mysqltuner.txt
 >>  MySQLTuner 1.7.19 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[OK] Currently running supported MySQL version 10.3.22-MariaDB
[OK] Operating on 64-bit architecture

-------- Log file Recommendations ------------------------------------------------------------------
[OK] Log file /var/lib/mysql/server.technopat.net.err exists
[--] Log file: /var/lib/mysql/server.technopat.net.err(513M)
[OK] Log file /var/lib/mysql/server.technopat.net.err is readable.
[OK] Log file /var/lib/mysql/server.technopat.net.err is not empty
[!!] Log file /var/lib/mysql/server.technopat.net.err is bigger than 32 Mb

`

**Solved at second run, sorry.**

**Comment by jmrenouard** [comment]
Hi @coolrecep,

Improvement managing large log file can be added.
If file is bigger than 32Mb, only 30000 last lines will be analyzed.

Best regards,
