### ISSUE TITLE
Incorrect values / figures

### ISSUE THREAD

**Issue by neobie** [major/MySQLTuner-perl#487]
After upgrading to the latest mysqltuner, 
I get such error:

[!!] Maximum reached memory usage: 789.8G (5055.73% of installed RAM)
[!!] Maximum possible memory usage: 1265.0G (8097.55% of installed RAM)

Previously it is 80% / 90% of installed RAM.

**Comment by arielesp** [comment]
same here... per thread value its wrong

**Comment by jmrenouard** [comment]
Hi @arielesp and @neobie 

Thanks for reporting

Can you give me more information ?

**Comment by neobie** [comment]
@jmrenouard , the newer version include 
$myvar{'max_allowed_packet'}
in per thread memory. The old version doesn't include that.

**Comment by heural** [comment]
The per-thread-buffers calculation is:
        $mycalc{'per_thread_buffers'} =
          $myvar{'record_buffer'} +
          $myvar{'record_rnd_buffer'} +
          $myvar{'sort_buffer'} +
          $myvar{'thread_stack'} +
          $myvar{'join_buffer_size'};

But record_buffer, record_rnd_buffer and sort_buffer not exist,
Here the output of this addition:
       +
           +
           +
          200704 +
          8388608

per_thread_buffer: 278859776

Whats going wrong here?

**Comment by jmrenouard** [comment]
Issue fixed with last PR: Fixing wrong calculation in memory usage (regression found) #679

Thanks for your patience and reporting this issue
 @jmrenouard
