### ISSUE TITLE
Unit is incorrect in MyISAM Metrics

### ISSUE THREAD

**Issue by Anankke** [major/MySQLTuner-perl#488]
![image](https://user-images.githubusercontent.com/40639066/78178390-8c096e00-742d-11ea-8a3d-07ebec6f3fa4.png)
It shoud be 2GB instead of 2B

**Comment by grooverdan** [comment]
Its hard to see what causes this. 2B is defiantly being measured as two bytes.

I did a number of changes in #524 so maybe the measurement may be fixed. The result will vary depending if you are connecting remotely via TCP or socket (in which case it looks for the MYI files in the datadir so you might be lacking permission).

So please try the latest version from github here, and include what connectoin options you are using.

**Comment by jmrenouard** [comment]
I think this is the end of MYISAM :D
PR https://github.com/major/MySQLTuner-perl/pull/524 shoud fix it
