### ISSUE TITLE
Maximum possible memory usage: mysqlx_max_connections?

### ISSUE THREAD

**Issue by qeepcologne** [major/MySQLTuner-perl#489]
I checked for our server and the output is:
Maximum possible memory usage: 181.4G
I try to calculate myself: 106G innodb_buffer_pool_size + (max_connections:4500 * memory per connection which is 17M in our case) => 183G, that looks reproducible.
But we have also mysqlx_max_connections = 2000, they are not calculated into maximum possible memory usage?

**Comment by jmrenouard** [comment]
Issue fixed with last PR: Fixing wrong calculation in memory usage (regression found) #679

Thanks for your patience and reporting this issue
 @jmrenouard
