### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by alagiyanirav** [major/MySQLTuner-perl#491]
Hi,
When I execute below command in ubuntu it gives me error of 500.

`wget http://mysqltuner.pl/ -O mysqltuner.pl`

Let me know if I am doing anything wrong.
Thanks
<img width="1005" alt="Screen Shot 2020-04-23 at 7 28 42 PM" src="https://user-images.githubusercontent.com/28755612/80107661-ff1f8380-8598-11ea-9431-5fbbeed19954.png">

**Comment by Luuk34** [comment]
In you screenshot is a different URL than in the command-line after wget  ??
Do they both give 500 ?

If so, post output of:
`wget -v http://mysqltuner.pl/ -O mysqltuner.pl`

**Comment by alagiyanirav** [comment]
Hi,
Thanks for the reply.
The wget URL is redirected to the screenshot URL.
But today it is working file so the issue has been resolved.
Thanks
