### ISSUE TITLE
Merge conflict non-resolved on develop

### ISSUE THREAD

**Issue by chteuchteu** [major/MySQLTuner-perl#492]
Dear maintainer,

The recent merge (https://github.com/major/MySQLTuner-perl/commit/1e8b32a25396907917c4c64d2fdd3ecb1e1a1337#diff-2cc6ed630854d08fdcfd8c17c70d25ef) broke mysqltuner.pl syntax. There seem to be a non-resolved merge conflict in this file (l.1 is `<<<<<<< HEAD`)

**Comment by jmrenouard** [comment]
Thanks and fixed
