### ISSUE TITLE
Some sort of mysqltuner version problem

### ISSUE THREAD

**Issue by davidfavor** [major/MySQLTuner-perl#493]
Current version shows to be - Version 1.7.15

I'm currently running - MySQLTuner 1.7.19 - Major Hayden <major@mhtx.net>

Please comment about correct version + correct download link, as...

[http://mysqltuner.com/mysqltuner.pl](http://mysqltuner.com/mysqltuner.pl) redirects to the old version.

Thanks.

**Comment by jmrenouard** [comment]
Fixed

**Comment by davidfavor** [comment]
Thanks!

Though I had somehow lost the plot.
