### ISSUE TITLE
mysqltuner fails on first line of new script with version control

### ISSUE THREAD

**Issue by Steve8291** [major/MySQLTuner-perl#494]
I just downloaded the newest commit: [https://github.com/major/MySQLTuner-perl/commit/1e8b32a25396907917c4c64d2fdd3ecb1e1a1337](url)

There seems to be lines relating to version control at the beginning and end of the script.
Do these need to be removed?

Running it with: `perl /usr/local/bin/mysqltuner --host 127.0.0.1`
I get: 

> Version control conflict marker at /usr/local/bin/mysqltuner line 1, near "<<<<<<<"
> BEGIN not safe after errors--compilation aborted at /usr/local/bin/mysqltuner line 42.

In Perl debug `perl -Mdiagnostics /usr/local/bin/mysqltuner` I see the following:

> Version control conflict marker at /usr/local/bin/mysqltuner line 1, near "<<<<<<<"
> BEGIN not safe after errors--compilation aborted at /usr/local/bin/mysqltuner line 42 (#1)
>     (F) The parser found a line starting with <<<<<<<,
>     >>>>>>>, or =======.  These may be left by a
>     version control system to mark conflicts after a failed merge operation.
>     
> Uncaught exception from user code:
> 	Version control conflict marker at /usr/local/bin/mysqltuner line 1, near "<<<<<<<"
> 	BEGIN not safe after errors--compilation aborted at /usr/local/bin/mysqltuner line 42.

**Comment by burakbuylu** [comment]
There are forgot git push HEAD

**Comment by jmrenouard** [comment]
Yes
Fixed now
