### ISSUE TITLE
v1.7.19 - Seeming bug with innodb_buffer_pool_size + innodb_buffer_pool_instances suggestions

### ISSUE THREAD

**Issue by davidfavor** [major/MySQLTuner-perl#497]
I might be wrong.

It appears there's a bug, where mysqltuner correctly determines best innodb_buffer_pool_size, then...

Incorrectly reports innodb_buffer_pool_instances == to innodb_buffer_pool_size.

So if best innodb_buffer_pool_size is determined to be 4G, then innodb_buffer_pool_instances is reported to be 4 (with G dropped).

I've been returning many MariaDB (10.3 + 10.4) instances today + this bug seems fairly consistent.

For example, if innodb_buffer_pool_size is suggested to by 9G...

The suggestion to also tune innodb_buffer_pool_instances to 9... seems... very odd, as that's...

81G total.

**Comment by ibaldonl** [comment]
innodb_buffer_pool_size is automatically divided by MySQL / MariaDB among the innodb_buffer_pool_instances.

I don't know if I understood you correctly or there is a misunderstanding on your part about those config variables.

Thanks for your clarification and sorry if I misunderstood you!

**Comment by davidfavor** [comment]
Still think this is a bug.

Seems like the correct setting should be...

innodb_buffer_pool_size=9G
innodb_buffer_pool_instances=1

To reach 9G.

Currently innodb_buffer_pool_instances shows a suggestion of increasing to 9.

So innodb_buffer_pool_size=9G * innodb_buffer_pool_instances=9 == 81G.

This is seems incorrect.

**Comment by davidfavor** [comment]
Or maybe...

innodb_buffer_pool_size=9G
innodb_buffer_pool_instances=9

Means each instance is 1G.

Maybe I was mistaken.

Let me know.

Thanks.

**Comment by ibaldonl** [comment]
Yes David, I think you are mistaken.
It means 9 instances of 1G in size totaling 9G of buffer pool.

**Comment by davidfavor** [comment]
Got it.

Thanks!

**Comment by ibaldonl** [comment]
You are welcome!!!
Can you please close this issue?
Thanks!!!

**Comment by davidfavor** [comment]
Will do!
