### ISSUE TITLE
Where are releases 1.7.18 and 1.7.19

### ISSUE THREAD

**Issue by xp-vit** [major/MySQLTuner-perl#498]
I want to update mysqltuner in Gentoo repository, but I don't see this releases to be present on GItHub. What are the URLs for these releases: 1.7.18 and 1.7.19?
Thanks a lot!

**Comment by jmrenouard** [comment]
Hi @xp-vit 

Nice idea to release MYSQLTuner 

Let me some time to do it !

**Comment by xp-vit** [comment]
Oh yes! Please let's do it and I can have fresh MysqlTunner on my Gentoo installation! :+1:

**Comment by xp-vit** [comment]
@jmrenouard Any chance I can help with releasing?

**Comment by cheese1** [comment]
any chance for a released version?

**Comment by ibaldonl** [comment]
Currently version 1.7.20 is released and it's identical to the current master branch, maybe this issue should be closed?

**Comment by xp-vit** [comment]
Can we create tag for 1.7.20? So any Linux repo will be able to point to the tag? Master branch can change any time.

**Comment by cheese1** [comment]
> Currently version 1.7.20 is released and it's identical to the current master branch, maybe this issue should be closed?

with released i would understand a version tagged with a release. its easier for packagers to use released versions.

**Comment by jmrenouard** [comment]
Hi @xp-vit 

Is it ok if we create a 1.7.21 version ?

**Comment by jmrenouard** [comment]
I publish tag 1.7.21
https://github.com/major/MySQLTuner-perl/releases/tag/1.7.21

**Comment by cheese1** [comment]
great, thanks
