### ISSUE TITLE
1.7.19 Cannot calculate MyISAM index size - re-run script as root user error

### ISSUE THREAD

**Issue by execash** [major/MySQLTuner-perl#500]
>>  MySQLTuner 1.7.19 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

-------- MyISAM Metrics ----------------------------------------------------------------------------
[!!] Key buffer used: 18.3% (3M used / 16M cache)
[!!] Cannot calculate MyISAM index size - re-run script as root user

**Comment by grooverdan** [comment]
Probably cleaned up as part of #524. @execash  can I assume you are on MariaDB-10.4+, if so there's no MyISAM tables by default which mysqltuner erronously assumed you didn't have the permission because it got 0 as the size of them.
