### ISSUE TITLE
mysqltuner.com has no DNS records

### ISSUE THREAD

**Issue by rwky** [major/MySQLTuner-perl#501]
The site is currently inaccessible because of this, see dig output from querying the nameservers below

```
 dig @ns-cloud-d1.googledomains.com mysqltuner.com

; <<>> DiG 9.16.1-Ubuntu <<>> @ns-cloud-d1.googledomains.com mysqltuner.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39857
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;mysqltuner.com.                        IN      A

;; AUTHORITY SECTION:
mysqltuner.com.         300     IN      SOA     ns-cloud-d1.googledomains.com. cloud-dns-hostmaster.google.com. 4 21600 3600 259200 300

;; Query time: 20 msec
;; SERVER: 216.239.32.109#53(216.239.32.109)
;; WHEN: Wed May 20 21:56:07 BST 2020
;; MSG SIZE  rcvd: 133

```

**Comment by Luuk34** [comment]
Try: mysqltuner.pl
it redirects to: https://raw.github.com/major/MySQLTuner-perl/master/mysqltuner.pl

> D:\TEMP>curl -i http://mysqltuner.pl
> HTTP/1.1 301 Moved Permanently
> Server: nginx
> Date: Thu, 21 May 2020 11:31:23 GMT
> Content-Type: text/html
> Transfer-Encoding: chunked
> Connection: close
> Location: https://raw.github.com/major/MySQLTuner-perl/master/mysqltuner.pl
> Cache-Control: max-age=10800
> Vary: Accept-Language
> 
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN"
>   "http://www.w3.org/TR/html4/frameset.dtd">
> 
> <html>
> <head>
> <title>301 Moved Permanently</title>
> </head>
> 
> <body>
>         <h1>Moved Permanently</h1>
>         <p>Object moved permanently -- see URI list</h1>
> </body>
> 
> </html>
>

**Comment by rendragnet** [comment]
mysqltuner.com has DNS records now...  Can we change the link on the githup repo mainpage please? :)

**Comment by xp-vit** [comment]
How this site relates to MySqlTunner? It's about guns and rifles...

**Comment by rendragnet** [comment]
> How this site relates to MySqlTunner? It's about guns and rifles...

Yes, that's the whole point..  Someone let the domain expire and now there's a spammer sitting on it..  I'm asking for references to the domain to be removed from this project's github mainpage so people aren't being sent to a spam site..

**Comment by jmrenouard** [comment]
Thanks

**Comment by mowny** [comment]
Nitpick:
The line now reads
` >>  Bug reports, feature requests, and downloads at http://mysqltuner.pl/`
but, as this redirects to the raw script itself, it takes some extra steps to get to the place for bug reports and feature requests (here).
Maybe use the wording from the comments at the top of the script
```
# For the latest updates, please visit http://mysqltuner.pl/
# Git repository available at https://github.com/major/MySQLTuner-perl
```
instead?
