### ISSUE TITLE
Change error.log empty to info message

### ISSUE THREAD

**Issue by Steve8291** [major/MySQLTuner-perl#504]
I wanted to suggest changing the following line in mysqltuner.pl 
line 1266      ` badprint "Log file $myvar{'log_error'} is empty";`
to
                      `infoprint "Log file $myvar{'log_error'} is empty";`

When using logrotate the current error.log will always be empty if there have been no errors. A better option might be to search through the rotated logs as well to detect starts and shutdowns. I see that those are already marked as info messages because my logs have been rotated.

**Comment by grooverdan** [comment]
likewise `'log_error'}" eq "stderr" ` is the default cause on containers and should be info too.

**Comment by grooverdan** [comment]
or, and the obvious case that `systemd` based mariadb services output to stderr too and then ends up in journald.

If those where opened with `[docker|podman] logs  --tail=30000 {container}` or `journalctl -b -n 30000 -u {service}` then the same analysis can be run.

So a new MySQLTuner option specify the `--server-log=[container|service]`

@Steve8291 sorry for going beyond your online patch issue into this.

**Comment by Steve8291** [comment]
That looks like a good way to deal with it @grooverdan and it covers containers as well!
