### ISSUE TITLE
Support for MariaDB 10.5.4

### ISSUE THREAD

**Issue by janekwisniewski86** [major/MySQLTuner-perl#505]
When does the official support for MySQL 10.5.4 is planned?

**Comment by grooverdan** [comment]
One significant change is that from 10.5 [innodb_buffer_pool_instances has been effectively removed](https://jira.mariadb.org/browse/MDEV-15058). Variable is still there however it can't be set to anything other than 1.

**Comment by Forza-tng** [comment]
> One significant change is that from 10.5 [innodb_buffer_pool_instances has been effectively removed](https://jira.mariadb.org/browse/MDEV-15058). Variable is still there however it can't be set to anything other than 1.

Just noticed this myself. Mysqltuner still suggests to use this option with mariadb 10.5.

**Comment by HoracioDos** [comment]
Its seems to be the same issue #512
