### ISSUE TITLE
Incorrect suggestion given by MYSQL Tuner - max_connections conf param

### ISSUE THREAD

**Issue by dhavaleshpotnuru** [major/MySQLTuner-perl#506]
Hi

Based on the MYSQL Tuner report we added max connections to our db server as 255. Below report given by Tuner

[--] Physical Memory     : 15.1G
[--] Max MySQL memory    : 11.4G
[--] Other process memory: 0B
[--] Total buffers: 3.4G global + 32.3M per thread (255 max threads)
[--] P_S Max memory usage: 0B
[--] Galera GCache Max memory usage: 0B
[OK] Maximum reached memory usage: 11.5G (76.14% of installed RAM)
[OK] Maximum possible memory usage: 11.4G (75.93% of installed RAM)

But recently so much load came into our website, during the peak time as well the memory utilized max of 9% and CPU utilized max of 5% of box which is very less but connections are exhausted.

As the max connections are reached during the peak time and server is doing good (i.e memory/cpu). So can we increase the max connections to 350/400 at-least?  Please suggest.

**Comment by grooverdan** [comment]
The maximum memory used by a connection depends a lot what is being done in the connection. Evidently your connections use a little less memory than the maximum.

As you've tested the maximum and there remains capacity you can go further.

Such high numbers of connections may indicate that your slow queries need addressing.

**Comment by jmrenouard** [comment]
Hi,

Somebody can help on this topics ?

How to calculate or estimate a good value ?

Thanks for your help

**Comment by jmrenouard** [comment]
Issue fixed with last PR: Fixing wrong calculation in memory usage (regression found) #679

Thanks for your patience and reporting this issue
 @jmrenouard
