### ISSUE TITLE
ERROR 1054 (42S22) at line 78 in file: './views/p_s/metrics_56.sql': Unknown column 'STATUS' in 'field list'

### ISSUE THREAD

**Issue by frankii91** [major/MySQLTuner-perl#508]
Język oryginału: angielski
1285/5000
I have a problem with
Optional Performance schema and Sysschema installation for MariaDB 10.x

during
mysql -u root -p <./sys_10.sql
gets a bug

ERROR 1054 (42S22) at line 78 in file: './views/p_s/metrics_56.sql': Unknown column 'STATUS' in 'field list'

arch linux and mariadb
[root @ MariaDB mariadb-sys-master] # pacman -Qi mariadb
Name: mariadb
Version: 10.5.5-2
Description: Fast SQL database server, derived from MySQL
Architecture: x86_64
URL: https://mariadb.org/
Licenses: GPL
Groups: None
Provides: mysql = 10.5.5
Depends On: mariadb-clients = 10.5.5 inetutils systemd-libs libxml2 zstd
Optional Deps: curl: for ha_s3 plugin [installed]
                  galera: for MariaDB cluster with Galera WSREP
                  mysql-python: for myrocks_hotbackup
                  perl-dbd-mysql: for mysqlhotcopy, mysql_convert_table_format and mysql_setpermission
Required By: None
Optional For: None
Conflicts With: mysql
Replaces: None
Installed Size: 234.53 MiB
Packager: Christian Hesse <arch@eworm.de>
Build Date: Thu Aug 20 08:24:47 2020
Install Date: Sat Sep 12 10:30:44 2020
Install Reason: Explicitly installed
Install Script: Yes
Validated By: Signature

**Comment by SzewsJa** [comment]
Cześć frankii91
Widziałem twój kod restApi Allegro. Skontaktuj się proszę jestem zainteresowany j.szews73@gmail.com

**Comment by jmrenouard** [comment]
Hi,
This issue is a issue for FromDual/mariadb-sys Github project
https://github.com/FromDual/mariadb-sys

MySQLTuner is not providing any code or support for mariaDB sysschema.

Thanks for your understanding

Jean-Marie
