### ISSUE TITLE
Mariadb-sys referenced in suggestions doesn't support Maria DB 10.x

### ISSUE THREAD

**Issue by meek2100** [major/MySQLTuner-perl#509]
This link for mariadb-sys doesn't support Maria DB only supports 10.0.x - https://github.com/good-dba/mariadb-sys

Probably need to update it to a more recently updated repo like https://github.com/FromDual/mariadb-sys that supports 10.x versions of Maria DB.  

According to https://fromdual.com/mariadb-sys-schema they say https://github.com/FromDual/mariadb-sys supports up to 10.4 at the time of writing the article.

**Comment by meek2100** [comment]
Looks like the latest changes has this code, but it doesn't appear to be working with MariaDB 10.4.14

`
"Performance schema shouldn't be activated for MariaDB 10.0 for performance issue"
        );
        push( @adjvars, "performance_schema = OFF disable PFS" );
        return;
    }
    unless ( grep /^sys$/, select_array("SHOW DATABASES") ) {
        infoprint "Sys schema isn't installed.";
        push( @generalrec,
"Consider installing Sys schema from https://github.com/mysql/mysql-sys for MySQL"
        ) unless ( mysql_version_le( 5, 6 ) );
        push( @generalrec,
"Consider installing Sys schema from https://github.com/FromDual/mariadb-sys for MariaDB"
        ) unless ( mysql_version_eq( 10, 0 ) or mysql_version_eq( 5, 5 ) );
`

**Comment by grooverdan** [comment]
Was fixed in #466

**Comment by grooverdan** [comment]
Upstream fix submitted to support 10.5 - https://github.com/FromDual/mariadb-sys/pull/2 . Once that is accepted/not then some more changing of wording can occur.

**Comment by FabioPedretti** [comment]
Since 10.6 the sys schema is included in MariaDB: https://jira.mariadb.org/browse/MDEV-9077

**Comment by grooverdan** [comment]
The existing MySQLTuner checks for the existance of the `sys` schema, so the MariaDB-10.6+ case is already taken care of.

The only broken case is the 10.5 as https://github.com/FromDual/mariadb-sys/pull/2 isn't merged.

So the only remaining change needed is removing 10.5 from the versions in which to recommend adding the sys schema.

**Comment by jmrenouard** [comment]
This issue is related to this one: ERROR 1054 #615
All fixes and details in ERROR 1054 #615 issue comments
