### ISSUE TITLE
Version Number in Releases

### ISSUE THREAD

**Issue by SenjorAlfonso** [major/MySQLTuner-perl#511]
There is a typo, 1.7.12 is called 1.7.2 and that's wired.

**Comment by jmrenouard** [comment]
Hi @SenjorAlfonso,

Can you tell me more because current version is 1.7.20 actually

Thanks

**Comment by SenjorAlfonso** [comment]
Sure, if I want to update from 1.7.19 it loads  1.7.12 cause it is is named 1.7.2 so 1.7.20 won't be found. Maybe take look here: https://github.com/major/MySQLTuner-perl/releases/tag/1.7.2

Also the git says the current version is Version 1.7.17 (Latest on 2 Oct 2019)

Hope this helps!
