### ISSUE TITLE
Remove innodb_buffer_pool_instances recommendations for MariaDB

### ISSUE THREAD

**Issue by toomuchio** [major/MySQLTuner-perl#512]
The setting has been totally removed as of 10.5, can read more about it here https://jira.mariadb.org/browse/MDEV-15058

I'd submit a PR but that setting seems tangled up in a few things so I didn't want to make the change with minimal understanding of how it would effect other things.

**Comment by grooverdan** [comment]
I've tested the implementation in de4b145e96fe4d605a16f4ebabffdbe7fdd50c92 and it looks good to me. Thanks @jmrenouard

**Comment by jmrenouard** [comment]
Feel free to reopen if needed
