### ISSUE TITLE
Suggestion for monitoring IOPS

### ISSUE THREAD

**Issue by Steve8291** [major/MySQLTuner-perl#522]
I've been using mysqltuner.pl for years and it's fantastic.
Thanks for making such a great tool.
Recently I've noticed a lot of discussions about raising `innodb_io_capacity` around the web.
I was wondering if adding some checks regarding that would be a useful addition to mysqltuner?

The best info I've been able to find is here: 
[https://www.percona.com/blog/2020/05/14/tuning-mysql-innodb-flushing-for-a-write-intensive-workload/](url)
[https://www.percona.com/blog/2019/12/18/give-love-to-your-ssds-reduce-innodb_io_capacity_max/](url)

Seems like mysqltuner could check the InnoDB Buffer and if it is really full then make the suggestion to increase `innodb_io_capacity`

Percona also recommends setting the value of `innodb_io_capacity_max`: "The ideal value should allow the checkpoint age to be as high as possible while staying under 75% of the max checkpoint age."
Seems like that could be a check to add to mysqltuner as well.

I realize that both of those tests would need to be carried out when the server was under a typical load. It would be nice if syschema kept some performance values on average checkpoint age and average buffer size. I don't think it does though.

**Comment by jmrenouard** [comment]
Hi @Steve8291 

Do you get some calculation formula based on variables and status helping us displaying a good value for this settings ?

**Comment by Steve8291** [comment]
@jmrenouard I tried to do a bit more digging into this and I don't think there is a good way for mysqltuner to come up with a value to tune by. There are just too many variables involved such as whether the disk is an ssd or not, and the actual performance capabilities IOPS of the disk. I'll go ahead and close this request.
