### ISSUE TITLE
no longer advise raising innodb_buffer_pool_instances

### ISSUE THREAD

**Issue by toshniba** [major/MySQLTuner-perl#544]
Why there are still advises to set `innodb_buffer_pool_instances` > 1 for recent mariadb server versions as they seem to are not longer sinful?

https://jira.mariadb.org/browse/MDEV-21826
https://jira.mariadb.org/browse/MDEV-15058

**Comment by grooverdan** [comment]
was fixed per #512
MDEV-21826 was a bug in MariaDB's innodb_buffer_pool_instances implementation.
MDEV-15058 de4b145e96fe4d605a16f4ebabffdbe7fdd50c92 - no longer a recommendation in 10.5+ as its fixed.

**Comment by toshniba** [comment]
Right, Since 10.5 (where the paramter got removed) this advice is no longer on the summary. Just tested on some 10.2 version before.

IMHO it seems this advice is generally no longer appropriate as of todays server infrastructure/hardware!?

Thanks for implementation anyhow.
