### ISSUE TITLE
Duplicate recommendation/check

### ISSUE THREAD

**Issue by vladloskut** [major/MySQLTuner-perl#545]
From the Galera metrics part I found the following:

-------- Galera Metrics ----------------------------------------------------------------------------
[--] Galera is enabled.
[--] GCache is using 0B
[--] CPU core detected  : 6

[--] wsrep_slave_threads: 24
[OK] wsrep_slave_threads is equal to 2, 3 or 4 times number of CPU(s)
**[!!] gcs.fc_limit should be equal to 5 * wsrep_slave_threads**
[--] wsrep parallel slave can cause frequent inconsistency crash.
**[!!] gcs.fc_limit should be equal to 5 * wsrep_slave_threads**
[OK] gcs.fc_factor is equal to 0.8
[OK] Flow control fraction seems to be OK (wsrep_flow_control_paused<=0.02)

As you can see gcs.fc_limit is duplicated as well as per recommendation part:

Variables to adjust:
    max_connections (> 70)
    wait_timeout (< 28800)
    interactive_timeout (< 28800)
    binlog_cache_size (16.0M)
    innodb_buffer_pool_size (>= 198.4G) if possible.
    innodb_buffer_pool_instances(=42)
    **gcs.fc_limit= wsrep_slave_threads * 5**
    Set wsrep_slave_threads to 1 in case of HA_ERR_FOUND_DUPP_KEY crash on slave
    **gcs.fc_limit= wsrep_slave_threads * 5**
    set up parameter wsrep_notify_cmd to be notify

Is this OK or something wrong on my machine?

Thanks in advance

**Comment by jmrenouard** [comment]
Removed in 17.22

Thanks @vladisalv
