### ISSUE TITLE
Error executing script sys_10.sql in MariaDB 10.5.8

### ISSUE THREAD

**Issue by mzalazar** [major/MySQLTuner-perl#547]
I activated 'performance_schema' table (following your instructions), restarted server (now performance_schema table is there) and run the script:

`mysql -u root -p < ./sys_10.sql`

and it throws an error:
```
root@5417a729b84c:/performance/mariadb-sys-master# mysql -u root -p < ./sys_10.sql
Enter password: 
ERROR 1054 (42S22) at line 78 in file: './views/p_s/metrics_56.sql': Unknown column 'STATUS' in 'field list'
```

What's happening here? it's a bug?
Please excuse my very basic english ;-)

**Comment by jmrenouard** [comment]
Hi @mzalazar 

Get the same issue: 

Issue comes from this github project:
https://github.com/FromDual/mariadb-sys

Fix is here proposed by @grooverdan  :
https://github.com/FromDual/mariadb-sys/pull/1


root@BD-01:/tmp# git clone https://github.com/FromDual/mariadb-sys
Clonage dans 'mariadb-sys'...
remote: Enumerating objects: 3045, done.
remote: Total 3045 (delta 0), reused 0 (delta 0), pack-reused 3045
Réception d'objets: 100% (3045/3045), 1.19 MiB | 11.91 MiB/s, fait.
Résolution des deltas: 100% (1793/1793), fait.
root@BD-01:/tmp# cd mariadb-sys/
root@BD-01:/tmp/mariadb-sys# ls
after_setup.sql   COPYING    generate_sql_file.sh  MERGE.md    NEWS.md     README.md   sys_56.sql  tables     triggers
before_setup.sql  functions  LICENSE               mysql-test  procedures  sys_10.sql  sys_57.sql  templates  views
root@BD-01:/tmp/mariadb-sys# cat sys_10.sql | mysql
ERROR 1054 (42S22) at line 78 in file: './views/p_s/metrics_56.sql': Unknown column 'STATUS' in 'field list'

I will close this is not a MT issue

Thanks for your understanding

@jmrenouard

**Comment by grooverdan** [comment]
technically my fix is https://github.com/FromDual/mariadb-sys/pull/2

Work around is to clone https://github.com/grooverdan/mariadb-sys instead. I'm not going to guarantee it will always be there.

From 10.6 the sys schema will be installed by default.
