### ISSUE TITLE
Wrong table cache hit rate calculation

### ISSUE THREAD

**Issue by MichaIng** [major/MySQLTuner-perl#548]
Based on https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L2706 the table cache hit rate is currently calculated as ratio of [Open_tables](https://mariadb.com/kb/en/server-status-variables/#open_tables) and [Opened_Tables](https://mariadb.com/kb/en/server-status-variables/#opened_tables), hence the currently opened non-temporary tables and the overall opened tables. But this does not represent that cache hit rate where the `table_open_cache` recommended should be based on, does it?

There are two stats for table cache hits and misses which seem to be the correct ones here:
```
MariaDB [(none)]> show global status like 'Table_open_cache_%';
+-----------------------------------+----------+
| Variable_name                     | Value    |
+-----------------------------------+----------+
| Table_open_cache_active_instances | 1        |
| Table_open_cache_hits             | 22555304 |
| Table_open_cache_misses           | 2866     |
| Table_open_cache_overflows        | 0        |
+-----------------------------------+----------+
```
=>
```
int( $mystat{'Table_open_cache_hits'} * 100 / ( $mystat{'Table_open_cache_hits'} + $mystat{'Table_open_cache_misses'} ) );
```

**Comment by MichaIng** [comment]
Many thanks for https://github.com/major/MySQLTuner-perl/commit/2079639e6bea9fa7f1aa44d7847363e29ae581a9, it works as expected here now.

Btw, I just verified that these variables are the same on MySQL, but they have been introduced with v5.6: https://dev.mysql.com/doc/refman/5.6/en/added-deprecated-removed.html

**Comment by sbrowne-godaddy** [comment]
Whilst a little late, this now breaks the math if `Table_open_cache_hits` or `Table_open_cache_misses` isn't present in the hash. The items the math depends upon are no longer having their existence tested.
