### ISSUE TITLE
improve FreeBSD support a bit (patch included)

### ISSUE THREAD

**Issue by bit0mike** [major/MySQLTuner-perl#549]
Here is a patch that fixes two calculations that currently only work on Linux so that they will also work on FreeBSD.  (It does use $^O instead of uname to get the OS type, which I think is a bit more portable.) More could be done here, but this minimalist patch at least stops it from throwing errors on our FreeBSD-based Galera cluster.

[mysqltuner.diff.txt](https://github.com/major/MySQLTuner-perl/files/6137492/mysqltuner.diff.txt)

**Comment by jmrenouard** [comment]
Hi @bit0mike 

Can you submit a pull request for this patch, please ?

https://opensource.com/article/19/7/create-pull-request-github

- Find a project you want to contribute to
- Fork it
- Clone it to your local system
- Make a new branch
- Make your changes
- Push it back to your repo
- Click the Compare & pull request button
- Click Create pull request to open a new pull request

Best regards,
Jean-Marie

**Comment by jmrenouard** [comment]
Hi @bit0mike 

Always wanting your PR :)

BR @jmrenouard

**Comment by jmrenouard** [comment]
Patch included
