### ISSUE TITLE
Script freezes after first line of Storage Engine Statistics

### ISSUE THREAD

**Issue by jlowe64** [major/MySQLTuner-perl#55]
- Redhat Enterprise Linux 6
- Architecture = x86_64
- MySQL version 5.5.39
- OS yum package install
- There was no error, but it just halted after the following line without progressing. I have to force exit the script:

[--] Status: +ARCHIVE +BLACKHOLE +CSV -FEDERATED +InnoDB +MRG_MYISAM

**Comment by dadaas** [comment]
I m on a box with 300 000 tables with 150GB in MYSQL. Is it even possible to use mysqltuner on this huge MYSQL?

I m waiting for 3h on storage statistics and nothing happens.

P.S. sorry to revoke old thread but it is related.

**Comment by tssajo** [comment]
I am also experiencing this same problem on a server which has lots of databases and lots of tables.

It would be great if we had a command line switch forcing mysqltuner to skip this query completely.

**Comment by rounce** [comment]
You can use --skipsize to skip this query
