### ISSUE TITLE
If password contains single quote, you can't use this script

### ISSUE THREAD

**Issue by svaningelgem** [major/MySQLTuner-perl#550]
You'll just get:
```
sh: 1: Syntax error: Unterminated quoted string
[!!] Attempted to use login credentials, but they were invalid
```

**Comment by jmrenouard** [comment]
Hi @svaningelgem 

do you try unspecialized quote with \" for example or use .my.cnf as explain in README.md ?

A quick and easy solution is avoiding using quotes in password for mysqltuner.pl and for all kind of script in fact :)

BR
@jmrenouard

**Comment by svaningelgem** [comment]
That's basically what I did ;-), but I was hoping you could improve the script to accommodate those passwords as well.
