### ISSUE TITLE
mysqltuner.pl not responding

### ISSUE THREAD

**Issue by gggeek** [major/MySQLTuner-perl#554]
```
>ping mysqltuner.pl
Ping request could not find host mysqltuner.pl. Please check the name and try again.
```

Either my dns provider has issues, or mysqltuner.pl does.

Is that a temporary snag, or should download instructions be altered ?

**Comment by lds-lds** [comment]
not responding for me to

**Comment by major** [comment]
Hey folks, I did not deal with an account balance issue at Gandi in time, and I've lost the domain. I'm trying to see if I can get it back, but no luck so far.

**Comment by Cristy94** [comment]
How can we download the script meanwhile instead of `wget http://mysqltuner.pl/ -O mysqltuner.pl` ?

Also, it's really important to notify people somehow or make sure an attacker doesn't get that domain instead.

**Comment by Cristy94** [comment]
To answer my own question, meanwhile you can use `wget https://raw.githubusercontent.com/major/MySQLTuner-perl/master/mysqltuner.pl -O mysqltuner.pl` to download the script.

**Comment by major** [comment]
@Cristy94 Still trying to get the domain back, but the .pl registrar makes things a little challenging.

**Comment by Luuk34** [comment]
I just noticed mysqltuner.pl is working again!
```
DOMAIN NAME:           mysqltuner.pl
registrant type:       individual
nameservers:           ns-148-a.gandi.net. 
                       ns-56-b.gandi.net. 
                       ns-78-c.gandi.net. 
created:               2008.06.02 13:06:44
last modified:         2021.06.04 14:46:09
renewal date:          2022.06.02 13:06:44

option created:        2021.05.24 21:07:46
option expiration date:       2024.05.24 21:07:46
```

**Comment by major** [comment]
Yup, $30 and a few emails later, we're back in business.
