### ISSUE TITLE
Performance schema and Sysschema installation for MariaDB >= 10.4 fails

### ISSUE THREAD

**Issue by jeremyj11** [major/MySQLTuner-perl#556]
mysql -u root -p < ./sys_10.sql
on mariadb >= 10.4 fails with:

`ERROR 1054 (42S22) at line 78 in file: './views/p_s/metrics_56.sql': Unknown column 'STATUS' in 'field list'`

Due to: 
[https://github.com/prometheus/mysqld_exporter/issues/494](https://github.com/prometheus/mysqld_exporter/issues/494)

Solution is to change line 78 in file: './views/p_s/metrics_56.sql' from:
`IF(STATUS,'enabled'`
to
`IF(ENABLED,'1'`

**Comment by jmrenouard** [comment]
Duplicate with #547

Solution: Pull requet to GitHub project FromDual/mariadb-sys 
https://github.com/FromDual/mariadb-sys/pull/2

Sys schema included in next MariaDB version
