### ISSUE TITLE
Update needed for MariaDB 10.6

### ISSUE THREAD

**Issue by willamowius** [major/MySQLTuner-perl#557]
mysqltuner 1.7.29 fails with MariaDB 10.6.3:

[!!] Your MySQL version 10.6.3-MariaDB-1:10.6.3+maria~focal-log is EOL software!  Upgrade soon!

This is obviously incorrect.

[OK] NO SECURITY CVE FOUND FOR YOUR VERSION
Use of uninitialized value in multiplication (*) at ./mysqltuner.pl line 2816 (#1)
    (W uninitialized) An undefined value was used as if it were already
...
And then it fails altogether:

[OK] InnoDB buffer pool / data size: 80.0G/10.6G
Use of uninitialized value in concatenation (.) or string at ./mysqltuner.pl
	line 5784 (#1)
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (0 %): 8.0G * /80.0G should be equal to 25%
Use of uninitialized value in division (/) at ./mysqltuner.pl line 5791 (#1)

Illegal division by zero at ./mysqltuner.pl line 5791 (#2)

**Comment by jmrenouard** [comment]
Hi @willamowius 

Tell me your feedback please :)

**Comment by willamowius** [comment]
That was quick!
Work fine now.
Thanks!
