### ISSUE TITLE
Version 1.8.1 not reporting replication correctly

### ISSUE THREAD

**Issue by lounicotra** [major/MySQLTuner-perl#562]
Just downloaded the 1.8.1 release. It is currently not reporting replication correctly.  It had me chasing the master-server status for a non-existing replication issue.  I confirmed replication is up and running via mysql. Reverted back to 1.7.19 and it shows correct state of replication.

1.8.1
-------- Replication Metrics -----------------------------------------------------------------------
[--] Galera Synchronous replication: NO
[--] This server is acting as master for 3 server(s).
[--] Binlog format: MIXED
[--] XA support enabled: ON
[--] Semi synchronous replication Master: Not Activated
[--] Semi synchronous replication Slave: Not Activated
[--] No replication setup for this server or replication not started.

1.7.19
-------- Replication Metrics -----------------------------------------------------------------------
[--] Galera Synchronous replication: NO
[--] No replication slave(s) for this server.
[--] Binlog format: MIXED
[--] XA support enabled: ON
[--] Semi synchronous replication Master: Not Activated
[--] Semi synchronous replication Slave: Not Activated
[OK] This replication slave is running with the read_only option enabled.
[OK] This replication slave is up to date with master.

mysql
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 1
                  Master_UUID: b4052626-8ca5-11e6-88bd-0cc47a6c9b2a
             Master_Info_File: /database/mysql/master.info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name:
           Master_TLS_Version:
1 row in set (0.00 sec)

ERROR:
No query specified

**Comment by qeepcologne** [comment]
we have the same issue with 1.8.1, 1 master with 2 replications slaves (up & running), mysql version 8.0.26

**Comment by jmrenouard** [comment]
Hi,

Same issue on 19.3

**Comment by jmrenouard** [comment]
I will work on a MySQL replication during this next month 
I will be able to provide some patches :)

**Comment by jmrenouard** [comment]
Is last PR #589 help ?
Fix some master/slave renaming issues #589

**Comment by jmrenouard** [comment]
A lot of fixes on replication in v1.9.9 and v2.0.1
Fell free to reopen it with more details :)
