### ISSUE TITLE
Illegal division by zero

### ISSUE THREAD

**Issue by dac2020** [major/MySQLTuner-perl#566]
I was running mysqltuner-1.7.21 on Debian and got a similar result so used apt to install which gave me MySQLTuner 1.7.17.
However, this one also gives me another similar error. The os is Debian GNU/Linux 11 (bullseye).

Not being a programmer, I'm not sure what I am facing and searching using Google is leading to countless things which don't help so thought I should ask here.

`-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[OK] InnoDB File per table is activated
[OK] InnoDB buffer pool / data size: 48.0G/7.5G
Use of uninitialized value in concatenation (.) or string at
        /usr/bin/mysqltuner line 5614 (#1)
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (0 %): 5.0G * /48.0G should be equal to 25%
Use of uninitialized value in division (/) at /usr/bin/mysqltuner line 5621 (#1)

Illegal division by zero at /usr/bin/mysqltuner line 5621 (#2)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.

Uncaught exception from user code:
        Illegal division by zero at /usr/bin/mysqltuner line 5621.
        main::mysql_innodb() called at /usr/bin/mysqltuner line 6353
`

**Comment by dac2020** [comment]
Is no one monitoring issues here?

**Comment by dac2020** [comment]
Anyone? Surely I'm not the only one seeing this problem?

**Comment by jmrenouard** [comment]
Hi,  
This issue have been solved in a later version 1.7.24


Best regards,
Jean-Marie

**Comment by jmrenouard** [comment]
innodb_log_files_in_group deprecated and ignored from MariaDB 10.5.2 #565

**Comment by dac2020** [comment]
Thank you for the reply.

Just so you know, mysqltuner-1.7.21.pl works fine on Centos 7 at least but not on Debian as mentioned above. I tried to upgrade but could not find an upgrade path for that OS.

**Comment by jmrenouard** [comment]
Hi,

Thanks for your quick answer

I just tag code in Github for a new version 1.7.24

I closed this issue 
Jean-Marie

**Comment by dragonfly-net** [comment]
lsb_release -r
Release:        22.04

mysqltuner is already the newest version (1.7.17-1).

It was 2023...

**Comment by mdotk** [comment]
I am seeing this exact problem. What is the fix?

**Comment by dragonfly-net** [comment]
> I am seeing this exact problem. What is the fix?

download current version and replace file

**Comment by andreyandreenko** [comment]
10.11.13-MariaDB-0ubuntu0.24.04.1 - Ubuntu 24.04
MySQLTuner 2.6.2

Illegal division by zero at mysqltuner.pl line 6570 (#1)                                                              
    (F) You tried to divide a number by 0.  Either something was wrong in                                             
    your logic, or you need to put a conditional in to guard against                                                  
    meaningless input.                                                                                                

Uncaught exception from user code:                                                                                    
        Illegal division by zero at mysqltuner.pl line 6570.                                                          
        main::mysql_innodb() called at mysqltuner.pl line 7437

**Comment by Va-Bank** [comment]
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
Linux mysql 6.1.0-38-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.147-1 (2025-08-02) x86_64 GNU/Linux
***********************************************************
mysqltuner installed from official debian repository
***********************************************************
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (75%): 96.0M * 1/128.0M should be equal to 25%
Illegal division by zero at /usr/bin/mysqltuner line 6024 (#1)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.

Uncaught exception from user code:
        Illegal division by zero at /usr/bin/mysqltuner line 6024.
        main::mysql_innodb() called at /usr/bin/mysqltuner line 6843

**Comment by jmrenouard** [comment]
Hi @ETNyx,

Current version is 2.7.1

BR,
@jmrenouard
