### ISSUE TITLE
Script do not OK to use with GCP Mysql

### ISSUE THREAD

**Issue by gdennye** [major/MySQLTuner-perl#570]

**Comment by gdennye** [comment]
root@zabbix:~/mysql-proxy/MySQLTuner-perl# perl mysqltuner.pl --host x.x.x.x --user <user> --pass='xxxxxx' --port 3307 --forcemem 15360 --forceswap 4096 --verbose dbstat
 >>  MySQLTuner 1.8.3 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.pl/
 >>  Run with '--help' for additional options and output filtering
[OK] You have the latest version of MySQLTuner(1.8.3)
[--] Performing tests on x.x.x.x:3307
[OK] Logged in using credentials passed on the command line
[--] Assuming 15360 MB of physical memory
[--] Assuming 4096 MB of swap space


Does not pass this step until you get a connection timeout

**Comment by jmrenouard** [comment]
This is a connection issue to database not a bug on MT
