### ISSUE TITLE
mysqltuner.com is now a gun part store?

### ISSUE THREAD

**Issue by erichowey** [major/MySQLTuner-perl#571]
I was checking out the github-page for this repo and was taken to mysqltuner.com. It's now a gun store with no references to the repo from what I can see. I didn't know if this was intentional or not.
![image](https://user-images.githubusercontent.com/4033313/139714349-0d8353de-5ac1-44c1-9c83-708c7cb92ec1.png)

**Comment by jmrenouard** [comment]
Hi,
 Yes intentionnal
mysqltuner.com is not used we are using mysqltuner.pl as last version pointer
