### ISSUE TITLE
DOS-style line endings

### ISSUE THREAD

**Issue by brandhout** [major/MySQLTuner-perl#574]
Hi!

The build_rpm.sh script contains DOS-style line endings; I have to convert it to UNIX before I can run it. 

`zsh: ./build_rpm.sh: bad interpreter: /bin/sh^M`

When saved with `:set fileformat=unix` (vim) It works as expected. 

Thank you

**Comment by jmrenouard** [comment]
Thanks for our issue
Job done

Last commit with fixed lin endings
