### ISSUE TITLE
Recommendation to turn on performance_schema

### ISSUE THREAD

**Issue by MichaIng** [major/MySQLTuner-perl#579]
MySQLTuner generally recommends to enable performance_schema for "better diagnostics". However, while it shows PF memory usage, it uses it only to check for unused indexes when table metrics are enabled, right? Probably the recommendation could somehow indicate this, as without enabling table metrics or manually analysing performance_schema, enabling it is useless and only consumes a bit of memory.

**Comment by jmrenouard** [comment]
HI @MichaIng 

Can you give us your feedback ?

**Comment by MichaIng** [comment]
There has been something confused in the code now, please see my comment and suggestion: https://github.com/major/MySQLTuner-perl/commit/b164a9b#r65203351

But the general question has not been addressed, i.e. does it really help that much for MySQLTuner diagnostics and does not really have no performance downsides with new MySQL/MariaDB versions? The recommendation could be more precise and say that it is required for table metrics only, and of course when manually used, but not sure whether it is correct to advise enabling PFS generally. It is disabled by default (when not overwritten by distribution package, but not done on Debian and Ubuntu at least), which may have some reason, even on newer MySQL/MariaDB versions.

**Comment by jmrenouard** [comment]
Hi @MichaIng 
Some config elements on my server, PFS impact performance for sure but ...

You should activate by PFS using performance_schema=ON
because:
 * You can't activate it without restarting your server 
 * AND you can configure all you consumers to OFF by default and activate it when you think it is necessary 

Some readings;
* https://www.alibabacloud.com/blog/best-practices-for-setting-the-parameter-performance-schema-overview_598273
* https://www.thegeekdiary.com/recommended-configuration-of-the-mysql-performance-schema/

Best regards,
Jean-Marie

**Comment by MichaIng** [comment]
Restarting the database server is not a big issue in many cases. Of course it enables additional monitoring abilities, but the question is whether admins actively use them or not. If someone is actively using them, then (s)he will be surely aware that for this is needs to be enabled, hence MySQLTuner does not need to give that advice for those. For anyone who is not actively using PFS, the recommendation is then somehow wrong, since it remains unused but consumes resources.

Another idea would be to show the recommendation only when `--idxstat` is set, where MySQLTuner itself reads PFS to detected unused indexes (?).

But most importantly, the current doubled + contradicting checks and info needs to be merged, as of the code comment I linked above. I can open a PR soon.

**Comment by MichaIng** [comment]
Hmm, the PFS check is still a mess. There is a dummy if-then-else block now. And MySQL <=5.5 + MariaDB == 10.0 get a warning now regardless whether it is on or off:
- When it is OFF, all systems get a recommendation to enable it.
- When it is ON, MySQL <=5.5 + MariaDB == 10.0 get a recommendation to disable it.

I can only recommend to check my comment with a suggestion how to structure the block: https://github.com/major/MySQLTuner-perl/commit/b164a9b#r65203351

**Comment by jmrenouard** [comment]
New fix with all your recommandations

**Comment by MichaIng** [comment]
Many thanks. I see you removed the differentiation for old MySQL and MariaDB versions, which I think is fine 👍.
