### ISSUE TITLE
Minor 1.9.4 message fix

### ISSUE THREAD

**Issue by davidfavor** [major/MySQLTuner-perl#581]
This diagnostic is emitted, even when no MyISAM storage engine tables are in use (InnoDB storage engine in use)...
```
    key_buffer_size (~ 24M)
```
Maybe there's some reason for this.

If not, as it appears key_buffer_size only applies to MyISAM storage engine tables, be nice if this message was silenced.

Thanks for your consideration of this request.

**Comment by jmrenouard** [comment]
Hi,

Can you tell us more about our database version ?

BR,
Jean-Marie

**Comment by jmrenouard** [comment]
Fix with last commit 1.9.5
[False impression on key buffer usage](https://github.com/major/MySQLTuner-perl/issues/573#)
#573
-------- MyISAM Metrics ----------------------------------------------------------------------------
[--] No MyISAM table(s) detected ....
