### ISSUE TITLE
'Maximum reached memory usage' > Total RAM + SWAP?

### ISSUE THREAD

**Issue by solracsf** [major/MySQLTuner-perl#584]
How can this even be possible?

`[!!] Maximum reached memory usage: 52.8G (696.35% of installed RAM)`

**Comment by jmrenouard** [comment]
Hi,

Calculated on all server buffers + all client buffers * Max_connections
https://www.mysqlcalculator.com/ for a basic calculus example

Thanks,

**Comment by solracsf** [comment]
I understand that as a possible max memory consumption, but how can that be **reached**?

**Comment by jmrenouard** [comment]
Hi,

This is theorical:
Sum of all server buffer + max_connctions * (all client buffers)

This means that:
 - all connections are opened
 - all clients used all buffers allowed
