### ISSUE TITLE
innodb_buffer_pool_instances(=16) suggested for MariaDB 10.5 which doesn't support it

### ISSUE THREAD

**Issue by scott8035** [major/MySQLTuner-perl#588]
Hi all. I'm running MariaDB 10.5.15 on an Ubuntu 20.04 server. When I run mysqltuner, it recommends setting innodb_buffer_pool_instances(=16), yet according to https://mariadb.com/kb/en/innodb-buffer-pool/#innodb_buffer_pool_instances, that parameter was disabled in MariaDB 10.5 and removed in 10.6.

**Comment by scott8035** [comment]
By the way, it's mysqltuner version 1.7.13.

**Comment by jmrenouard** [comment]
Changing condition for innodb-buffer-pool lower or equal to 10.4
