### ISSUE TITLE
[!!] InnoDB is enabled but isn't being used

### ISSUE THREAD

**Issue by iamthatguy** [major/MySQLTuner-perl#59]
i'm kind of new to this so i apologize before hand encase this is an issue that has been address already.

i just installed MySQLTuner on my server and am trying to understand why i am getting :  
[!!] InnoDB is enabled but isn't being used

when to my understanding InnoDB i the default. when i run the query 'SHOW ENGINES;' i get this:

mysql> SHOW ENGINES;
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+
| Engine             | Support | Comment                                                        | Transactions | XA   | Savepoints |
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+
| PERFORMANCE_SCHEMA | YES     | Performance Schema                                             | NO           | NO   | NO         |
| MRG_MYISAM         | YES     | Collection of identical MyISAM tables                          | NO           | NO   | NO         |
| MEMORY             | YES     | Hash based, stored in memory, useful for temporary tables      | NO           | NO   | NO         |
| BLACKHOLE          | YES     | /dev/null storage engine (anything you write to it disappears) | NO           | NO   | NO         |
| MyISAM             | YES     | MyISAM storage engine                                          | NO           | NO   | NO         |
| CSV                | YES     | CSV storage engine                                             | NO           | NO   | NO         |
| ARCHIVE            | YES     | Archive storage engine                                         | NO           | NO   | NO         |
| FEDERATED          | NO      | Federated MySQL storage engine                                 | NULL         | NULL | NULL       |
| InnoDB             | DEFAULT | Supports transactions, row-level locking, and foreign keys     | YES          | YES  | YES        |
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+

**Comment by manuelsdt** [comment]
I am getting the same output from mysqltuner.pl ("[!!] InnoDB is enabled but isn't being used") and when I run the query above I also get "Empty set (0.01 sec)".  What I didn't understand in the above is can I disable InnoDB and if so will it buy me anything or not really?  innodb_buffer_pool_size is not defined in my conf file.

Thanks.
