### ISSUE TITLE
log problem and advise improve config mariadb after several issues

### ISSUE THREAD

**Issue by sof931** [major/MySQLTuner-perl#595]
Hello,

I have executed mysqltuner in my production server during an issue, the database didn't responde. I would like with theses elements advises to improve my config : 

My hardware config :
Environnement : Production
OS : CENTOS 7.x
vCpu : 4
RAM : 16 Go
Duplicate of #Stockage SAN (Hors OS) : FS de 80 Go

My server.cnf : 

# this is read by the standalone daemon and embedded servers
[server]
# this is only for the mysqld standalone daemon
log_error=/var/log/mysql/log_mariadb.err
log_warnings=3
[mysqld]
# data directory
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
max_connections = 1200
port=3306
log_error=/var/log/mysql/mariadb.err
log_warnings=3
innodb_buffer_pool_size=8G
innodb_file_per_table=1
skip-name-resolve=ON

# Query Cache
query_cache_type = 0
query_cache_size = 32M
tmp_table_size= 256M
max_heap_table_size= 256M

long_query_time = 1
max_allowed_packet = 64M
thread_cache_size = 128
event-scheduler = 1

#recommendation mysqltuner
performance_schema = ON 
innodb_log_file_size = 512M
innodb_log_buffer_size = 8M
innodb_flush_log_at_trx_commit = 0

innodb_flush_method = O_DIRECT
innodb_thread_concurrency = 10

#
# * Galera-related settings
#
[galera]
# Mandatory settings
#wsrep_on=ON
#wsrep_provider=
#wsrep_cluster_address=
#binlog_format=row
#default_storage_engine=InnoDB
#innodb_autoinc_lock_mode=2
#
# Allow server to accept connections on all interfaces.
#
bind-address=0.0.0.0
#
# Optional setting
#wsrep_slave_threads=1
#innodb_flush_log_at_trx_commit=0

# this is only for embedded server
[embedded]

# This group is only read by MariaDB servers, not by MySQL.
# If you use the same .cnf file for MySQL and MariaDB,
# you can put MariaDB-only options here
[mariadb]

# This group is only read by MariaDB-10.3 servers.
# If you use the same .cnf file for MariaDB of different versions,
# use this group for options that older servers don't understand
[mariadb-10.3]

The mysqltuner results : 

[--] Skipped version check for MySQLTuner script
Please enter your MySQL administrative login: root
Please enter your MySQL administrative password: [OK] Currently running supported MySQL version 10.3.8-MariaDB-log
[OK] Operating on 64-bit architecture

-------- Log file Recommendations ------------------------------------------------------------------
[!!] Log file /var/log/mysql/mariadb.err doesn't exist

-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +Aria +CSV +InnoDB +MEMORY +MRG_MyISAM +MyISAM +PERFORMANCE_SCHEMA +SEQUENCE
[--] Data in InnoDB tables: 598.2M (Tables: 153)
[OK] Total fragmented tables: 0

-------- Analysis Performance Metrics --------------------------------------------------------------
[--] innodb_stats_on_metadata: OFF
[OK] No stat updates during querying INFORMATION_SCHEMA.

-------- Views Metrics -----------------------------------------------------------------------------

-------- Triggers Metrics --------------------------------------------------------------------------

-------- Routines Metrics --------------------------------------------------------------------------

-------- Security Recommendations ------------------------------------------------------------------
[OK] There are no anonymous accounts for any database users
[OK] All database users have passwords assigned
[!!] User 'APP_BDD_LEC'@% does not specify hostname restrictions.
[!!] User 'APP_PROD'@% does not specify hostname restrictions.
[!!] User 'root'@% does not specify hostname restrictions.
[!!] There is no basic password file list!

-------- CVE Security Recommendations --------------------------------------------------------------
[--] Skipped due to --cvefile option undefined

-------- Performance Metrics -----------------------------------------------------------------------
[--] Up for: 1d 13h 59m 48s (2M q [15.055 qps], 46K conn, TX: 5G, RX: 713M)
[--] Reads / Writes: 98% / 2%
[--] Binary logging is disabled
[--] Physical Memory     : 15.5G
[--] Max MySQL memory    : 87.6G
[--] Other process memory: 0B
[--] Total buffers: 8.5G global + 66.9M per thread (1200 max threads)
[--] P_S Max memory usage: 673M
[--] Galera GCache Max memory usage: 0B
[!!] Maximum reached memory usage: 17.2G (110.81% of installed RAM)
[!!] Maximum possible memory usage: 87.6G (565.41% of installed RAM)
[!!] Overall possible memory usage with other process exceeded memory
[OK] Slow queries: 0% (11K/2M)
[OK] Highest usage of available connections: 10% (122/1200)
[OK] Aborted connections: 0.02%  (11/46918)
[!!] Query cache may be disabled by default due to mutex contention.
[OK] Query cache efficiency: 45.0% (1M cached / 3M selects)
[!!] Query cache prunes per day: 104047
[OK] Sorts requiring temporary tables: 0% (0 temp sorts / 2K sorts)
[!!] Joins performed without indexes: 2757
[!!] Temporary tables created on disk: 80% (11K on disk / 14K total)
[OK] Thread cache hit rate: 99% (386 created / 46K connections)
[OK] Table cache hit rate: 99% (643K hits / 644K requests)
[OK] table_definition_cache(400) is upper than number of tables(311)
[OK] Open file limit used: 0% (59/1M)
[OK] Table locks acquired immediately: 100% (277 immediate / 277 locks)

-------- Performance schema ------------------------------------------------------------------------
[--] Memory used by P_S: 673.6M
[--] Sys schema isn't installed.

-------- ThreadPool Metrics ------------------------------------------------------------------------
[--] ThreadPool stat is enabled.
[--] Thread Pool Size: 6 thread(s).
[--] Using default value is good enough for your version (10.3.8-MariaDB-log)

-------- MyISAM Metrics ----------------------------------------------------------------------------
[!!] Key buffer used: 18.3% (23.4M used / 128.0M cache)
[OK] Key buffer size / total MyISAM indexes: 128.0M/2.4M
[!!] Read Key buffer hit rate: 91.1% (225 cached / 20 reads)

-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[--] InnoDB Thread Concurrency: 10
[OK] InnoDB File per table is activated
[OK] InnoDB buffer pool / data size: 8.0G/598.2M
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (12.5 %): 512.0M * 2/8.0G should be equal to 25%
[OK] InnoDB buffer pool instances: 8
[--] Number of InnoDB Buffer Pool Chunk : 64 for 8 Buffer Pool Instance(s)
[OK] Innodb_buffer_pool_size aligned with Innodb_buffer_pool_chunk_size & Innodb_buffer_pool_instances
[OK] InnoDB Read buffer efficiency: 100.00% (5020763965 hits/ 5020797988 total)
[!!] InnoDB Write Log efficiency: 88.21% (138203 hits/ 156677 total)
[OK] InnoDB log waits: 0.00% (0 waits / 18474 writes)

-------- Aria Metrics ------------------------------------------------------------------------------
[--] Aria Storage Engine is enabled.
[OK] Aria pagecache size / total Aria indexes: 128.0M/0B
[OK] Aria pagecache hit rate: 99.8% (2M cached / 3K reads)

-------- TokuDB Metrics ----------------------------------------------------------------------------
[--] TokuDB is disabled.

-------- XtraDB Metrics ----------------------------------------------------------------------------
[--] XtraDB is disabled.

-------- Galera Metrics ----------------------------------------------------------------------------
[--] Galera is disabled.

-------- Replication Metrics -----------------------------------------------------------------------
[--] Galera Synchronous replication: NO
[--] No replication slave(s) for this server.
[--] Binlog format: MIXED
[--] XA support enabled: ON
[--] Semi synchronous replication Master: OFF
[--] Semi synchronous replication Slave: OFF
[--] This is a standalone server

-------- Recommendations ---------------------------------------------------------------------------
General recommendations:
    Restrict Host for 'APP_BDD_LEC'@'%' to 'APP_BDD_LEC'@LimitedIPRangeOrLocalhost
    RENAME USER 'APP_BDD_LEC'@'%' TO 'APP_BDD_LEC'@LimitedIPRangeOrLocalhost;
    Restrict Host for 'APP_PROD'@'%' to 'APP_PROD'@LimitedIPRangeOrLocalhost
    RENAME USER 'APP_PROD'@'%' TO 'APP_PROD'@LimitedIPRangeOrLocalhost;
    Restrict Host for 'root'@'%' to 'root'@LimitedIPRangeOrLocalhost
    RENAME USER 'root'@'%' TO 'root'@LimitedIPRangeOrLocalhost;
    Reduce your overall MySQL memory footprint for system stability
    Dedicate this server to your database for highest performance.
    We will suggest raising the 'join_buffer_size' until JOINs not using indexes are found.
             See https://dev.mysql.com/doc/internals/en/join-buffer-size.html
             (specially the conclusions at the bottom of the page).
    Temporary table size is already large - reduce result set size
    Reduce your SELECT DISTINCT queries without LIMIT clauses
    Consider installing Sys schema from https://github.com/mysql/mysql-sys for MySQL
    Consider installing Sys schema from https://github.com/FromDual/mariadb-sys for MariaDB
    Before changing innodb_log_file_size and/or innodb_log_files_in_group read this: https://bit.ly/2TcGgtU
Variables to adjust:
  *** MySQL's maximum memory usage is dangerously high ***
  *** Add RAM before increasing MySQL buffer variables ***
    query_cache_size (=0)
    query_cache_type (=0)
    query_cache_size (> 32M)
    join_buffer_size (> 256.0K, or always use indexes with JOINs)
    key_buffer_size (~ 24M)
    innodb_log_file_size should be (=1G) if possible, so InnoDB total log files size equals to 25% of buffer pool size.

Thank you for help

**Comment by jmrenouard** [comment]
Thanks for posting 
This is not an issue with MySQL tuner
Please refer to error log message in order to understand root cause of this failure
