### ISSUE TITLE
[Patch] Legibility and typos

### ISSUE THREAD

**Issue by longradix** [major/MySQLTuner-perl#597]
Various cosmetic updates in `diff -u` format on mysqltuner.pl script:
- Comments start with single hash, then a single white space.
- New sentences start with capital letter.
- Opening parenthesis is preceded by white space.
- No white space before colon.
- Remove blank line between consecutive closing curly braces.
- Typos.

[mysqltuner.diff.gz](https://github.com/major/MySQLTuner-perl/files/8690815/mysqltuner.diff.gz)

**Comment by jmrenouard** [comment]
Thanks @longradix
