### ISSUE TITLE
incorrectly reports roles as users without passwords

### ISSUE THREAD

**Issue by mnalis** [major/MySQLTuner-perl#598]
MySQLTuner 1.9.8 on MariaDB mariadb-server-10.3 (1:10.3.27-0+deb10u1) incorrectly reports **roles** as _users without passwords_:
 
```
[!!] User ''qa_role'@''' has no password set.
```
```
    Set up a Secure Password for 'qa_role'@'' user: SET PASSWORD FOR 'qa_role'@'' = PASSWORD('secure_password');
```

It should ignore roles (i.e. entries with `mysql.user.is_role = 'Y'`)

**Comment by jmrenouard** [comment]
Hi,

We are trying to display role profile in MySQLtuner now

**Comment by jdiazest** [comment]
Hi,
using mysql 5.7, it seems this change has broken something. Now this warning appears in my DB for all users, including root: 

[!!] User 'root'@'localhost' is an anonymous account. Remove with DROP USER 'root'@'localhost';

I don't have is_role column, so:

<pre>
 my $extra_user_condition="1 = 1 OR ";
(...)
"SELECT CONCAT(QUOTE(user), '\@', QUOTE(host)) FROM mysql.user WHERE $extra_user_condition (TRIM(USER) = '' OR USER IS NULL)";
</pre>
So it seems query executed is:

<pre>
SELECT CONCAT(QUOTE(user), '\@', QUOTE(host)) FROM mysql.user WHERE 1 = 1 OR (TRIM(USER) = '' OR USER IS NULL)
</pre>

Taking out "1 = 1 OR" part, it seems to work ok.
