### ISSUE TITLE
Opportunity for refactoring at login test

### ISSUE THREAD

**Issue by longradix** [major/MySQLTuner-perl#608]
The following two blocks look like they can be refactored?
https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L790-L803
https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L805-L818

**Comment by jmrenouard** [comment]
Hi @longradix 

Can you create a PR ?

Best regards, 
JEan-Marie

**Comment by jmrenouard** [comment]
In Readme:

Contributions welcome !
How to contribute using Pull Request ? Follow this guide : [Pull request creation](https://opensource.com/article/19/7/create-pull-request-github)

Simple steps to create a pull request:
Fork this Github project
Clone it to your local system
Make a new branch
Make your changes
Push it back to your repo
Click the Compare & pull request button
Click Create pull request to open a new pull request

**Comment by longradix** [comment]
Apologies, I am not familiar with the Perl language, hence the following untested attempt. The key line is:
`$mysqllogin = "-u $opt{user} " . (($opt{pass} ne 0) ? "-p'$opt{pass}'" : "") . $remotestring;`
[mysqltuner.diff.tar.gz](https://github.com/major/MySQLTuner-perl/files/9607290/mysqltuner.diff.tar.gz)
