### ISSUE TITLE
Deprecated configuration parameters innodb_log_file_size and/or innodb_log_files_in_group

### ISSUE THREAD

**Issue by alanmels** [major/MySQLTuner-perl#609]
This is different than https://github.com/major/MySQLTuner-perl/issues/565

When I run the script it gives the following recommendation:

> innodb_log_file_size should be (=512M) if possible, so InnoDB total log files size equals 25% of buffer pool size.

However, if I use `innodb_log_file_size` then the `/var/log/mysql/error.log` then starts complaining:

> Deprecated configuration parameters innodb_log_file_size and/or innodb_log_files_in_group have been used to compute innodb_redo_log_capacity=1073741824. Please use innodb_redo_log_capacity instead.

If I replaced it with `innodb_redo_log_capacity` the warning is gone, but then MySQLTuner keep insisting with the recommendation to use the `innodb_log_file_size`.

**Comment by 3kami3** [comment]
I think the message is coming up because MySQLTuner-perl does not support MySQL 8.0.30.

https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_dedicated_server
> Note
> innodb_log_file_size and innodb_log_files_in_group are deprecated in MySQL 8.0.30.

I think you have to ignore the message for now.

**Comment by jmrenouard** [comment]
Hi @3kami3 

I have push some PR in 2.1.8 version and this issue is fixed IHMO

Tested on MariaDB 10.6 and MySQL 8.0
Report and recommendations are more reflective about each databases
