### ISSUE TITLE
Not working on MariaDB 10.6.10 on Ubuntu 18

### ISSUE THREAD

**Issue by zoddshop** [major/MySQLTuner-perl#620]
Use of uninitialized value in concatenation (.) or string at
        /usr/bin/mysqltuner line 5391 (#1)
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (0 %): 1.0G * /8.0G should be equal 25%
Use of uninitialized value in multiplication (*) at /usr/bin/mysqltuner line
        5398 (#1)
Use of uninitialized value in concatenation (.) or string at
        /usr/bin/mysqltuner line 5471 (#1)
[--] Number of InnoDB Buffer Pool Chunk : 64 for  Buffer Pool Instance(s)
Use of uninitialized value $myvar{"innodb_buffer_pool_instances"} in int at
        /usr/bin/mysqltuner line 5474 (#1)

Illegal modulus zero at /usr/bin/mysqltuner line 5474 (#2)
    (F) You tried to divide a number by 0 to get the remainder.  Most
    numbers don't take to this kindly.

Uncaught exception from user code:
        Illegal modulus zero at /usr/bin/mysqltuner line 5474.
        main::mysql_innodb() called at /usr/bin/mysqltuner line 6021

**Comment by jmrenouard** [comment]
Hi @zoddshop 
Can you tell us your MySQLtuner version ?

Are you using last version ?

**Comment by trentstollery-millow** [comment]
Hello,
I'm having the same issue, using the most recent version.
Please see output below:

```
-------- Performance schema ------------------------------------------------------------------------
[DG] Performance schema is ON
[DG] PERFORM: SHOW ENGINE PERFORMANCE_SCHEMA STATUS
[DG] select_array: return code : 0
[--] Memory used by P_S: 72B
[DG] PERFORM: SHOW DATABASES
[DG] select_array: return code : 0
[--] Sys schema is installed.

-------- ThreadPool Metrics ------------------------------------------------------------------------
[--] ThreadPool stat is enabled.
[--] Thread Pool Size: 4 thread(s).
[--] Using default value is good enough for your version (10.6.11-MariaDB-log)

-------- MyISAM Metrics ----------------------------------------------------------------------------
[!!] Key buffer used: 18.3% (3M used / 16M cache)
[!!] Cannot calculate MyISAM index size - re-run script as root user

-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[OK] InnoDB File per table is activated
[!!] InnoDB buffer pool / data size: 23.0G/680.8G
Use of uninitialized value in concatenation (.) or string at /mysqltuner.pl
        line 5453 (#1)
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (0 %): 2.0G * /23.0G should be equal 25%
Use of uninitialized value in division (/) at /mysqltuner.pl line 5459 (#1)

Illegal division by zero at /mysqltuner.pl line 5459 (#2)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.

Uncaught exception from user code:
        Illegal division by zero at /mysqltuner.pl line 5459.
        main::mysql_innodb() called at /mysqltuner.pl line 6141
```

**Comment by jmrenouard** [comment]
Have recently try MT on MariaDB 10.10
Works perfectly well on my side ;)

Can you run it with --debug option and share us result ?

**Comment by ebonit** [comment]
I just downloaded version 2.0.11. running it foe mariadb 10.6.11 it gives the following output:

```
# perl mysqltuner.pl 
 >>  MySQLTuner 2.0.11
	 * Jean-Marie Renouard <jmrenouard@gmail.com>
	 * Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.pl/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[!!] Attempted to use login credentials from Debian maintenance account, but they failed.
```

**Comment by jmrenouard** [comment]
Last checks with MariaDB 10.6.10 (work perfectly for me)

**Comment by jmrenouard** [comment]
Hi,

There is sereval logs that tell me that you have a specific config
innodb_log_files_in_group = 0

So, i force this value to 1 so that awaited result can be calculated and divBy0 error type removed

**Comment by jmrenouard** [comment]
Thanks @zoddshop for his patience :)

IHMO, last commit will fix this issue
MysqlTuner 2.1.9
