### ISSUE TITLE
Not working Mariadb 10.10.2/Rocky Linux 9.1

### ISSUE THREAD

**Issue by linuxtudor** [major/MySQLTuner-perl#622]
[!!] InnoDB Write Log efficiency: 0% (0 hits / 0 total)
Illegal division by zero at ./mysqltuner.pl line 6157 (#1)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.

Uncaught exception from user code:
        Illegal division by zero at ./mysqltuner.pl line 6157.
        main::mysql_innodb() called at ./mysqltuner.pl line 6900

**Comment by longradix** [comment]
Can you check if the workaround at #603 works?

**Comment by linuxtudor** [comment]
Thanks, my problem solution!
