### ISSUE TITLE
Defragmentation recommendation for InnoDB tables

### ISSUE THREAD

**Issue by lewart3** [major/MySQLTuner-perl#623]
Defragmentation recommendation is always `OPTIMIZE TABLE`.

However, for InnoDB tables:
```
$ echo "OPTIMIZE TABLE foo.bar" | mysql -E
*************************** 1. row ***************************
   Table: foo.bar
      Op: optimize
Msg_type: note
Msg_text: Table does not support optimize, doing recreate + analyze instead
*************************** 2. row ***************************
   Table: foo.bar
      Op: optimize
Msg_type: status
Msg_text: OK
```

Recommendation for InnoDB tables should be `ALTER TABLE ... FORCE`:
```
$ echo "ALTER TABLE foo.bar FORCE" | mysql -E
```

Thank you!
Dan

**Comment by jmrenouard** [comment]
Hi @lewart3 

I think this command is doing awaited staff in fact:
* doing recreate + analyze instead
This means as server I'm doing this instead

But, you are also absolutely right, I will change it for InnoDB tables 

Most generic way to do it is: ALTER TABLE foo.bar ENGINE=InnoDB;

What do you think about that ?

**Comment by lewart3** [comment]
@jmrenouard Sorry, I did not see your comment before creating PR #624.

Not sure what "awaited staff" means.

What is the advantage of `ENGINE=InnoDB` vs `FORCE` ?

**Comment by jmrenouard** [comment]
@lewart3 I have check documentation related to ALTER TABLe ans FORCE is present at least since 5.5 MariaDB so it's OK for me
