### ISSUE TITLE
Argument "" isn't numeric in numeric ge (>=) at mysqltuner.pl line 329 (#1)

### ISSUE THREAD

**Issue by mikhailter** [major/MySQLTuner-perl#627]
Hi! FreeBSD 12.3 with perl 5.32 and mysql 8.0.29

perl mysqltuner.pl --debug
 >>  MySQLTuner 2.0.11
         * Jean-Marie Renouard <jmrenouard@gmail.com>
         * Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.pl/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[DG] MySQL Client: /usr/local/bin/mysql would have been started with the following arguments:
--port=3306 --socket=/tmp/mysql.sock --no-auto-rehash

[DG] MySQL Client: /usr/local/bin/mysql
[DG] /usr/local/bin/mysqladmin  ping 2>&1
[DG] MySQL FINAL Client : /usr/local/bin/mysql
[DG] MySQL Admin FINAL Client : /usr/local/bin/mysqladmin
[DG] Physical Memory: 68635041792

[DG] Swap Memory:

Argument "" isn't numeric in numeric ge (>=) at mysqltuner.pl line 329 (#1)
    (W numeric) The indicated string was fed as an argument to an operator
    that expected a numeric value instead.  If you're fortunate the message
    will identify which operator was so unfortunate.

    Note that for the Inf and NaN (infinity and not-a-number) the
    definition of "numeric" is somewhat unusual: the strings themselves
    (like "Inf") are considered numeric, and anything following them is
    considered non-numeric.

[DG] PERFORM: SELECT VERSION()
[!!] Failed to execute: SELECT VERSION()
[!!] FAIL Execute SQL / return code: 256
[DG] CMD    : /usr/local/bin/mysql
[DG] OPTIONS:
[DG] ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

[DG] select_array: return code : 256
[!!] You probably do not have enough privileges to run MySQLTuner ...

**Comment by mikhailter** [comment]
This error is shown in case of absence swap on the system.

**Comment by jmrenouard** [comment]
Code have been reinforced on this topics here: line 454
An additional back protection added  here:
https://github.com/major/MySQLTuner-perl/commit/fe573ac578158630e2fa656e5f606d85b821b67e

```

 if ( $opt{'forcemem'} > 0 ) {
        $physical_memory = $opt{'forcemem'} * 1048576;
        infoprint "Assuming $opt{'forcemem'} MB of physical memory";
        if ( $opt{'forceswap'} > 0 ) {
            $swap_memory = $opt{'forceswap'} * 1048576;
            infoprint "Assuming $opt{'forceswap'} MB of swap space";
        }
        else {
            $swap_memory = 0;
            badprint "Assuming 0 MB of swap space (use --forceswap to specify)";
        }
    }
```
