### ISSUE TITLE
Total buffers per thread wrong calculation

### ISSUE THREAD

**Issue by urtvs** [major/MySQLTuner-perl#628]
Hi
We try to solve proble with memory allocation for 1 connection
[--] Total buffers: 28.6G global + 1.0G per thread (300 max threads)

mysqltunner told us that there is 1.0G per thread
But! We make such sql query and see

MAX_MEMORY_GB - 52.6494
MAX_PER_CON - 82.7500

Why mysqltunner shows wrong info?

Maria DB 10.3.22-MariaDB

`SELECT ( @@key_buffer_size
+ @@query_cache_size
+ @@innodb_buffer_pool_size
+ @@innodb_log_buffer_size
+ @@max_connections * ( 
    @@read_buffer_size
    + @@read_rnd_buffer_size
    + @@sort_buffer_size
    + @@join_buffer_size
    + @@binlog_cache_size
    + @@thread_stack
    + @@tmp_table_size )
) / (1024 * 1024 * 1024) AS MAX_MEMORY_GB,
( 
    @@read_buffer_size
    + @@read_rnd_buffer_size
    + @@sort_buffer_size
    + @@join_buffer_size
    + @@binlog_cache_size
    + @@thread_stack
    + @@tmp_table_size ) / (1024*1024) AS MAX_PER_CON
;`

**Comment by jr-timme** [comment]
`mysqltuner` does not take `tmp_table_size` into account. Another variable which is included in the calculation however is `max_allowed_packet`:

https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L2657-L2665
```perl
    # Per-thread memory
    if ( mysql_version_ge(4) ) {
        $mycalc{'per_thread_buffers'} =
          $myvar{'read_buffer_size'} +
          $myvar{'read_rnd_buffer_size'} +
          $myvar{'sort_buffer_size'} +
          $myvar{'thread_stack'} +
          $myvar{'max_allowed_packet'} +
          $myvar{'join_buffer_size'};
    }
```

**Comment by jmrenouard** [comment]
Issue fixed with last PR: Fixing wrong calculation in memory usage (regression found) #679

Thanks for your patience and reporting this issue
 @jmrenouard
