### ISSUE TITLE
innodb_buffer_pool_size recommendation can be to high on 32-bit systems

### ISSUE THREAD

**Issue by pattyland** [major/MySQLTuner-perl#634]
I get the following recommendation from MySQLTuner:

`innodb_buffer_pool_size (>= 17.6G) if possible.`

I know, "possible" is an elastic term but on 32-bit systems, which are also recognized, the specification must not be so large, otherwise there is the following error message in the MySQL log:

`[ERROR] innodb_buffer_pool_size can't be over 4GB on 32-bit systems`

**Comment by jmrenouard** [comment]
OK, can you give us expected behabiour in this specific case ?

**Comment by pattyland** [comment]
A good question indeed! There are many criteria for the perfect recommendation for innodb_buffer_pool_size but I think 2 restrictions are easy to implement: The limitation on 32-bit devices and the generally available memory.

"You should set innodb_buffer_pool_size to XGB but you can't because you have a 32-bit system" would probably be too long an output. 
Maybe a generic message like "set innodb_buffer_pool_size should be >= 17.6G but your limit is XGB" would be better, I think the people who run a MySQL server themselves will quickly figure out what criteria resulted in this limit.

**Comment by jmrenouard** [comment]
Last version is taking into account this issue for 32 bit architectures
