### ISSUE TITLE
What about Mysql 5.6?

### ISSUE THREAD

**Issue by shawnholt** [major/MySQLTuner-perl#64]
If this is not longer supported, is there another suggested resource?  Thanks.

**Comment by morrow95** [comment]
Same question - 5.6.23 here myself.

**Comment by major** [comment]
I hope to get a look at this soon. It's not unsupported but there might be an issue parsing the version number.

**Comment by morrow95** [comment]
So if there was an issue parsing the version number how would that affect things?  I guess I am asking if it is safe to run and will it run as intended?

**Comment by jmrenouard** [comment]
I am personally using MySQL 5.6.24 version and I don't have any issues about it.

I think a global checks can be perform to catch what's can be improve but current indicators work pretty well.

**Comment by jmrenouard** [comment]
MySQL 5.6.x is supported and in current version used for basic tests on my dev PC.

MySQL 5.5/5.6 and MariaDB 10.1 are currently supported.
We have added innodb_buffer_pool_instances calculations which is a 5.5+ MySQL parameter and some performance_schema SQL request.
For instance, performance have been activated by default in 5.6.20 version.

Best regards,
