### ISSUE TITLE
Bug in Tuner variables to change

### ISSUE THREAD

**Issue by zoddshop** [major/MySQLTuner-perl#651]
I've already set cache size and cache type to 0. My join Buffer size is 2M. But look at the results.

Variables to adjust:
    query_cache_size (=0)
    query_cache_type (=0)
    query_cache_size (> 16M)
    join_buffer_size (> 512B, or always use indexes with JOINs)

Its saying conradictory things as well as not recognizing the variables I already set. Do I need to define something to use Indexes with joins in mysql config?

**Comment by jmrenouard** [comment]
Yes I see I see :)

Can you tell me more about your version (MySQL/MariaDB) ?

**Comment by jmrenouard** [comment]
Hi @zoddshop 

So, I see two issues here:
1°   query_cache_size with two different values to adjust
2° join_buffer_size detection with wrong value (2m settings vs 512B detected)

**Comment by bitcoinvero** [comment]
correct.

**Comment by zoddshop** [comment]
yes these are the issues indeed. not only that but
3. query_cache_size always says set to  0 even when alraedy set to 0

**Comment by jmrenouard** [comment]
Hi @zoddshop 

Your query_cache_prunes_per_day is > 98 so you got 2 messages:
1° disable query cache
2° Setup good size for query cache

I have fixed this issue
You shouldn't have two message for query_cache_size now since #666
