### ISSUE TITLE
Document the action to take to solve detected issue

### ISSUE THREAD

**Issue by ProceduralMan** [major/MySQLTuner-perl#656]
On the issue marked as [!!]

-------- Kernel Information Recommendations --------------------------------------------------------
[--] Information about kernel tuning:
[--] 	fs.aio-max-nr = 65536
[--] 	fs.aio-nr = 2561
[--] 	fs.file-max = 9223372036854775807
[--] 	vm.swappiness = 10
[--] Swappiness is < 10.
[--] TCP slot entries is > 100.
[!!] Max running total of the number of events is < 1M, please consider having a value greater than 1M

No amount of search has been enough to discover which system variable controls "Max running total of the number of events"

Some hint is definitely needed

**Comment by longradix** [comment]
It is a system wide setting: https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html#id1

You can check (and change) its values via:
```
$ cat /proc/sys/fs/aio-*
65536
2305

```

**Comment by jmrenouard** [comment]
Fixed with last PR #669
