### ISSUE TITLE
Newer versions of mysql ignore innodb_log_file_size, recommend innodb_redo_log_capacity instead.

### ISSUE THREAD

**Issue by elyograg** [major/MySQLTuner-perl#657]
Running the master branch version of mysqltuner against mysql-community-server version 8.0.33-1ubuntu22.04, I get this recommendation:

```
    innodb_log_file_size should be (=512M) if possible, so InnoDB total log file size equals 25% of buffer pool size.
```

But if I add that to my config, I then get warnings in the error log saying that innodb_log_file_size is being ignored and to use innodb_redo_log_capacity instead.  I have gone with their recommendation.

When will mysqltuner be updated to properly deal with this change in mysql?

**Comment by jmrenouard** [comment]
Hi @elyograg 

Yes we have changed this parameter in calculation formula but we forgot to change variables name into recommandations part

Thanks for your feedback

**Comment by jmrenouard** [comment]
Fixed
