### ISSUE TITLE
Attempted to use login credentials from Plesk, but they failed

### ISSUE THREAD

**Issue by Ghost-nsk** [major/MySQLTuner-perl#66]
It didn't asked for password. How to fix?

[root@dev ~]# perl mysqltuner.pl

 >>  MySQLTuner 1.4.0 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
[!!] Attempted to use login credentials from Plesk, but they failed.

**Comment by jmrenouard** [comment]
giving a password as password is  unsecured. Dixit Oracle.
As describe in the main page (README.md), use .my.cnf or mysql_config_editor for secure password storage.

**Comment by jmrenouard** [comment]
We don't known how to fix it because we don't have an plesk plateform.

Sorry,
could you tell us more about it ?

Thks

**Comment by myTepee** [comment]
On Plesk versions 8.x and 9.x admin password is stored at ````/etc/psa/.psa.shadow````

Since Plesk 10, location is the same, but crypted.
To have it uncrypted MySQLTuner should run :

Linux :
````/usr/local/psa/bin/admin --show-password````

Windows :
```` %plesk_bin%\plesksrvclient --get````

**Comment by myTepee** [comment]
See also http://download1.parallels.com/Plesk/Doc/ru-RU/online/plesk-linux-advanced-administration-guide/index.htm?fileName=68745.htm#o68779

**Comment by jmrenouard** [comment]
@myTepee thnk you for this precision.

We don't have any platform for testing such feature.

Is there anybody can provide us this kind of platform with several versions ?

Thanks by advance,

**Comment by jmrenouard** [comment]
Developers that can patch Pleck connection code are welcome !

Code to change is in the subroutine mysql_setup line 316
and specific Plesk code is line 393

I also open a issue #87 because we would like to know if Mysql windows version is worked as well.

**Comment by jmrenouard** [comment]
how do you get the plesk version in command line ?

**Comment by json-m** [comment]
does `perl mysqltuner.pl --user admin --pass `cat /etc/psa/.psa.shadow`` not work? remember root can not be used in the case of plesk.

**Comment by jmrenouard** [comment]
Is anyone have a plesk plateform to change and validate this feature ?
It doesn't seem to be complicated but I don't have this type of plateform for test ?

**Comment by jmrenouard** [comment]
Is this issue doesn't interested anybody ?

If Plesk authentication in mysqltuner is not interesting anymore, what about removing this support ?


Thnaks for your feedback.

**Comment by jmrenouard** [comment]
Hi @Ghost-nsk @json-m @myTepee,

Is someone can summurize me command to get it works ?

Thanks by advance,

**Comment by json-m** [comment]
@jmrenouard 

```
mysql -uadmin -p`cat /etc/psa/.psa.shadow`
```

**Comment by jmrenouard** [comment]
So, I think all is working fine because code is based on this formula.
@Ghost-nsk @json-m @myTepee,
can you confirm all Plesk box version works with command in the previous comment ?

**Comment by jmrenouard** [comment]
So, I think all is working fine because code is based on this formula.
@Ghost-nsk @json-m @myTepee,
can you confirm all Plesk box version works with command in the previous comment ?

**Comment by jmrenouard** [comment]
Hi @Ghost-nsk @json-m @myTepee

I closed this ticket because I don't get your feedback.

Feel free to reopen it if necessary or open a new ticket on Plesk connexions issue.

Thanks for your support.

**Comment by sylvio5** [comment]
Hello if someone is interested the correct use with plesk is : 
`perl mysqltuner.pl --user admin --pass `cat /etc/psa/.psa.shadow``
