### ISSUE TITLE
Incorrect log-file association when checking remote host

### ISSUE THREAD

**Issue by jesusbagpuss** [major/MySQLTuner-perl#661]
I realise that this may be a bit niche, but it confused me somewhat before working out what was happening.

ServerA (linux) - has perl + required modules installed to run the script. It also happens to have a mysql server installed/running.
ServerB (Windows) - running an instance of MySQL I want to analyse.

Running the script on ServerA using e.g.
`perl mysqltuner.pl --host ServerB --user X --pass XX --forcemem 1000` 
will return some recommendations about log files that exist on Server A.

Sample output (running with `--debug`):
```

 >>  MySQLTuner 2.1.1
...
[DG] V: datadir = C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Data\\
...
[DG] V: log_error = .\\SERVER-B.err
...
[OK] Currently running supported MySQL version 8.0.16

-------- Log file Recommendations ------------------------------------------------------------------
[OK] Log file /var/log/mysqld.log exists
[--] Log file: /var/log/mysqld.log (46M)
[OK] Log file /var/log/mysqld.log is not empty
[!!] Log file /var/log/mysqld.log is bigger than 32 MB
[OK] Log file /var/log/mysqld.log is readable.
...
```
As I was analysing a MySQL instance on a Windows server, it was (eventually) obvious what was happening - as the log paths didn't make any sense.

A fix for the log files could include a check of `$doremote` in https://github.com/major/MySQLTuner-perl/blob/f27541682db4865952af987f808c65326d3d6ecf/mysqltuner.pl#L1410 to govern which files/paths to consider. 

I think there may be other parts of the script that suffer from a similar issue e.g.
https://github.com/major/MySQLTuner-perl/blob/f27541682db4865952af987f808c65326d3d6ecf/mysqltuner.pl#L450 - which appears to check the server-running-the-tests rather than reporting (or skipping) tests run on the remote server.

**Comment by jmrenouard** [comment]
Fixed with #665
