### ISSUE TITLE
Bad options behaviour

### ISSUE THREAD

**Issue by j75** [major/MySQLTuner-perl#662]
1. `mysqltuner.pl --user <user> --pass <password> --reportfile /tmp/toto` issues the following error: 
> Can't locate object method "new" via package "Text::Template" at
> 	/.../mysqltuner.pl line 6871 (#1)
>     (F) You called a method correctly, and it correctly indicated a package
>     functioning as a class, but that package doesn't define that particular
>     method, nor does any of its base classes.  See perlobj.
> Uncaught exception from user code:
> 	Can't locate object method "new" via package "Text::Template" at /.../mysqltuner.pl line 6871.
> 	main::dump_result() called at /.../mysqltuner.pl line 6969
2.  `mysqltuner.pl --user <user> --pass <password> --outputfile /tmp/toto.json --json --silent` => the **silent** option seems not to have any effect (i.e. messages are still displayed)

The script version is the latest (from the **master** branch).

**Comment by jmrenouard** [comment]
Perl Module Text::Template is required for report file
You can use your own personal template in this mode

You can try --json and redirect output into file from the command line or use --outputfile option if needed
