### ISSUE TITLE
Version 2.2.0 issues

### ISSUE THREAD

**Issue by Lofesa** [major/MySQLTuner-perl#686]
Hi
I tried the lates version in this environment
OS Almalinux 9
Plesk 18.0.53 Update 2
MariaDB 10.5.16-MariaDB

Issues:
Ram:  [--] Physical Memory     : 1.0G The server has  Mem:  62Gi

Tables 
Recomendation Ensure that all table(s) are InnoDB tables for performance and also for replication
But the detected tables are type ENGINE = MEMORY.  This table type is a temporary one,, so should temporary in ram tables be reported here?

Columns:
Recomendation Ensure that all text colums(s) are UTF-8 compliant for encoding support and performance

But some columns are utf8
[!!]    DB-USER,TABLE-NAME,meta_key,utf8,utf8_general_ci,varchar,255

**Comment by jmrenouard** [comment]
Hi @jadeops 
I think there is a bug I will fix it

**Comment by jmrenouard** [comment]
Memory table type are not good enough

I fact, this kind of table are placing table lock instead of row locks crating contention

IHMO, INNODB with appropriate Buffer Pool will be better

**Comment by Lofesa** [comment]
Well... some times the user has no, or poor, control over these things.
This case is related to wordpress plugins that uses memory tables in a transient operation, it creates the table do their stuuf and then delete it. The purpose is not only have the data in ram memory but treat it as a "efimeral" data structure  with less cost than create a innodb table then destroy it, create again then destroy it again...
But that's my point of view, not necesarly the better..
