### ISSUE TITLE
Memory Tables out of sugestion to make Innodb tables

### ISSUE THREAD

**Issue by Lofesa** [major/MySQLTuner-perl#689]
As sugested by @jmrenouard  in this  comment  [#686 ](https://github.com/major/MySQLTuner-perl/issues/686#issuecomment-1607031919) I open this issue to track if memory tables should be sugested to convert it to innodb

**Comment by jmrenouard** [comment]
Bad message for Memory Table
Table $badtable is a MEMORY table. It's suggested to use only InnoDB tables in production
