### ISSUE TITLE
New issue 2.2.1

### ISSUE THREAD

**Issue by Lofesa** [major/MySQLTuner-perl#690]
[OK] InnoDb Buffer Pool size ( 37.0G ) under limit for 64 bits architecture: (17179869184.0G )
[OK] InnoDB buffer pool / data size: 0B / 34.2G

1st line report the pool size, in the 2nd one it report with 0

**Comment by jmrenouard** [comment]
An other question: Do you get any InnoDB table ? do you setup InnoDB buffer pool size ?

**Comment by Lofesa** [comment]
Forgot to close this grr... no my better day

**Comment by Lofesa** [comment]
Definetivelly not my day, I closed this thinking are in other issue.

Database version [OK] Currently running supported MySQL version 10.5.16-MariaDB-log

From the last run I've done

-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[--] InnoDB Thread Concurrency: 0
[OK] InnoDB File per table is activated
[OK] InnoDb Buffer Pool size ( 37.0G ) under limit for 64 bits architecture: (17179869184.0G )
[OK] InnoDB buffer pool /data size: 0B / 34.2G
[OK] Ratio InnoDB log file size / InnoDB Buffer pool size: 9.2G * 1/37.0G should be equal to 25%
[--] Number of InnoDB Buffer Pool Chunk: 296 for 1 Buffer Pool Instance(s)
[OK] Innodb_buffer_pool_size aligned with Innodb_buffer_pool_chunk_size & Innodb_buffer_pool_instances
[OK] InnoDB Read buffer efficiency: 99.99% (8752837801 hits / 8753903658 total)
[!!] InnoDB Write Log efficiency: 319.31% (129715 hits / 40623 total)
[OK] InnoDB log waits: 0.00% (0 waits / 170338 writes)

**Comment by Lofesa** [comment]
Found it. there are 1 malformed line here

https://github.com/major/MySQLTuner-perl/blob/f585e6ad2d5c598bd03a501e62775a50dce97745/mysqltuner.pl#L6256-L6259

The variable innodb_buffer_pool_size is not in the hr_bytes

**Comment by jmrenouard** [comment]
Hi @Lofesa 

this issue is fixed by PR #700
