### ISSUE TITLE
More issues in 2.2.1

### ISSUE THREAD

**Issue by Lofesa** [major/MySQLTuner-perl#691]
Ensure that all text colums(s) are UTF-8 compliant for encoding support and performance
And the list of tables columns, with or without utf8 still be displayed

As reference this issue #686

**Comment by jmrenouard** [comment]
Hi @Lofesa 
Can you send us output examples ?
I don't get same result on my side

**Comment by Lofesa** [comment]
Sorry, my bad. I mixed output. In version 2.2.1 all reported tables are non utf8

**Comment by Lofesa** [comment]
Definetivelly not my day, I closed this thinking are in other issue.

**Comment by Lofesa** [comment]
Definetively not my best day
