### ISSUE TITLE
InnoDB Read buffer efficiency: reported as negative after mariadb restart

### ISSUE THREAD

**Issue by FabioPedretti** [major/MySQLTuner-perl#694]
```
-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[OK] InnoDB File per table is activated
[OK] InnoDb Buffer Pool size ( 512.0M ) under limit for 64 bits architecture: (17179869184.0G )
[OK] InnoDB buffer pool / data size: 0B / 316.3M
[OK] Ratio InnoDB log file size / InnoDB Buffer pool size: 128.0M * 1/512.0M should be equal to 25%
[--] Number of InnoDB Buffer Pool Chunk: 64 for 1 Buffer Pool Instance(s)
[OK] Innodb_buffer_pool_size aligned with Innodb_buffer_pool_chunk_size & Innodb_buffer_pool_instances
[!!] InnoDB Read buffer efficiency: -868.02% (-5972 hits / 688 total)
[!!] InnoDB Write Log efficiency: 60% (3 hits / 5 total)
[OK] InnoDB log waits: 0.00% (0 waits / 2 writes)
```
Also, maybe due to this, **General recommendations** gives the advice about changing innodb_log_file_size, but **Variables to adjust** doesn't mention any innodb_log_file_size sugesstion:

```
General recommendations:
 ...
 Before changing innodb_log_file_size and/or innodb_log_files_in_group read this: https://bit.ly/2TcGgtU
```

**Comment by jmrenouard** [comment]
Hi @FabioPedretti 

As explained in USAGE
Allow MySQL server to run for at least 24-48 hours before trusting suggestions

I will close this issue because MT is not suitable for this kind of situation

IHMO, be patient :)

**Comment by adaugherity** [comment]
IMHO this is still a bug -- values may not be accurate initially, as is noted in the output, but a negative efficiency is preposterous and leads the DBA to worry they may have misconfigured something.

I would think clamping it to 0 in that case would make sense.
