### ISSUE TITLE
Option --port doesn't seem to work

### ISSUE THREAD

**Issue by H0w4rd** [major/MySQLTuner-perl#705]
I have two MariaDB instances on the ports 3306 and 3307.

When I run `myqltuner.pl --port 3307`, it still connects to the instance on the port 3306.

I can even enter any random port number, it still connects to 3306.

**Comment by jmrenouard** [comment]
Hi @H0w4rd 

I think that you should try to setup --host option with --port option

This method works fine for me :)

**Comment by jmrenouard** [comment]
hi  @H0w4rd
 @leonyu send us a PR #731 do you think this can solve our issue ?

**Comment by jmrenouard** [comment]
I think using host option will solve this issue
