### ISSUE TITLE
Inconsistency in option behaviour

### ISSUE THREAD

**Issue by FabioPedretti** [major/MySQLTuner-perl#706]
Continuing from https://github.com/major/MySQLTuner-perl/issues/702#issuecomment-1624920192

structstat is no longer enabled by default, while myisamstat it is.

Is that intended?

The code indeed shows:
```
$opt{structstat} = 0
$opt{myisamstat} = 1
```
but the help text shows the same syntax for both:
```
 --nostructstat              Don't print table structures information
 --nomyisamstat              Don't print MyIsam information
```

**Comment by jmrenouard** [comment]
Hi @FabioPedretti 

Yes, we have a recent issue for @FabioPedretti (yourself) telling us that in large database models, this feature took a lot of time to compute
https://github.com/major/MySQLTuner-perl/issues/695

So, we disable it by default :)

**Comment by FabioPedretti** [comment]
Yes, my point was to update the help text, so to reflect what it is enabled by default and what not.

So from:

```
--nostructstat              Don't print table structures information
--nomyisamstat              Don't print MyIsam information
```

```
--structstat                Print table structures information
--nomyisamstat              Don't print MyIsam information
```
Thanks.
