### ISSUE TITLE
Illegal division by zero at /usr/bin/mysqltuner line 5563 (#2) on Ubuntu Server 20.04 Raspberry Pi aarch64

### ISSUE THREAD

**Issue by Danrancan** [major/MySQLTuner-perl#711]
I have downloaded mysqltuner from the default Ubuntu 20.04 apt repository for Raspberry Pi 4 (aarch64). `Mysqltuner -v `outputs `MySQLTuner 1.7.13 - Major Hayden <major@mhtx.net>`. When I run it, midway through analysis, I get the following error:

```
Illegal division by zero at /usr/bin/mysqltuner line 5563 (#2)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.

Uncaught exception from user code:
	Illegal division by zero at /usr/bin/mysqltuner line 5563.
	main::mysql_innodb() called at /usr/bin/mysqltuner line 6272
```

Then the scripts stops. I'm not sure what this means but hopefully you can give me a quick fix for this and then add it to an Ubuntu (aarch64) update. Let me know what I can do.

**Comment by jmrenouard** [comment]
Hi @Danrancan 
Can you use a recent version ?
This version gets a lot of bug fixed since

**Comment by jmrenouard** [comment]
No patch for this version
