### ISSUE TITLE
Join Buffer Size recommendation Link Broken

### ISSUE THREAD

**Issue by Staubiii** [major/MySQLTuner-perl#722]
We got the following recommendation:
```
We will suggest raising the 'join_buffer_size' until JOINs not using indexes are found.
See https://dev.mysql.com/doc/internals/en/join-buffer-size.html
(specially the conclusions at the bottom of the page).
```
But we noticed that the link https://dev.mysql.com/doc/internals/en/join-buffer-size.html nowadays redirects to https://dev.mysql.com/doc/dev/mysql-server/latest/.

I did not find a new version of the page but the archived one can be found here:

https://web.archive.org/web/20220818201005/https://dev.mysql.com/doc/internals/en/join-buffer-size.html

**Comment by jmrenouard** [comment]
Changing to link to parameter info instead
     push(
            @generalrec,
"We will suggest raising the 'join_buffer_size' until JOINs not using indexes are found.
             See https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_join_buffer_size"
        );

**Comment by jmrenouard** [comment]
Hi @Staubiii 
I consider this issue fixed
No more valuable link present

An other option consists in removing this link
