### ISSUE TITLE
Bugs in today's version

### ISSUE THREAD

**Issue by gmt-it** [major/MySQLTuner-perl#729]
Hello.
I have the following errors with today's release:

Use of uninitialized value in multiplication (*) at /usr/bin/mysqltuner line
        2705 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

Use of uninitialized value in concatenation (.) or string at
        /usr/bin/mysqltuner line 5614 (#1)
Use of uninitialized value in division (/) at /usr/bin/mysqltuner line 5621 (#1)

Illegal division by zero at /usr/bin/mysqltuner line 5621 (#2)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.

Uncaught exception from user code:
        Illegal division by zero at /usr/bin/mysqltuner line 5621.
        main::mysql_innodb() called at /usr/bin/mysqltuner line 6353

**Comment by jmrenouard** [comment]
Thanks for reporting

Can you give us more feedback ?

MySQL tuner version
MySQL/MariaDB version 
More useful information

**Comment by jmrenouard** [comment]
@gmt-it can you give us more feedback ? :)

**Comment by jmrenouard** [comment]
No more feedback
I close this issue feel free to give us more feddback and repoen it
