### ISSUE TITLE
`1Go`??

### ISSUE THREAD

**Issue by leonyu** [major/MySQLTuner-perl#730]
> MySQL needs 1 instance per 1Go of Buffer Pool
> innodb_buffer_pool instances = round(innodb_buffer_pool_size / 1Go)

What is `1Go`?

**Comment by jmrenouard** [comment]
Hi @leonyu 

On previous version, instances were dedicated for managing part of InnoDB Buffer Pool

A rule of thumb indicates one instance per Go of InnoDB Buffer Pool

Nowadays, this parameter is deprecated and managed internally

**Comment by leonyu** [comment]
So `1 Go` is `1000000000 objects`?
