### ISSUE TITLE
Check error line(s) false positive

### ISSUE THREAD

**Issue by qeepcologne** [major/MySQLTuner-perl#741]
mysql tuner reports (tested with mysql 8.1.0)

```
    Check warning line(s) in /var/log/mysql/error.log file
    Check error line(s) in /var/log/mysql/error.log file
```
but there is no error line in error.log file

i checked log and error is from the following line:
```
2023-10-24T12:39:50.553537Z 0 [Warning] [MY-010915] [Server] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
```
(if i remove this line manually the check error line(s) disappears)

i think because ERROR is inside the log line.
Please change the check from ERROR to [ERROR].
Please check also if the same problem exists for other log levels e.g. Warning => [Warning] ?

**Comment by jmrenouard** [comment]
Thanks for reporting @qeepcologne
