### ISSUE TITLE
Perfermance scheme update to mariadb >10.x

### ISSUE THREAD

**Issue by spirillen** [major/MySQLTuner-perl#747]
Request:

would it be possible to have the performance_scheme updated to match Mariadb >=11.X ([Optional Performance schema and Sysschema installation for MariaDB < 10.6](https://github.com/major/MySQLTuner-perl#optional-performance-schema-and-sysschema-installation-for-mariadb--106)) as the `< 10.6` are returning an error do to a change on the way MariaDB handles `STATUS`

```sql
ERROR 1054 (42S22) at line 78 in file: './views/p_s/metrics_56.sql': Unknown column 'STATUS' in 'field list'
```

**Comment by jmrenouard** [comment]
Last readme version include documentation around this topics

In fact, error in mariadb_sys is related to issue from sysschema project not MySQLtuner project

**Comment by spirillen** [comment]
Thanks
