### ISSUE TITLE
New CLI-Option "nondedicated" for non-dedicated servers

### ISSUE THREAD

**Issue by Staubiii** [major/MySQLTuner-perl#748]
MySQLTuner always assumes a server is dedicated to running MySQL and will give recommendations that don't make sense for a non-dedicated server. 

Such messages include:

> Consider stopping or dedicate server for additional process other than mysqld.
> DON'T APPLY SETTINGS BECAUSE THERE ARE TOO MANY PROCESSES RUNNING ON THIS SERVER. OOM KILL CAN OCCUR!

Since we dont host dedicated database servers we always have to ignore these irrelevant recommendations among the other useful ones.

It would be nice if MySQLTuner could ignore these recommendations through a new CLI option, e.g. `nondedicated`. If set, all recommendations relating to dedicated servers would not be given.

How to reproduce:
Having a server with MySQL, on which at least 15% of the memory is used by other processes than the database server, i.e. a backup software and/or a web application.

If this feature ends up being implemented I would be happy to help test it.

**Comment by jmrenouard** [comment]
hi @Staubiii 
Can you test --nondedicated option ?

**Comment by Staubiii** [comment]
@jmrenouard works perfectly.

Thank you!
