### ISSUE TITLE
ERROR 1267 (HY000) at line 1: Illegal mix of collations (latin1_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='

### ISSUE THREAD

**Issue by devisbal** [major/MySQLTuner-perl#75]
The following query at line 497 mysqltuner Version 1.4.3 with Currently running supported MySQL version 5.5.42-cll give error due to COLLATION

SELECT CONCAT(user, '\@', host) FROM mysql.user WHERE password = PASSWORD(user) OR password = PASSWORD(UPPER(user)) OR password = PASSWORD(UPPER(LEFT(User, 1)) + SUBSTRING(User, 2, LENGTH(User)));

ERROR 1267 (HY000): Illegal mix of collations (latin1_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='

I change it for:
SELECT CONCAT(user, '\@', host) FROM mysql.user WHERE CAST(password as Binary) = PASSWORD(user) OR CAST(password as Binary) = PASSWORD(UPPER(user)) OR CAST(password as Binary) = PASSWORD(UPPER(LEFT(User, 1)) + SUBSTRING(User, 2, LENGTH(User)));

**Comment by major** [comment]
I believe this was fixed in #71.

**Comment by devisbal** [comment]
No, the problem is still present.

**Comment by cloos** [comment]
#71 only fixed fetching memory values from Linux systems on the OS level.

Looking into the mysql.user table shows that the User column and the Password column have different collations:
```
`User` char(16) COLLATE utf8_bin NOT NULL DEFAULT '',
`Password` char(41) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
```

**Comment by jmrenouard** [comment]
Fix is committed.
