### ISSUE TITLE
Argument "" isn't numeric in numeric lt 

### ISSUE THREAD

**Issue by ToterEngel** [major/MySQLTuner-perl#753]
Since version 2.5.2:

[OK] InnoDB buffer pool / data size: 4.0G / 206.1M
Argument "" isn't numeric in numeric lt (<) at ./mysqltuner.pl line 6375 (#1)
    (W numeric) The indicated string was fed as an argument to an operator
    that expected a numeric value instead.  If you're fortunate the message
    will identify which operator was so unfortunate.
    
    Note that for the Inf and NaN (infinity and not-a-number) the
    definition of "numeric" is somewhat unusual: the strings themselves
    (like "Inf") are considered numeric, and anything following them is
    considered non-numeric.

**Comment by jmrenouard** [comment]
Hi @ToterEngel 
Duplicated with #759
