### ISSUE TITLE
Query Cache Size warning only displays when query_cache_size is already > 128MB

### ISSUE THREAD

**Issue by StephenButcher** [major/MySQLTuner-perl#76]
I ran mysqltuner.pl on one of my instances, and got this result.
`General recommendations:`
`    Run OPTIMIZE TABLE to defragment tables for better performance`
`    Increase table_open_cache gradually to avoid file descriptor limits`
`    Read this before increasing table_open_cache over 64: http://bit.ly/1mi7c4C`
`Variables to adjust:`
`    query_cache_size (> 128M)`
`    table_open_cache (> 128)`
`    innodb_buffer_pool_size (>= 4G)`

The warning `Increasing the query_cache size over 128M may reduce performance` did not display.

I recommend changing line 921 from:
`if ($myvar{'query_cache_size'} > 128*1024*1024) {`
to
`if ($myvar{'query_cache_size'} >= 128*1024*1024) {`

**Comment by jmrenouard** [comment]
Thanks for your reply.

The best way is to calculate QCache Hits ratio and then advice increasing or decreasing value.

**Comment by jmrenouard** [comment]
Changes has been made in code.

**Comment by jmrenouard** [comment]
commit #82
