### ISSUE TITLE
Defective interpreter (/bin/env) starting 2.5.2 update

### ISSUE THREAD

**Issue by bcutter** [major/MySQLTuner-perl#761]
Once updated from 2.2.12 to https://github.com/major/MySQLTuner-perl/releases/tag/v2.5.2, when running

`./mysqltuner.pl --host localhost --forcemem 3950 --forceswap 3950`

I get

> bash: ./mysqltuner.pl: /bin/env: Defekter Interpreter: Datei oder Verzeichnis nicht gefunden

_(translating `bash: ./mysqltuner.pl: /bin/env: Defective interpreter: File or directory not found`_

Please assist on which details to provide or on how to fix this.

**Comment by C0RD** [comment]
replace the first line in mysqltuner.pl with #!/usr/bin/perl

**Comment by jmrenouard** [comment]
Hi @C0RD 

using #!env perl 
this seems to be a good alternative for specific perl path installation correct handling solution

**Comment by jmrenouard** [comment]
Shebang is fixed since last commit

**Comment by C0RD** [comment]
Thats fine. 

As a side node, on Debian Policy it is

> In the case of Perl scripts this should be #!/usr/bin/perl.

(https://www.debian.org/doc/debian-policy/ch-files.html#scripts)

But this will be replaced during package build.
