### ISSUE TITLE
MariaDB 11.4.2 (LTS) support

### ISSUE THREAD

**Issue by datgausaigon** [major/MySQLTuner-perl#786]
Hi, 

MariaDB has a new LTS version for 11.x, 11.4.2.

Are you compatible with MariaDB 11.4.2? If not, please update.

I'm using AlmaLinux 8.10 and MariaDB 11.4.2 on multiple new servers. And are migrating old servers to this new environment. I would be very grateful if you are compatible with MariaDB 11.4.2.

Thanks ❤️

**Comment by zag2me** [comment]
MySQL also has new 9.01 version

**Comment by jmrenouard** [comment]
Hi @zag2me @datgausaigon 
https://github.com/major/MySQLTuner-perl/releases/tag/v2.6.0
