### ISSUE TITLE
MariaDB 11.2.4 - MySQLTuner 2.5.2

### ISSUE THREAD

**Issue by stevefxp1** [major/MySQLTuner-perl#790]
Hello all,

I am running MariaDB 11.2.4 on Ubuntu 24.04. 

I am getting a number of errors when I run MySQLTuner:

1) Failed to execute: select  round( 100* sum(allocated)/( select VARIABLE_VALUE FROM performance_schema.global_variables WHERE VARIABLE_NAME='innodb_buffer_pool_size' ) ,2)FROM sys.x\$innodb_buffer_stats_by_table;
2) Your MySQL version 11.2.4-MariaDB-ubu2404 is EOL software. Upgrade soon!

I just installed 11.2.4. Where should I go to so that this does not come up? I thought 11.2 was a LTS version of MariaDB.

[zabbixm01_mysqltuner.txt](https://github.com/user-attachments/files/16242333/zabbixm01_mysqltuner.txt)

**Comment by stevefxp1** [comment]
Ok a few more points...

1) I went back to Ubuntu 22.04.4 and still getting the failed to execute error but its now showing a fail execute SQL / return code: 256

**Comment by Neurozone** [comment]
Same issue for point 2 here.

I'm a dba and can confirm that 11.4.2 version is a supported one, see here : https://mariadb.com/kb/en/mariadb-11-4-2-release-notes/

Release date: 29 May 2024

MariaDB 11.4 is the current long-term series of MariaDB and will be maintained until May 2029. It is an evolution of MariaDB 11.3 with several entirely new features.

MariaDB 11.4.2 is a Stable (GA) release.

By the way : mysqltuner.pl is a good tool to guide people

**Comment by stevefxp1** [comment]
Thanks...I got it mixed up...dyslexia here! 

What about the failed to execute error that shows up on my output?

**Comment by stevefxp1** [comment]
Well it looks like this error is fixed with the v2.5.4 of the script.
