### ISSUE TITLE
Unitialized Value

### ISSUE THREAD

**Issue by stevefxp1** [major/MySQLTuner-perl#806]
Hello all,

Since I got the new version of 2.61 I am getting the following error message in the attached screenshot. What is this and is everyone seeing this?

Thanks,
Steve
![Screenshot 2024-11-11 102307](https://github.com/user-attachments/assets/184b5181-6436-499a-9bda-5e0918033328)

**Comment by ckujau** [comment]
Happens here too, with Perl `5.36.0-7+deb12u1 `:

```
$ mysqltuner.pl > /dev/null
Use of uninitialized value $opt{"prettyicon"} in numeric ne (!=) at
        /usr/local/sbin/mysqltuner.pl line 236 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.
    
    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    and the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.
```
Version 2.6.0 (e.g. commit 1b9c8e5) doesn't have this warning.

**Comment by ckujau** [comment]
Rat's should've bisected before commenting:

```
$ git bisect bad
b189c548811f0b0f36451d470dfcb1e8b8982ca9 is the first bad commit
commit b189c548811f0b0f36451d470dfcb1e8b8982ca9
Author: Jean-Marie Renouard <jmrenouard@gmail.com>
Date:   Fri Nov 8 18:09:18 2024 +0100

    New version with icons and supported versions files

 CURRENT_VERSION.txt |  2 +-
 Makefile            |  8 +++++++-
 README.md           | 24 +++++++++---------------
 build/endoflife.sh  | 36 ++++++++++++++++++++++++++++++++++++
 mysqltuner.pl       | 24 +++++++++++++++++++-----
 5 files changed, 72 insertions(+), 22 deletions(-)
 create mode 100644 build/endoflife.sh
```

**Comment by Steve8291** [comment]
The option was named "noprettyicon" on line 121 and set to 0.
Then later in lines 236 and 289 it's referenced as "prettyicon". I don't want to submit a pull request because I'm not sure what the desired default value or option name was supposed to be.

**Comment by stevefxp1** [comment]
Does this mean it has been updated to remove the error condition? Should I
just update now?

**Comment by Steve8291** [comment]
@stevefxp1 No it hasn't been updated yet. Although the error won't hurt anything. I just submitted a pull request to fix it.

**Comment by jmrenouard** [comment]
Thanks for submitting, this issue seems to be closed now
Feel free to reopen if needed
