### ISSUE TITLE
Wrong calculation of InnoDB Read buffer efficiency

### ISSUE THREAD

**Issue by KeldorDE** [major/MySQLTuner-perl#83]
Hi,

you have a bug in the calculation for the "InnoDB Read buffer efficiency"

Output of MySQLTuner:
[!!] InnoDB Read buffer efficiency: 0% (18495 hits/ 1692913280 total)

But the efficiency should be 100% in this case.

To fix it, change line 989 of mysqltuner.pl from

$mycalc{'pct_read_efficiency'}=percentage($mystat{'Innodb_buffer_pool_reads'}/$mystat{'Innodb_buffer_pool_read_requests'}) if defined $mystat{'Innodb_buffer_pool_read_requests'};

to

$mycalc{'pct_read_efficiency'}=100-percentage($mystat{'Innodb_buffer_pool_reads'}/$mystat{'Innodb_buffer_pool_read_requests'}) if defined $mystat{'Innodb_buffer_pool_read_requests'};

**Comment by jmrenouard** [comment]
Thanks you for your bug reports :)

**Comment by jmrenouard** [comment]
Feel free to repoen it if last version is shown weakeness.
I have fix it and test it but we never known.

**Comment by fidoboy** [comment]
This bug is still present in november 2023. Amazing
