### ISSUE TITLE
key_buffer_size

### ISSUE THREAD

**Issue by myTepee** [major/MySQLTuner-perl#90]
Since last update, ````key_buffer_size```` recommandations are given twice:

````
[!!] Key buffer used: 22.2% (1M used / 8M cache)
[!!] Key buffer size / total MyISAM indexes: 8.0M/23.8M
````

````
Variables to adjust:
    key_buffer_size (~ 1M)
    key_buffer_size (> 23.8M)
````

**Comment by jmrenouard** [comment]
Thanks for this issues
1° Key buffer used indicated how much buffer are used in allocated ressources.
2° Key buffer size should be equals or greater than MyISAM indexes size.

I will remove advice for key buffer used.

**Comment by myTepee** [comment]
Another tip, to avoid warning when checking for bad passwords, documentation should also include to wget the .txt file.

**Comment by jmrenouard** [comment]
Can you check that advice:
key_buffer_size (~ 1M)
is no longer displayed ?

**Comment by jmrenouard** [comment]
Ok next topic there is an option --skippassword that skip passwords checking based on basic_passwords.txt.
 I will add the link in the documentation.

**Comment by jmrenouard** [comment]
Feel free to fork and pull request documentation :)

**Comment by myTepee** [comment]
````key_buffer_size (~ 1M)```` is no longer displayed.

**Comment by myTepee** [comment]
Reporting is no longer good:
````
[!!] Key buffer used: 18.4% (3M used / 16M cache)
[OK] Key buffer size / total MyISAM indexes: 16.0M/81.0M
[OK] Read Key buffer hit rate: 97.3% (67M cached / 1M reads)
````
````
Variables to adjust:
    query_cache_size (> 16M)
    join_buffer_size (> 128.0K, or always use indexes with joins)
````

````key_buffer_size```` is not recommended to adjust but it should, as it is set to 16M and total MyISAM indexes is 81M

**Comment by myTepee** [comment]
Hum...i've restarted the server and it is reporting correctly now.
I'll keep this open until i'll do some more tests.

**Comment by jmrenouard** [comment]
The calcul formula is :
$myvar{'key_buffer_size'} < $mycalc{'total_myisam_indexes'} && $mycalc{'pct_keys_from_mem'} < 95

**Comment by jmrenouard** [comment]
README updated with basic_passwords.txt download command.
