### ISSUE TITLE
using ~/.mylogin.cnf failed

### ISSUE THREAD

**Issue by kn007** [major/MySQLTuner-perl#92]
I'm using
mysql_config_editor set --login-path=client --user=user --password --socket=/tmp/mysql.sock
Using 
mysql --login-path=cilent
can access to mysql.
But when i using
perl mysqltuner.pl
it was return
Please enter your MySQL administrative login:

I also using 
sh tuning-primer.sh
it can access to mysql.

Centos 6 x64
MySQL 5.6.25

Thank you.

**Comment by jmrenouard** [comment]
My config is:
$mysql_config_editor print
[client]
user = root
password = *****
host = localhost

and mysqltuner.pl is working fine !

Can you try 
$mysqltuner.pl -S /tmp/mysql.sock

Is it better ?

**Comment by kn007** [comment]
i try it, but

> perl mysqltuner.pl -S /tmp/mysql.sock
Option s is ambiguous (silent, skipsize, socket)
 >>  MySQLTuner 1.4.9 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
Please enter your MySQL administrative login: Can't do inplace edit: /tmp/mysql.sock is not a regular file at mysqltuner.pl
        line 431 (#1)
    (S inplace) You tried to use the -i switch on a special file, such as
    a file in /dev, or a FIFO.  The file was ignored.

Please enter your MySQL administrative password:


i using back 
mysql_config_editor set --login-path=client --user=user --password --host=localhost

> mysql_config_editor print
[client]
user = user
password = *****
host = localhost

but it still

> perl mysqltuner.pl
 >>  MySQLTuner 1.4.9 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering
Please enter your MySQL administrative login: ^C

**Comment by kn007** [comment]
Any module need to install?

**Comment by jmrenouard** [comment]
Sorry, rigth way is:
mysqltuner.pl --socket /tmp/mysql.sock

Is it better ?

**Comment by jmrenouard** [comment]
Can you tell me what return the following code : 
mysqladmin ping
echo $?

**Comment by kn007** [comment]
i am try it too.Still
Please enter your MySQL administrative login:

:-(

**Comment by jmrenouard** [comment]
There is a test done with mysaladmin ping.

Can you give me your feedback for : 
mysqladmin ping
echo $?
printenv HOME
cat printenv HOME/.mylogin.cnf
cat printenv HOME/.my.cnf
Thks

**Comment by jmrenouard** [comment]
Is there any parameter in your /etc/my.cnf with login-path ?

**Comment by kn007** [comment]
Thank you 
i found the problem.
when i try 
mysqladmin ping

it's return
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'

so i try 
 mysqladmin --version

it's return
mysqladmin  Ver 8.42 Distrib 5.1.73, for redhat-linux-gnu on x86_64

damm,so i using 
ln -sf /usr/local/mysql/bin/* /usr/bin/
 mysqladmin --version

return
mysqladmin  Ver 8.42 Distrib 5.6.25, for linux-glibc2.5 on x86_64

trying 'mysqladmin ping',return
mysqld is alive

now try
mysqltuner.pl 

it's work.

thanks a lot!

**Comment by kn007** [comment]
i am sorry about that.
it's my fault.

**Comment by jmrenouard** [comment]
Enjoy you can find the source of your problem :)
