### ISSUE TITLE
Modification of a read-only value attempted at mysqltuner.pl line 503 (#1)

### ISSUE THREAD

**Issue by anikitenko** [major/MySQLTuner-perl#94]
OS: CentOS release 5.11 (Final)
Arch: x86_64
MySQL: 5.1.73-cll
MySQL packages installed:
cpanel-perl-514-DBD-mysql-4.027-2.cp1146
cpanel-mysql-libs-5.1.73-1.cp1136
cpanel-mysql-5.1.73-1.cp1136
Error:
 >>  MySQLTuner 1.5.0 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

Modification of a read-only value attempted at mysqltuner.pl line 503 (#1)
    (F) You tried, directly or indirectly, to change the value of a
    constant.  You didn't, of course, try "2 = 1", because the compiler
    catches that.  But an easy way to do the same thing is:
    
        sub mod { $_[0] = 1 }
        mod(2);
    
    Another way is to assign to a substr() that's off the end of the string.
    
    Yet another way is to assign to a foreach loop VAR when VAR
    is aliased to a constant in the look LIST:
    
            $x = 1;
            foreach my $n ($x, 2) {
                $n *= 2; # modifies the $x, but fails on attempt to modify the 2
            }
    
Uncaught exception from user code:
	Modification of a read-only value attempted at mysqltuner.pl line 503.
 at mysqltuner.pl line 503
	main::get_tuning_info() called at mysqltuner.pl line 1630

**Comment by jmrenouard** [comment]
Thanks for this bugs.

I can't successed reproduce it.

However, I found why this appears !

**Comment by jmrenouard** [comment]
Can you tell me if last commit resolve your problem for right ?

Thanks by advance,

**Comment by anikitenko** [comment]
I'll check later today and get back to you. Thank you for looking into this issue.

**Comment by anikitenko** [comment]
Yeah, the issue is fixed. Thank you!
