### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by devisbal** [major/MySQLTuner-perl#96]
The problem: same values for reached and posible:
[!!] Maximum reached memory usage: 11.3G (116% of installed RAM)
[!!] Maximum possible memory usage: 11.3G (116.58% of installed RAM)

The code:
# Global memory
	$mycalc{'max_used_memory'} = $mycalc{'server_buffers'} + $mycalc{"max_total_per_thread_buffers"};
	$mycalc{'total_possible_used_memory'} = $mycalc{'server_buffers'} + $mycalc{'total_per_thread_buffers'};

It should be I believe just be:
# Global memory
        $mycalc{'total_possible_used_memory'} = $mycalc{'server_buffers'} + $mycalc{'max_total_per_thread_buffers'};

The new result:
[OK] Maximum reached memory usage: 2.1G (22% of installed RAM)
[!!] Maximum possible memory usage: 11.3G (116.58% of installed RAM)

**Comment by jmrenouard** [comment]
Maximum reached memory usage: Memory calculation based on max parallel connections reached by MySQL
Maximum possible memory usage: Memory calculation based on max connections "allowed" by MySQL

This means that if all your connections has used by clients your server can run out of memory.

I have add some comment for this issue in the code.

	# Global memory
	# Max used memory is memory used by MySQL based on Max_used_connections
	# This is the max memory used theorically calculated with the max concurrent connection number reached by mysql
	$mycalc{'max_used_memory'} = $mycalc{'server_buffers'} + $mycalc{"max_total_per_thread_buffers"};

	# Total possible memory is memory needed by MySQL based on max_connections
	# This is the max memory MySQL can theorically used if all connections allowed has opened by mysql
	$mycalc{'total_possible_used_memory'} = $mycalc{'server_buffers'} + $mycalc{'total_per_thread_buffers'};

**Comment by devisbal** [comment]
Still there is something Wrong: 

[!!] Maximum reached memory usage: 11.3G (116% of installed RAM) 
[!!] Maximum possible memory usage: 11.3G (116.58% of installed RAM) 


For printed result the Maximum reached memory usage: is taken from Total possible memory [total_possible_used_memory] and not from Max used memory [max_used_memory] . 

Also Max used memory [max_used_memory] is never used on the code... 

There is the portion latter about Maximum memory limit that is printed as the Maximum possible memory usage [max_peak_memory] 


Memory code: 

# Global memory 
# Max used memory is memory used by MySQL based on Max_used_connections 
# This is the max memory used theorically calculated with the max concurrent connection number reached by mysql 
$mycalc{'max_used_memory'} = $mycalc{'server_buffers'} + $mycalc{"max_total_per_thread_buffers"}; 

# Total possible memory is memory needed by MySQL based on max_connections 
# This is the max memory MySQL can theorically used if all connections allowed has opened by mysql 
$mycalc{'total_possible_used_memory'} = $mycalc{'server_buffers'} + $mycalc{'total_per_thread_buffers'}; 

$mycalc{'pct_physical_memory'} = int(($mycalc{'total_possible_used_memory'} * 100) / $physical_memory); 

# Maximum memory limit 
$mycalc{'max_peak_memory'}=0; 
foreach my $key ( 'key_buffer_size', 'query_cache_size', 'tmp_table_size', 
'innodb_buffer_pool_size', 'innodb_additional_mem_pool_size', 
'innodb_log_buffer_size') { 
$mycalc{'max_peak_memory'}+=$myvar{$key} if defined $myvar{$key}; 
} 
foreach my $key ( 'sort_buffer_size', 'read_buffer_size', 'read_rnd_buffer_size', 'join_buffer_size', 
'thread_stack', 'binlog_cache_size' ) { 
$mycalc{'max_peak_memory'}+=($myvar{$key}*$myvar{'max_connections'}) if defined $myvar{$key}; 
} 


Result Printed: 

if ($arch && $arch == 32 && $mycalc{'total_possible_used_memory'} > 2*1024*1024*1024) { 
badprint "Allocating > 2GB RAM on 32-bit systems can cause system instability\n"; 
badprint "Maximum reached memory usage: ".hr_bytes($mycalc{'total_possible_used_memory'})." ($mycalc{'pct_physical_memory'}% of installed RAM)\n"; 
} elsif ($mycalc{'pct_physical_memory'} > 85) { 
badprint "Maximum reached memory usage: ".hr_bytes($mycalc{'total_possible_used_memory'})." ($mycalc{'pct_physical_memory'}% of installed RAM)\n"; 
} else { 
goodprint "Maximum reached memory usage: ".hr_bytes($mycalc{'total_possible_used_memory'})." ($mycalc{'pct_physical_memory'}% of installed RAM)\n"; 
} 

if ($mycalc{'pct_max_physical_memory'} > 85) { 
badprint "Maximum possible memory usage: ".hr_bytes($mycalc{'max_peak_memory'})." ($mycalc{'pct_max_physical_memory'}% of installed RAM)\n"; 
push(@generalrec,"Reduce your overall MySQL memory footprint for system stability"); 
} else { 
goodprint "Maximum possible memory usage: ".hr_bytes($mycalc{'max_peak_memory'})." ($mycalc{'pct_max_physical_memory'}% of installed RAM)\n"; 
} 


----- Original Message -----

**Comment by jmrenouard** [comment]
I have pushed a fix for that point.

I know that no recommandations are done for pct_max_used_memory.

Do you have a idea ?

**Comment by jmrenouard** [comment]
Thanks for reporting this issue :)

**Comment by drzraf** [comment]
This expression:
``my $key ( 'sort_buffer_size', 'read_buffer_size', 'read_rnd_buffer_size', 'join_buffer_size', 'thread_stack', 'binlog_cache_size' ``
Apparently attempt to estimate the size of a thread.
According to MySQL developpers, this is completely wrong.

Quoting
> * read_rnd_buffer_size is never even used in innodb environments
> * join_buffer_size is only used on non-indexed joins
> * read_buffer_size is also used in limited cases
> * thread stack is not always fully used (although sure, it is important one)
> * binlog cache is used for write transactions only  
> That whole formula is taken from decades old mysql error message which is stupid

* thread memory usage is one of the most important value to estimate in order to determine other limits
* thread memory calculation can not be fully determined in advance
* providing hint about it (like minimal size / possible size) would be helpful
* providing documentation about getting usage-specific thread size would be helpful
* providing a wrong (and over-estimated) value of thread size is not helpful (people may reduce max_connections or buy memory after reading about a thread-size 10 times over the reality [in my case, 2.7 MB according the mysqltuner versus 300 kB in the reality]
