### ISSUE TITLE
Use of uninitialized value $mycalc{"total_possible_used_memory"} in numeric gt

### ISSUE THREAD

**Issue by anikitenko** [major/MySQLTuner-perl#98]
I experienced syntax error:

[--] Total buffers: 1.3G global + 36.2M per thread (100 max threads)
Use of uninitialized value $mycalc{"total_possible_used_memory"} in numeric gt
	(>) at mysqltuner.pl line 1139 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.
    
    To help you figure out what was undefined, perl will try to tell you the
    name of the variable (if any) that was undefined. In some cases it cannot
    do this, so it also tells you what operation you used the undefined value
    in.  Note, however, that perl optimizes your program and the operation
    displayed in the warning may not necessarily appear literally in your
    program.  For example, "that $foo" is usually optimized into "that "
    . $foo, and the warning will refer to the concatenation (.) operator,
    even though there is no . in your program.

**Comment by jmrenouard** [comment]
Can you use the last version in github please ?

Can you give us the output with --debug option for your server ?

Thanks by advance,
JM

**Comment by Grokon** [comment]
Hello. I have that problem too. What data in debug log you need?

**Comment by jmrenouard** [comment]
all if possible :)

**Comment by jmrenouard** [comment]
Can you tell me if last version works better with 32 bits OS ?

**Comment by Grokon** [comment]
thx, now all work fine. I use Centos 6 x32.

**Comment by jmrenouard** [comment]
Thanks for reporting this issue :)
